### ISSUE TITLE
setgroup is activated too often

### ISSUE THREAD

**Issue by JacobEdelman** [qtile/qtile#1044]
As far as I can tell, setgroup is supposed to activate everytime what group is being displayed is changed. Despite this, it is apparently used much more often. For instance, when I subscribed to "@hook.subscribe.setgroup" and had it open a new window, it would be activated by the window it opened. This led to qtile being completely unresponsive as it just kept opening new windows as fast as possible.

**Comment by frostidaho** [comment]
Grepping through the code `setgroup` is only called 3 times.
It looks like the one that might fire often is in [dgroups.py](https://github.com/qtile/qtile/blob/27bc20f71b0cf7d02d735aa11940ecbdf7b4dbb8/libqtile/dgroups.py#L234).
The patch that introduced this code is [here](https://github.com/qtile/qtile/commit/4d18ad2b1fea82bae47ef24d4b3df0af177509b9). Maybe this hook is better off being `changegroup`, since `sort_groups()` is just potentially changing the order of the groups.

**Comment by JacobEdelman** [comment]
Is it possible that "handle_ClientMessage" is also causing a problem? I don't completely understand the code there, but I'm unsure if this guarantees that the hook is only fired if the group is actually changed?

**Comment by frostidaho** [comment]
The callables registered for setgroup are only ever called in response to hook.fire('setgroup'). So wherever that appears is a possibility. Try out the pull request and see if it works

**Comment by flacjacket** [comment]
I just added the link PR into develop, try giving that a shot, feel free to re-open if that doesn't address your problem.

**Comment by JacobEdelman** [comment]
So,  I'm still confused, but this is probably just my being confused and not something wrong with qtile. According to the docs, changegroup is "Called whenever a group change occurs" and setgroup is "Called when group is changed". I'm not entirely sure what either of those means. Is either of them supposed to be called when, and only when, the current group is being displayed is switched to a different group? Is one of them supposed to be called when any change is made to the current group of the form adding or deleting a window?

**Comment by JacobEdelman** [comment]
(Also, I'm not sure how to reopen this issue to be honest)
