### ISSUE TITLE
documentation questions

### ISSUE THREAD

**Issue by frostidaho** [qtile/qtile#1069]
I just have a few questions about the docs.

* Are the docs at this url based on the latest commit on master? http://docs.qtile.org/en/latest/

* What are the docstring conventions? I've only been able to find [this commit](https://github.com/qtile/qtile/commit/d9c7f45986ed189a4450f512dc7db50376c459ab)

**Comment by flacjacket** [comment]
I think the "latest" docs are actually built off of `master`, which is the latest release, rather than `develop`. I think you can see the current live build of the docs at http://docs.qtile.org/en/develop/. We generally use PEP 257 for formatting of docstrings, and use numpydoc style documentation for things like parameters and returns. Things like sphinx directives are encouraged, but not necessary, I'd say. The basic requirements are as long as it is something that compiles with sphinx without throwing warnings.

**Comment by flacjacket** [comment]
Since this question is answered, I'll close this issue.
