### ISSUE TITLE
Ability to skip xterm tests

### ISSUE THREAD

**Issue by irl** [qtile/qtile#1076]
xterm requires that a pty can be created, which isn't possible in the restrictive Debian build environment.

What would be the best way to skip the xterm tests? Can something else (xclock?) be run in place of xterm?

**Comment by flacjacket** [comment]
Yeah that would be fine, we already use xeyes and xclock in addition to xterm, we can switch to using those instead. You can see in `qtile/conftest.py`.

**Comment by irl** [comment]
I've uploaded a package to Debian where all the tests are passing 
excluding the ones that call xterm. I tried to just swap out xterm for 
xclock, but this is not as trivial as it may have appeared, as there are 
tests against window size and xclock and xterm differ. I'm sure there 
are other things I've missed also.

This is probably not urgent to fix, but ideally would be fixed in the 
next release so I can drop this patch from the Debian package and run 
the full test suite during builds.

**Comment by Terseus** [comment]
The problem with replacing xterm with xclock is that in [test_manager.py line 60](https://github.com/qtile/qtile/blob/54d5d50cd66354499952605c6d37ef870bab1243/test/test_manager.py#L60) there is a float rule that explicitly matches xclock windows (used in other floating tests), so when used in non-floating layouts tests some asserts fails.

As I see it there are two obvious solutions:
* Set the xclock window to don't float when using it in non-floating tests.
* Replace xclock with another X11 standard utility like xcalc (which is in the [Ubuntu x11-apps package](https://packages.ubuntu.com/trusty/amd64/x11-apps/filelist)).

Personally I prefer the second option because fiddling with `window.toggle_floating` in non-floating layouts tests looks ugly and error prone, however this change would add xcalc to the build requirements (or replace xterm entirely).

What do you think guys?

**Comment by irl** [comment]
xcalc is a good alternative, does not require pty allocation so would avoid the problems I'm having with xterm.

**Comment by kynikos** [comment]
I've always wondered why tests are spawning xeyes etc. instead of just using `testWindow` or `testTkWindow` (or higher-level functions such as `testDialog` or `testNotification`).
