### ISSUE TITLE
HDPI issues only with Qtile

### ISSUE THREAD

**Issue by mr337** [qtile/qtile#1089]
I am having issues using qtile on a HDPI laptop via ubuntu.

On unity everything looks great. On qtile the qtile bar looks perfect but everything else is gigantic, fonts, screen, menu bars, cursor in FF, VirtualBox, emacs, etc. Oddly enough the webpages in FF looks correct while the menu bars are gigantic, and the only app that seems to be rendering properly is Spotify. Go figure :D

First time running qtile on a HDPI laptop and banging my head on what else to tweak. To me it feels like qtile understands the resolution and dpi, but something isn't getting set and everything else is defaulting to a weird dpi. I am starting qtile via qtile.sessions file in /usr/share/xsessions.

A related issue https://github.com/qtile/qtile/issues/670 except restarting qtile after login doesn't seem to help. I have also tried tweaking the DPI via Xresources file with no luck.

Screenshots:
![unity](https://user-images.githubusercontent.com/413937/31864877-e5a7e8f0-b72a-11e7-876e-4fbb1abfe384.png)
![qtile](https://user-images.githubusercontent.com/413937/31864876-e598742e-b72a-11e7-8df7-bc1ca2f2c612.png)

**Comment by makuto** [comment]
I'm seeing the same issues.

**Comment by nazar-pc** [comment]
This is because you need to configure X11, which on 4k and similar displays makes everything gigantic, you'll see the same behavior in LightDM.

Here is my LightDM config (`/etc/lightdm/lightdm-gtk-greeter.conf`) in case you use the same greeter:
```
[greeter]
background=#000000
theme-name=Numix Git
icon-theme-name=Numix-Circle
cursor-theme-name=DMZ-White
cursor-theme-size=24
font-name=Ubuntu Regular 10
xft-antialias=true
xft-dpi=96
xft-hintstyle=hintfull
xft-rgba=rgb
indicators=~session;~language;~clock;~power
clock-format=%H:%M:%S %a %d
hide-user-image=true
```

And to fix it in regular X11 sessions you may create 2 files in `/etc/X11/Xresources`.
`fixed-cursor-size`:
```
Xcursor.size: 24
```
`fixed-dpi`:
```
Xft.dpi: 96
```

You can, of course, put everything into single file if you want.

Also you might want to install `xsettingsd` that will provide some information to GTK apps and session in general, here is my `~/.config/xsettingsd/xsettingsd.conf`:
```
Net/IconThemeName				"Custom"
Net/ThemeName					"Numix Git"
Gtk/CursorThemeName				"DMZ-White"
Gtk/CursorThemeSize				24
Xft/Antialias					1
Xft/Hinting						1
Xft/HintStyle					"hintfull"
Xft/RGBA						"rgb"
Gtk/FontName					"Ubuntu Regular 10"
GtkDecorationLayout				"close:"
```

This is X11-related question and there is nothing in Qtile to be fixed here. I had the same issues with custom session using Compiz (which Unity uses under the hood).

**Comment by mr337** [comment]
@nazar-pc Thanks for the reply. For some reason I was thinking Qtile was responsible for providing the info to the GUI libs (gtk/qt). I'll give this a shot.
