### ISSUE TITLE
Running A Custom Command When A Rule Is Matched

### ISSUE THREAD

**Issue by ScarletMetal** [qtile/qtile#1123]
Hi,
I have been using Qtile for a while now, and i really like it, thank you for your hard work!
For the most part, everything in the Qtile configuration is really logical, but there is one thing that really bugs me - it is impossible to run a custom command when a certain Rule is matched.

An example could be something like this:
`def example()`
`    print('example') `
` dgroups_app_rules.append(Rule(Match(title=["foo"]), break_on_match=False, command=example`

what do you think about it?

**Comment by ramnes** [comment]
I don't know what you want to do exactly, but did you consider using hooks?

http://docs.qtile.org/en/latest/manual/ref/hooks.html

**Comment by TheArchNemesis** [comment]
I had considered using hooks. In fact, they made me ditch i3 in favor of Qtile in the first place.
But Unfortunately there is no hook for my use case:
I'm using intellij and other jetbrains products, as well as GIMP. all of these start with a loading screen that is suppose to be in the center of the screen (and it is, in i3 for example), but in Qtile it appears at the top left corner of the screen. It just drives me crazy.

**Comment by Sweenu** [comment]
I had the exact same problem! I didn't have the time to look into it at the time but I'm gonna try and add a callback parameter to Rule. That way we could use a function that centers the window when it starts.

I admit however that having smaller sized floating window spawned in the center should be the default. I can try to look into that as well.

**Comment by TheArchNemesis** [comment]
@Sweenu That would be awesome

**Comment by flacjacket** [comment]
Well, I think the latest commit should at least fix the issue of windows not popping up in the center of the screen :)

**Comment by ramnes** [comment]
Now that the dialogs problem is fixed, do we still want this? Hooks are here for the same reason, and I don't like the idea of having two different things for the same purpose. If needed we could add more hooks.

**Comment by Sweenu** [comment]
Nice! 
As for the callback @ramnes, even though it does not seem needed anymore for now, it could still be a nice feature by passing the matched client as a parameter to the function, I think this gives much more power to the Rule mechanism. 
With a hook, if we wanted to target one particular type of client, we'd need to test for each newly opened client if it is the one we are targetting. Having several if-else under a hook instead of Rules seems less clean imo. (well, maybe I'm missing something, you tell me)

**Comment by ramnes** [comment]
I can definitely understand why you want this, and that would indeed be a great feature, but I'd rather extend hooks and make them more powerful to match your use-case than creating an alternative way of doing things. But that's just my two cents and since I don't use dgroups, I might miss something here. @flacjacket, what do you think?

**Comment by jjsullivan5196** [comment]
Hey there, new guy just resurrecting this dead issue here. I was googling through doing something in this vain, I wanted to set the netwm opacity hint on my terminal specifically. Using awesome, I could do this with their version of match/rule, since it had a parameter for window hints. 

As suggested, I was able to do something similar with hooks and the `window.Window` object. Example here:

`@hook.subscribe.client_new
def trans_set(window):
    if window.match(wmclass = 'rxvt-256color'):
        window.opacity = 0.9`

I think qtile might be helped by a more specific version of `client_new`, possibly a function-like decorator that takes arguments to a match object, and used in what would be the fastest way possible for the command API. I might work on this as a pull request, I just started using qtile and I really dig the style of configuration and extension.

**Comment by m-col** [comment]
It seems to me that @jjsullivan5196's example demonstrates how you can get the rules-based behaviour mentioned.

It _would_ be cool to do something like as you describe:
```
@hook.subscribe.client_new([Match(wm_class='firefox')])
def trans_set(window):
    window.opacity = 0.9
```

> Having several if-else under a hook instead of Rules seems less clean imo. (well, maybe I'm missing something, you tell me)

The above is functionally equivalent to just using `window.match()` in a bunch of if-else lines, but of course you'd be swapping out n `if`s for n `Match`s, so it would be basically the same and provide no advantage IMO.
