### ISSUE TITLE
Prompt widget: New windows should not steal focus from it

### ISSUE THREAD

**Issue by tych0** [qtile/qtile#122]
Also, moving focus explicitly while in the prompt widget should either close it or move focus to that window and not close it but also not lose its focus.

**Comment by kynikos** [comment]
I think the way to fix this requires setting a `focus_locked` boolean attribute either (A) globally in `manager.Qtile`, or (B) for each `window._Window`.
When the prompt widget is launched, it locks the focus (in case of (B) I guess for the whole bar's window). When the prompt widget is closed, it releases the focus. This of course would be possible in general for any window that needed to exploit this feature.
When `manager.Qtile.manage()` is called, the lock is checked (in case of (B) for the currently focused window), and `group._Group.add()` is called with `focus=c.can_steal_focus()` (requires #568) if the focus is released, or with `focus=False` if the focus is locked.

I'm ready to implement this, if you like the idea, but I need to know whether you prefer (A) or (B).

**Comment by tych0** [comment]
I think A makes the most sense, since it is a global property anyway. Looking forward to the patch!

**Comment by kynikos** [comment]
Great! A few more considerations:

* It must be made sure that the focus is always released, possibly even in cases like a widget crash, otherwise the window manager may remain in a focus-locked state until another window locks the focus and releases it (windows would still be able to be focused manually).
  Alternatively, the focus could always be released when focus is changed manually.

* Option (A) can generate race bugs, for example:
  * A window (1) locks the focus
  * Another window (2) locks the focus (it may do it automatically, without user interaction; it wouldn't receive focus automatically though because (1) has already locked it)
  * Window (1) releases the focus
  * Window (2) now cannot count anymore on the fact that the focus is locked

  Maybe this could be mitigated if the focus locking method checks whether the focus is already locked, and returns False if it is, so that the window that requests the lock can act accordingly, if it relies on that.
  I thinks these conditions wouldn't be likely to generate major problems, and the feature would still be an improvement over the current behaviour (no lock at all); we may track this kind of bug in a new report or in TODO notes in the code.

* What do we do when releasing the focus? Do we leave focus on the bar or set it to some other window? I'm not acquainted yet with Qtile's focus history, any hint will be appreciated.

* The prompt widget should close itself if focus is given to another window manually (but this is an already existing bug and might be worth another feature request).

**Comment by tych0** [comment]
On Fri, Jan 02, 2015 at 08:13:23PM -0800, Dario Giovannetti wrote:
> Great! A few more considerations:
> 
> * It must be made sure that the focus is always released, possibly even in cases like a widget crash, otherwise the window manager may remain in a focus-locked state until another window locks the focus and releases it (windows would still be able to be focused manually).
>   Alternatively, the focus could always be released when focus is changed manually.

For this it would be nice to use a context manager. I'm not sure how
easy that would be with our current codebase, though, so if we had to
use the hammer of simply unsetting the focus lock after each event
loop iteration, that would be ok with me too.

> * Option (A) can generate race bugs, for example:
>   * A window (1) locks the focus
>   * Another window (2) locks the focus (it may do it automatically, without user interaction; it wouldn't receive focus automatically though because (1) has already locked it)
>   * Window (1) releases the focus
>   * Window (2) now cannot count anymore on the fact that the focus is locked

Here you can use a semaphore instead of just a mutex (i.e. an int
instead of a bool) to indicate whether or not focus is locked. Each
window increments and decrements the int, and if it is >0, focus is
locked.

>   Maybe this could be mitigated if the focus locking method checks whether the focus is already locked, and returns False if it is, so that the window that requests the lock can act accordingly, if it relies on that.
>   I thinks these conditions wouldn't be likely to generate major problems, and the feature would still be an improvement over the current behaviour (no lock at all); we may track this kind of bug in a new report or in TODO notes in the code.
> 
> * What do we do when releasing the focus? Do we leave focus on the bar or set it to some other window? I'm not acquainted yet with Qtile's focus history, any hint will be appreciated.

I think ideally we'd put it on the last focused window. Perhaps
instead of using an int above, you can just have a stack of windows
that is pruned when a particular client unlocks focus. If the last
element of the stack is popped, you set the focus to that window.

> * The prompt widget should close itself if focus is given to another window manually (but this is an already existing bug and might be worth another feature request).

Yeah, that would be nice too :)

**Comment by kynikos** [comment]
Thanks for your input, I'll try to come up with an updated plan that answers all (or most of) these requirements.

**Comment by kynikos** [comment]
After considering all the problems that option A above was presenting, I've decided to try option B because if we make it work it seems more natural to me.

I have a series of commits in https://github.com/kynikos/qtile/tree/develop%23122 that:

* fix this bug for some applications (e.g. chromium)
* sort-of-fix it for others (e.g. xterm, the focus does stay in the prompt, but xterm's window is not tiled until another window is given focus manually)
* have strange effects for others (e.g. opera, the focus doesn't stay in the prompt, it doesn't go to opera, but it goes to a third open window)

If somebody wants to help debugging it, just fetch the branch linked above in my fork (develop#122).

**Comment by ramnes** [comment]
Fixed by 16574c10 (prompt is closed when something else acquires the focus).
