### ISSUE TITLE
DropDown is not working properly with FireFox

### ISSUE THREAD

**Issue by jcowgar** [qtile/qtile#1225]
Please see attached configuration.

I am attempting to create a DropDown in conjunction with ScratchPad for a Firefox window. The first time I press F11, Firefox appears in a normal window tiled according to the layout in my current tag. Pressing F11 does not remove/hide it. If I close that window, F11 in the future does nothing.

What I would like to happen when pressing F11 for the first time is FireFox to appear in a floating drop down. Pressing F11 a second time should hide the drop down. Subsequent F11's should drop FireFox down and contain the browser where I left it.

There is a DropDown for urxvt (F12) and that drop down works great, as expected.

my config: https://gist.github.com/jcowgar/3f9473abdba4fb9201332ce5cd12d329

**Comment by jcowgar** [comment]
BTW, in my config I just tried replacing "firefox" as the command with "google-chrome-stable" and the dropdown works as expected. Change it back to "firefox" and it becomes broken again. So, something firefox is doing... Surf also works fine.

**Comment by ramnes** [comment]
What version of Firefox is it? Did you try a newer or older version?

**Comment by jcowgar** [comment]
FireFox 63.0.1. I did not try any other version, just this one.

**Comment by jcowgar** [comment]
I'm not the best person to debug this, but I found if I add --new-instance to the firefox command arguments, then all works as expected.

Does that provide any meaningful information? It would be nice not to have to create a new instance, but not the end of the world either.

**Comment by dhannes** [comment]
The ScratchPad/DropDown behaviour of spawning and remembering processes is already described in #1156, and also seems to be the cause for the here described odd behaviour, since it is limited to scenarios where the given command spawns a new process and creates a new window.

The ScratchPad /DropDown behaviour is basically as follows:
1. the command of the DropDown is executed by `cmd_spawn` command of Qtile and the returned process id is remembered.
2. if a new client appears (hook: `client_new`), with that process id (determined by `net_wm_pid`) it is wrapped and stored by the Scratchpad group, set to floating and added to current group.
3. afterwards the windows visibility is toggled as described in [qtile documentation](http://docs.qtile.org/en/latest/manual/config/groups.html#scratchpad-and-dropdown)

If adding` --new-instance` argument to the firefox command is ok for you and does not introduce other problems it seems to be a fairly wrokaround.

**Comment by jcowgar** [comment]
Sounds good, thanks!
