### ISSUE TITLE
camelCase removal

### ISSUE THREAD

**Issue by ramnes** [qtile/qtile#1233]
Before anything, sorry for being "that guy". :smile: 

To be honest I don't like camelCase, but what I don't like even more is inconsistency. I've always had the feeling that there was a lot of camelCase names in Qtile codebase, which annoyed me, but I also had the feeling that there was even more snake_case, and thus that we should agree on a coding style once for all.

So I conducted a brief analysis of `libqtile`, and it showed me that there are 95 unique names (54 functions and 41 variable) that are written in camelCase. Those 95 names are used 669 times. Here they are:

`addGroup`, `addHandler`, `appendHead`, `archivedInput`, `backupCount`, `borderWidth`, `captureWarnings`, `clientFromWID`, `colorPixel`, `columnHeight`, `columnWidth`, `curGroup`, `currentGroup`, `currentLayout`, `currentOffset`, `currentScreen`, `currentStack`, `currentStackOffset`, `currentWindow`, `cursorId`, `customLayout`, `deleteCurrentStack`, `delGroup`, `disableMask`, `displayName`, `displayNum`, `docSig`, `docText`, `eventEvents`, `focusHistory`, `formatSelector`, `funcName`, `getAttribute`, `getElementsByTagNameNS`, `getEssid`, `getIconPath`, `getLogger`, `getOpacity`, `grabKeys`, `grabMouse`, `groupMap`, `groupName`, `ignoreEvents`, `iTouch`, `keyMap`, `layoutAll`, `layoutChanged`, `listWID`, `maildirPath`, `mapKey`, `masterWindows`, `maxBytes`, `mouseMap`, `moveToGroup`, `nextGroup`, `nextLayout`, `nextSelector`, `nextStack`, `nodeIdx`, `numlockMask`, `parseString`, `prevGroup`, `previousStack`, `prevLayout`, `registerWidget`, `removeHandler`, `resetMaster`, `rRmazA`, `screenHeight`, `screenWidth`, `sectionIdx`, `setFormatter`, `setGroup`, `setLevel`, `setOpacity`, `shuffleDown`, `shuffleUp`, `stackOffset`, `startInput`, `subFolder`, `subFolders`, `terminalWidth`, `toggleSplit`, `toLayoutIndex`, `toScreen`, `unmapKey`, `updateHints`, `updateName`, `updateState`, `userInput`, `validMask`, `widgetMap`, `windowMap`, `winHeight`

To get the list: `grep -Rh -Po '[^A-z]\K[a-z]+[A-Z][A-Za-z]+' | sort -u`.

In comparison, there are 1590 names in snake_case, which are used 5923 times (`grep -Rh -Po '[^A-z]\K[a-z]+[_][a-z_]+'`.

What is annoying here is that those 95 camelCase names are pretty important, and that a lot of them might be used in config files hacks or other user scripts, even if none of them actually is something publicly exposed by `libqtile` modules. So basically, renaming all those wouldn't be a `!!! config breakage !!!` per se, but still might end up breaking a lot of stuff on the user side.

The other annoying thing is that I don't feel like adding a deprecation warning for those 54 functions.

And yet, I really want to make the codebase cleaner, easier to maintain, make the coding style enforceable, all of that so that it's overall more welcoming to new contributors.

So how should we proceed to do that renaming, if we want to?

*Edit:* if we decide to move forward on this, should we also rename stuff like `togroup` into `to_group`, or `cw` to `current_window`? It's much less important as it doesn't directly break the PEP 8, but still, I'd love this.

**Comment by tych0** [comment]
I'm +1 on the idea, and would support a patch that just changed these all at once everywhere. I don't think (?) any of this is exposed via the lazy API, so it should be ok.

One notable exception which I think we might want to keep is the handle_* mnemonic for handling events. I routinely grep for the x11 event names, and although I could do it in snake case too, we do some dynamic dispatch based on this mnemonic, which means we'd have to programatically convert from camel to snake, which is annoying.

Also, if we do this, I think we should make travis fail if there's any camel case (modulo the one exception above). Not sure how hard this would be to get to work.

**Comment by flacjacket** [comment]
We've definitely moved some things from camel case to snake case, and I'd
be in favor of doing more to clean it up. The "right" thing to do, as you
say, is to add deprecation warnings and make the change over a couple
versions. We can tighten up the version bumps to clear them out sooner,
rather than later. If we start breaking lots of stuff at once, it will be
trickier to bundle that with lots of other changes (as you've been doing
lately :D ).

**Comment by tych0** [comment]
Yeah, it's true that because we send the qtile object along with events, a lot of these internal guts are exposed and may break some configs, but I'm less worried about that. While I have qtile-object specific hacks in my config and I know other people do, I think when you start doing surgery at that level you have to be willing to accept some breakage, or upstream your stuff into a real api call so that we'll maintain it for you.

I do think we should work pretty hard to avoid breaking the lazy.* API, though, as that's documented and absolutely everyone uses it. I don't think (?) though that any of the stuff you've described above will affect it though.

We might want to make an explicit guarantee (in the form of documentation, I guess), that libqtile.{lazy, layout, bar, widget, hook} will not break API after 1.0, but we reserve the right to refactor the qtile object at any time, so if you're doing surgery at that level you're on your own (but leave it exposed, so it's still possible). I don't think that's unreasonable, and it's mostly what we already do anyway :)

**Comment by Ryuno-Ki** [comment]
I wonder, whether it is possible tto use aliases here.

That is, start using snake case NOW, but have the camel case variant exported as well, which logs a deprecation notice, then calls the snake cased variant.

I haven't looked at the code, though.

**Comment by flacjacket** [comment]
That is definitely possible, and we have done similar things before, it is
just a lot of development overhead to manage all of that and a question of
whether that is necessary. If we are just changing internal APIs, as seems
to be the case, we can probably just make the change outright.

**Comment by ramnes** [comment]
We could do a minor release for what has been done since 0.12, then rename as much stuff as possible as long as it's not in `libqtile.{lazy, layout, bar, widget, hook}` (as defined by @tych0), and later (i.e. when we'll accept to break stuff, e.g. for 1.0) rename the few remaining stuff. How does that sound?

**Comment by tych0** [comment]
I think you can even rename stuff that's in libqtile.widget, e.g. currentStack is not exposed to users, just the lazy cmd_* stuff is. Really it's just the constructors I think we can't change.

**Comment by ramnes** [comment]
Done! See #1234.
