### ISSUE TITLE
Stack layout: lazy.layout.up() & down()

### ISSUE THREAD

**Issue by osimplex** [qtile/qtile#1251]
Stack has two methods to move the focus around windows in one stack: `up()` and `down()`, but, when I call the `up()` method, the focus go to the down window, and `down()`method behaves like `up()`, `down()` -> up.
`up()`is down, `down()` is up.

This can be solved, maybe, with a change at methods names.

**Comment by flacjacket** [comment]
It'd be great to have a small change and add some testing to show the fix :)

**Comment by osimplex** [comment]
Ref: https://github.com/qtile/qtile/blob/master/libqtile/layout/stack.py -> `stack.py`

At `stack.py:266` there is `def cmd_down(self):`.
At `stack.py:271` there is `def cmd_up(self):`.

The code works as expect, moving the focus up and down, but `cmd_down()` go up, and cmd_up()` go down. Just this.

So, there are two solutions (that are just "swaps):
* Swap the methods names
* Invert the operators at `self.current_stack.current_index` lines (268 and 273) for both methods.
  1. (268) `self.current_stack.current_index -= 1` -> `self.current_stack.current_index += 1`
  1. (273) `self.current_stack.current_index += 1` -> `self.current_stack.current_index -= 1`

**Comment by osimplex** [comment]
Ref: https://github.com/qtile/qtile/blob/master/libqtile/layout/stack.py -> `stack.py`

At `stack.py:266` there is `def cmd_down(self):`.
At `stack.py:271` there is `def cmd_up(self):`.

The code works as expect, moving the focus up and down, but `cmd_down()` go up, and cmd_up()` go down. Just this.

So, there are two solutions (that are just "swaps):
* Swap the methods names
* Invert the operators at `self.current_stack.current_index` lines (268 and 273) for both methods.
  1. (268) `self.current_stack.current_index -= 1` -> `self.current_stack.current_index += 1`
  1. (273) `self.current_stack.current_index += 1` -> `self.current_stack.current_index -= 1`

I don't know how to do the modifications and a PR _et cetera_.

**Comment by ramnes** [comment]
Okay so, I just played a bit with the Stack layout. Currently, `up` and `down` is consistent with the Max layout when windows are stacked, which is great and which we really want to keep that way. Now it is right that when you activate the split, the `up` and `down` seems reversed, due to the position of windows.

But in fact, `up` still gets you the previous window and `down` the next window, as it should. So it seems to me that the real problem is the order in which the windows are displayed, and this is what we should reverse. Or we could keep the windows in the current order and reverse `up` and `down` when the split is toggled, but that sounds weird to me.

**Comment by ramnes** [comment]
Just seeing that the Column layout does it the other way around, i.e. isn't consistent with Max and does like you proposed @osimplex. So let's do the same here and then deprecate the Stack layout so that we all use the Columns layout and maybe change its behavior some day to be consistent with Max.
