### ISSUE TITLE
Displaying powerline symbols in qtile bar?

### ISSUE THREAD

**Issue by cyruseuros** [qtile/qtile#1283]
Currently it only produces gibberish if the symbol is not part of the `widget_defaults` font. Terminal emulators handle this through fallback fonts (in one way or another), but it doesn't seem like Qtile does that kind of lookup. Is there a trick I'm missing?

**Comment by tych0** [comment]
Can't you just set a custom font for that widget that has the symbol?

**Comment by jjzmajic** [comment]
I can, and that is what I do for almost everything. But that requires a patched font instead of obeying `fontconfig` rules for some reason. I've still to find a patched font that doesn't, in one way or another, butcher the original. What I resort to now is a `TextBox` widget for each icon, with a custom font that contains _only_ icons, and a standard font for the widget itself. The trouble is, I can't set icons for dynamic widgets this way, such as the battery charging indicator.

**Comment by tych0** [comment]
I see, so I guess the problem is we need to look in the fontconfig database for this sort of thing.

**Comment by jjzmajic** [comment]
Guess so. Unfortunately I'm not of much use on the matter, only ever got deep enough into fonts to be able to easily recognize my powerline segments... Hopefully at least noticing the issue was of some help. I'll do some more work with the fontconfig file for my icon font to see if that fixes it. The trouble I see with that, is that there would need to be a separate configuration for each style of the fallback font, so 
- nerd font icons bold : nerd font icons -> source coude pro bold
- nerd font icons italic : nerd font icons -> source coude pro italic
- etc.

That seems like an awful lot of work, which I would be willing to do, but terminal emulators like `termite` seem to be able to do it without ever being told that the icon font exists, and only being instructed to use `source code pro`.

**Comment by elParaguayo** [comment]
Best way to do powerline symbols in bar is to use PowerLineDecoration in qtile-extras:
https://qtile-extras.readthedocs.io/en/stable/manual/ref/decorations.html#powerlinedecoration
