### ISSUE TITLE
memory widget displays wrong memory usage

### ISSUE THREAD

**Issue by deadsidestar** [qtile/qtile#1324]
The qtile memory widget displays the wrong memory usage, much higher usage than what htop or any other system monitor would display.

If lines 31 & 32 in memory.py were changed to the following the issue is solved.

val[key] = int(uv[0]) // 1024
val['MemUsed'] = val['MemTotal'] + val['Shmem'] - val['MemFree'] - val['Buffers'] - val['Cached'] - val['SReclaimable']

**Comment by erikdubois** [comment]
same as issue #1303

**Comment by ramnes** [comment]
The newest version of the memory widget that I merged on master should fix this. Thank you!

**Comment by arcolinuxz** [comment]
Could you consider releasing a version soon so that this new memory widget is included then we can delete our memory.py?

Keep up the good work.

**Comment by ramnes** [comment]
We're in the middle of [a big refactoring with a lot of breaking changes](https://github.com/qtile/qtile/compare/v0.13.0...master), so I doubt we'll release soon, unless it is called `1.0.0-alpha-0.0.1` or something like. :smile: 

@flacjacket your thoughts?

**Comment by flacjacket** [comment]
Oof! I didn't realize how much we had pulled in since 0.13. I think it
makes sense to try to capture everything that has changed so far, document
it, and get a release out. There have been some big changes, but most of
the user facing stuff has been renaming stuff so far. I think it'd be good
to cut a new release to reset the changes before we make big architectural
changes.

**Comment by ramnes** [comment]
@arcolinuxz FYI, 0.14.0 just got released. :+1:

**Comment by arcolinuxz** [comment]
thanks
