### ISSUE TITLE
Qtile on Arch Linux requires python-psutils for cpugraph widget

### ISSUE THREAD

**Issue by arcolinuxz** [qtile/qtile#1354]
We discovered today on the ArcoLinuxB Qtile Minimal that **python-psutils** was not installed. 
Hence the configuration we made crashed.
We think the culprit is the **cpugraph widget**.

This is our latest config.
https://github.com/arcolinux/arcolinux-qtile/blob/master/etc/skel/.config/qtile/config.py

We are working on the latest qtile from Arch Linux version 0.14-2-1 and are using the config you see in the link.

There might be more widgets that require that particular package. Only you can estimate that.

The question I would like to ask you is the following.

This is the PGKBUILD on Arch Linux.
https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/qtile

Is it today a must to have python-psutils installed as a dependency?
IF yes can you contact the maintainer to ask to change it?

**Comment by ramnes** [comment]
Yes, `CPUGraph` depends on `psutil` since #1250.

So far we've considered widgets as rather independent parts of the code, on which we see all dependencies as optional (since it's optional to use a widget or not). So if you want to use the graph widgets, you have to install `psutil`, but it won't come as a Qtile dependency.

The real issue here is that Qtile should not crash but rather give you an error text box, [as seen here](https://github.com/qtile/qtile/blob/833e7f67256a2c54a29cfda3ccd94486f8e00a83/libqtile/widget/import_error.py#L24-L29). Does the crash produce logs in `.local/share/qtile/qtile.log`?

That being said, we might want to list those dependencies as extra dependencies per widget in `setup.cfg`; @flacjacket, did you think on this already?

**Comment by flacjacket** [comment]
`extras` dependencies is exactly what I thought when I saw this pop up. I agree that it is odd that the cpugraph isn't being replaced with the import error widget.

**Comment by ramnes** [comment]
Closing in favor of #1398.
