### ISSUE TITLE
toggle_split not documented

### ISSUE THREAD

**Issue by Nebucatnetzer** [qtile/qtile#1358]
I found the toggle_split functionality in the config but there doesn't seem to be a reference in the documentation. At least when I searched for it, I found only one appearance in the qshell example:
http://docs.qtile.org/en/latest/search.html?q=toggle_split&check_keywords=yes&area=default

**Comment by ramnes** [comment]
Thank you for reporting this issue, @Nebucatnetzer. Feel free to open a PR if you want to fix it!

**Comment by Nebucatnetzer** [comment]
I see what I can do.
 I'm currently still figuring out how everything works in qtile.

Thu Jun 27 09:21:23 GMT+02:00 2019 Guillaume Gelin <notifications@github.com>:

**Comment by ramnes** [comment]
I'm going to close this in favor of #1360, and because there is not much that can be done for `toggle_split` alone (it's already listed in the example here, and I'm not sure why the search doesn't output that: http://docs.qtile.org/en/latest/manual/ref/layouts.html#columns).

Thanks again for reporting this!

**Comment by Nebucatnetzer** [comment]
Thank you for the link.
I agree that it makes sence to close this, given the additional information.
