### ISSUE TITLE
Keys doesn't work if layout is changed

### ISSUE THREAD

**Issue by zordsdavini** [qtile/qtile#1460]
I have us, lt and ru keyboard layouts. Groups are binded to numbers 1-9 and 0. But if I switch to Lithuanian keyboard layout the numbers becomes "ąčęėįšųū„“". Can I bind to keyboard button but not to letter? Alternatively, can I bind to ex. "ą"? because if I try - Qtile crashes. 
Same stuff for Russian. If I want close window I have bind to M-C-w, but in if ru is enabled w -> в :)
In dwm I think I didn't need to think about such case. It was binding to keyboard button.

**Comment by pawamoy** [comment]
I'd be interested in this as well. With the `fr` keyboard layout I was never able to use the number row. Without shift they're other letters, and with shift well... I press shift. And then I don't know if I have to put `shift` in the key definition or not. Binding to the keycode instead of keysym would solve that I guess?

**Comment by zordsdavini** [comment]
the only way to do that now is to double (or in my case triple) keybindings. Example switch to 1 group I should bind M-1, M-ą. To close window: M-S-w, M-S-в... 
But I support Pawamoy idea to bind to keycode instead of keysym. Will leave isuue opened

**Comment by zordsdavini** [comment]
closing in favor of https://github.com/qtile/qtile/issues/933
