### ISSUE TITLE
How are the tasks in TaskList sorted?

### ISSUE THREAD

**Issue by liborw** [qtile/qtile#1541]
It seems that the task in the TaskList are sorted differently than what the `lazy.layout.next()` thinks. As  when I use the `lazy.layout.next()` the focus in the TaskList jumps around but seldom on the task I would expect...

**Comment by ramnes** [comment]
Yep, can confirm.

**Comment by tych0** [comment]
This is really an architecture problem: each layout keeps its own "list" or other state of what order windows are in. There's no standardized way for TaskList (or indeed, the qtile core) to ask a layout what order its windows are currently in.

Fixing this in a nice way would enable a lot of features, including one I've wanted for a long time. Unfortunately, you'd probably have to touch each layout and understand it to figure out how to linearize things into a reasonable way. Maybe it wouldn't be that hard, though, who knows :)

**Comment by ramnes** [comment]
Options for this have been discussed in #1334 (probably among others).

**Comment by tych0** [comment]
Oh right, I forgot all about that discussion :)

**Comment by isentropic** [comment]
I feel this is especially relevant to the max layout. I have just switched to Qtile, and it'd really would become the endgame for me in case the TaskList would be sorted normally just for the max layout.

It feels that max layout doesn't have a lot of kw params, so it must fairly minimal in its codebase. Do you think there is a way to only hack the Max layout so that the order in the TaskList would be sensible at least according the to Max layout only? I understand that it might take a lot of effort to fix this for all the existing layouts (like you mentioned in the linked PR), but the most relevant is the Max, as there is no other way to tell the order and how to switch to a needed window right away. I think for other layouts the order in the TaskList is not as critical. 

In case this is out of your reach within the nearest future, do you think writing my CustomMaxLayout would let me somehow achieve this? Coming from i3 (tabs) awesome (tasklist) this is the major blockade. :(

**Comment by kapilpokhrel** [comment]
Storing windows in list instead of unordered set inside Group class seems to fix this.

**Comment by ramnes** [comment]
Really? Nice! PR welcome. :)
