### ISSUE TITLE
Anonymous telemetry

### ISSUE THREAD

**Issue by ramnes** [qtile/qtile#1576]
As discussed with @tych0 at the latest FOSDEM, I think we could benefit from some sort of anonymous telemetry on Qtile.

Things I'm interested in:
* Having an approximation of the number of people running Qtile
* Getting the exceptions that are raised (with Sentry or alike?) and the versions in use, so that we can track our changes versus actual errors, e.g. reverting a commit if a lot of exceptions are raised before someone opens an issue
* Having statistics on which distributions are running what version of Qtile, to know where we need to concentrate our efforts in terms of packaging and support

My POV is certainly biased by my contributor position, and I know this is often a smell for some people when they install and try new software (including me), so let's discuss this! Feel free to throw other ideas of interesting things to watch, also.

**Comment by ramnes** [comment]
Also, if we do this, I'd say we should have everything public: the graphs, the server-side, or anything else that comes into play.

**Comment by zordsdavini** [comment]
I think that would be very interesting information :)

**Comment by pawamoy** [comment]
Usage statistics for layouts and their respective methods?

**Comment by tych0** [comment]
On Mon, Mar 30, 2020 at 05:12:12AM -0700, Guillaume Gelin wrote:
> As discussed with @tych0 at the latest FOSDEM, I think we could benefit from some sort of anonymous telemetry on Qtile.
> 
> Things I'm interested in:
> * Having an approximation of the number of people running Qtile
> * Getting the exceptions that are raised (with Sentry or alike?) and the versions in use, so that we can track our changes versus actual errors, e.g. reverting a commit if a lot of exceptions are raised before someone opens an issue
> * Having statistics on which distributions are running what version of Qtile, to know where we need to concentrate our efforts in terms of packaging and support
> 
> My POV is certainly biased by my contributor position, and I know this is often a smell for some people when they install and try new software (including me), so let's discuss this! Feel free to throw other ideas of interesting things to watch, also.

I think it would be interesting; we could have an opt in/out that was
just a simple telemetry=True in the config.

Of course, the classic problem is that if we default it to off, we'll
only get a small amount of data, and if we default it to on, people
will complain about it uploading data by default :)

**Comment by ramnes** [comment]
> Usage statistics for layouts and their respective methods? For widgets?

Yay! Removing unused stuff! \o/

> I think it would be interesting; we could have an opt in/out that was
> just a simple telemetry=True in the config.

Yes

> Of course, the classic problem is that if we default it to off, we'll
> only get a small amount of data, and if we default it to on, people
> will complain about it uploading data by default :)

I think it only makes sense to spend time on this if we default to on, sadly

**Comment by zordsdavini** [comment]
where all data should be saved?
how often it should be resended?
should default config be avoided (ex., this is my first time in Qtile or got crash)?

**Comment by ramnes** [comment]
> where all data should be saved?

At the same place that qtile.org is hosted, I'd say?

> how often it should be resended?

Once a day, plus the exceptions when they come? We don't need any more data I guess.

> should default config be avoided (ex., this is my first time in Qtile or got crash)?

I'm not sure to understand, why you would like to avoid default configs?

**Comment by tych0** [comment]
Qtile.org is stateless on heroku, so that doesn't work, unfortunately.

I could host stuff if we need cloud disk space, though.

**Comment by ramnes** [comment]
> Qtile.org is stateless on heroku, so that doesn't work, unfortunately.

Why not? You can spawn a database on Heroku.

> I could host stuff if we need cloud disk space, though.

We'll discuss this on IRC when I'll be back there!

**Comment by zordsdavini** [comment]
> > should default config be avoided (ex., this is my first time in Qtile or got crash)?
> I'm not sure to understand, why you would like to avoid default configs?
I thought that default config means user didn't get interest after try, but maybe that is the case why we need that data.
I haven't done anything with such telemtry. That's very interesting for me. As I understand we will use some command to get, ex., json of all objects and send to store where we can analyze it. Will theming part (colors, fonts etc) be included? Other properties? Gmail passwords :D ?  
But what does it mean anonymous? Will Qtile generate some id to track changes of user or totally anonymous and we wouldn't see user changes and counting would be not very accurate.

**Comment by ep12** [comment]
- What about opening a notification window if `telemetry` is not set? The user then has the choice and is not presented with a default. However, if the message box (`Please add _telemetry_ to your configuration. For details see <URL>`) appears on every restart, the user will surely make that choice very soon. And for the default config I don't think it would be too bad to set `telemetry = True`. Most users will probably use a custom config...
- A more interesting question is the anonymization! If warnings or exceptions in the user config are thrown, the exception text contains the full path to the config files (which might include user names). Maybe `re.sub` might help with that to filter common paths, e.g. `/home/.*`, `/Users/.*`, `C:\Users\.*`...

Anonymization is a tricky thing to do. Especially when everything (including the raw database?) should be public, it is very important to check that the data is really anonymous. I think there should be some sort of checks to guarantee that the collected data does not contain any personal stuff. By that I mean qtile should only collect data about the usage of qtile's features, not what the user likes to start on login, not the full config...

Maybe the principle of data economy could be preserved if the user config would be analysed using `ast` and the like.

It might also be useful to give the user a choice to generate a report and have a look at it (`python -m libqtile.telemetry`?).  
Maybe `telemetry` should not be a `bool`, but rather a string (`'full', 'prompt before submission', 'no'). The telemetry utility could then be run in the user preferred terminal emulator and ask for consent if demanded.


I know that's a ton of ideas, but maybe they are a bit useful for you. I haven't contributed to qtile (yet?), but I am a proud user of it.

**Comment by pawamoy** [comment]
Let's not forget about the GDPR. It must be opt-in, so we cannot default to True, right?

To avoid collecting personal information, we could maybe whitelist the fields we collect. Example: never collect the contents of a widget's TextBox. Instead, just collect a book saying if it's the default value or not.

**Comment by ramnes** [comment]
Nah, analytics stuff is outside GDPR scope so far (source: I work in a data marketing company).

**Comment by ramnes** [comment]
Also, the legal definition of "opt-in" really depends on where you are on planet Earth. In some places the opt-in can be passive (i.e. default to True), in others it must be a passive opt-out (i.e. default to False), and in yet other places you have to give as much room to the opt-in than the opt-out which, in our case, would mean to default to None, I guess?

So yeah, basically, we should not care too much about the GDPR which is most likely irrelevant here, but rather about what we feel is useful to us and fair to users.

**Comment by ramnes** [comment]
@ep12 thanks for your input, lots of interesting things. Your `prompt before submission` could be my `None`. I do agree that we would have to be very careful with stack traces, and maybe we should ignore that in the first place and just raise the error string or something alike. However if everything is public, and given the kind of people that use Qtile, I have no doubt we'll have things fixed very quickly if anythings leaks!

**Comment by ep12** [comment]
I played a bit with `ast` (and `astor`), the result is [in this repo](https://github.com/ep12/qtile-telemetry-playground).
- `identity.py`: A first try to generate a unique id that does not change with updates.
- `config_stats.py`: A bit of `ast` magic to analyse the user config file without harming the user.

I recommend you `git clone` the repo and run the scripts on your machines. You should see a bit of what your config does, e. g. which features it uses, but hopefully you can't see anything that nobody except you is supposed to see.

The verbosity of the config analysis can also be changed. Maybe a `telemetry.ini` file could be introduced (the `telemetry.py` utility should not have to import all the qtile config?) where some part would reflect what my `settings` dict is, and some other part would control the bug report telemetry.

Please let me know what you think about it (if you have time - considering there are probably more relevant things to do than to implement telemetry functionality)...

**Comment by ramnes** [comment]
Wow! It's much more than what I would have done in a first version, but that's awesome!

For the identity, that's funny, it looks a lot like browser fingerprinting, and should work really well. My thoughts on this were much simpler though. I was thinking of generating an UUID or alike, putting it in a file, and then just checking if the file exist when qtile starts. As much as I like your implementation, maybe that simpler way would feel less invasive to developers that check the code? If you see other pros and cons, let's write them down.

For the config stats, again, great work, but maybe the `Imports`, `ClassDef` and `FunctionDef` would feel too invasive also? And I'm not sure what we would use them for. On the other hand I find the `Attribute` thing excellent and really useful for us.

**Comment by zordsdavini** [comment]
For me everything looks amazing :) the only things what I'm missing is Linux distribution, python version, Qtile version, screens. All other looks very interesting. Alreday want to compare :smile: 
:100:

**Comment by ep12** [comment]
@ramnes  
Well, the hash identity is persistent, even if you reinstall / update the software. One point of the telemetry stuff would be to measure the qtile community size. If I set my `startup_once` hook up to delete that UUID everytime I start qtile, I could boost the numbers, considering approximately two to four logins a day, that would be 700-1400 fake users per year. 
On the other hand: qtile is open source, so why not check out a source code and create a script that sends hundreds of telemetry packets each day? Let's make qtile the number one WM!

Honestly, the exact implementation to "calculate" an id is not really a huge deal. What really matters is that it doesn't change a lot, ideally it does change only when the user enforces a change. It is important that the id is random, not just some hardware MAC addresses chained together. In that stupid example, one could check out the MAC addresses of a friends device and look up the telemetry reports in the (open data) database.  
Really, the only two things I can think of atm that are really important is that the id is *random* and *unique* (and semi-persistent).  
Hashing some unique hardware and user metata combined with user-modifiable data (the hostname in my case) is a very simple way to achieve those goals.

I honestly had a bit of fun figuring out how to retrieve hardware related stuff in python :laughing:. 


Concerning the config stats:
I know that it might feel a bit invasive, the script parses the full user config after all. Telemetry *can* always (and often does) feel invasive. It's very important this the telemetry stuff is as transparent as air, not just as transparent as glass. Users might also send telemetry data if they don't know what they are sending, but we should really let *them* choose what they want. That's why I included those settings switches in my draft.
+ `Imports`: maybe not necessary after all (meaning it should not be transmitted, but it must be collected to enable the `Attribute` stuff.)
+ `Attribute`: everything that is not `libqtile` is removed by default. That should be okay, I think.
+ `ClassDef`: Maybe useful for *which class is subclassed the most?*, e. g. what classes miss highly demanded features? (It would be easy to only include those classes where at least one `base` is from `libqtile` I think.) This might be useful to start polls, e. g. which features are missing from ***class xy***.
+ `FunctionDef`: Similar, but probably less important. (e. g. alsa / pulseaudio volume controls? I don't know if there is such a thing in qtile now, but [my config](https://github.com/ep12/qtileconf/) (the public part) contains custom stuff. The function names will probably be descriptive without containing secrets, so maybe most users are fine sharing that data. They should definitely have a choice of course...)


That's already a lot of text for a comment, so I stop here...

**Comment by ep12** [comment]
> For me everything looks amazing :) the only things what I'm missing is Linux distribution, python version, Qtile version, screens. All other looks very interesting. Alreday want to compare smile
> 100

Jep. That would be definitely part of the telemetry packets, but this kind of metadata is fairly easy to obtain. Except the screen stuff. If you mean the number (and resolution?) of connected screens, that would be okay, I think. But if you mean a user's screen config (as in `~/.config/qtile/config.py`) that would be too much.
Maybe small details like the number of groups configured by default or the bar position / which screen edges have bars are also non-invasive. But all that should be easier to do from inside qtile / after really importing the user config.  
My `config_stats.py` does *not* import the config, it just parses it (this way it's relatively easy to get libqtile usage stats (`Attribute`), although even those are not really perfect. My `Attribute` contains `'libqtile.command.lazy.group[i.name].toscreen': 1,`, which is part of a loop (the `i` :smile:), I guess. This getitem is not ideal for comparisons / math, but I think stuff like this can be removed on the server side.

However, some of the other functionality can be implemented when importing the user config as well (e. g. class definitions). Some pathological examples might break that, e.g. classes that are not defined at the module level or deleted after they have been used somewhere. AST walking also catches those definitions. (In fact, I had to filter the `FunctionDef` nodes to not show any methods in a class body (searching for `'self'` as the first argument to the function.)

**Comment by ramnes** [comment]
Alright, thanks a lot for your inputs! I think we would gain in keeping this issue more meta though, and keep the implementation ideas for a second phase.

Does anyone has strong opinions on the telemetry idea itself, how it should behave, or how it should be done in functional terms?

Also, I'd love to hear more use-cases, i.e. what we would like to be able to achieve with the data, and only then, what we need to measure in accordance to the goal.

**Comment by ep12** [comment]
Also note that my code requires `astor` (a new dependency :disappointed:). It currently uses `astor.to_source`, but I gave up implementing that myself for every node type.

**Comment by ep12** [comment]
Some ideas, just to start a list:
1. user count
1. qtile version distribution / distro stuff
1. warnings?
1. non-critical bugs (e. g. qtile continues to work)
1. critical bugs (when qtile dies, requieres a try-except [in here](https://github.com/qtile/qtile/blob/master/bin/qtile))
1. feature usage (widget usage)
1. modified (subclassed) widgets (hints for missing features)
1. The bug stuff can be combined with the distro/python/qtile version data to detect old or conflicting versions of different parts that are requiered to run qtile (if a particular distro can be associated with lots of bug reports). (e. g. LyX *requires* `python2`, but on arch linux and the like, `python` points to `python3`). Might also give a hint when to start using newer python features like fstrings.

Bug reports can be used to create a dashboard with an overview of the most recent errors / crashes. Introspection might be useful since stack traces are not always helpful without variable values (->debug data and privacy...).

**Comment by zordsdavini** [comment]
9. layouts usage to detect not used
10. keys usage to detect what features is not used

**Comment by ep12** [comment]
@zordsdavini
Concerning 10.  
What do you mean? The types (`Key`, `EzKey`, maybe also `Click`, `EzClick`, `Drag`, `EzDrag`) or the arguments they are initialised with?

Maybe 11. Preferred `mod` key? Not really # relevant, but easy to implement and as a check that everything works (like config file size stats).

**Comment by zordsdavini** [comment]
@ep12 about 10. You've already added to attributes, we just need to identify if we will look not from initial key combination but from result command side. Maybe I've gave wrong name "used keys". Maybe "used commands" would be better. 

And how about, ex. 
```
'libqtile.command.lazy.run_extension': 8,
'libqtile.command.lazy.spawn': 15,
```
is it possible to add what it does? `run_extension` is like root for and you can see, that it contains (in my case) Dmenu: 3, DmenuRun, WindowList, CommandSet: 3. Maybe information is too personal :(
Same with `spawn`

**Comment by ep12** [comment]
Oh, I think that this is too personal, I would not give that data to anyone... The key combinations might be okay, but not the actions...
I know it's tempting to gather data and make statistics, but this kind of data is not really qtile-related (whereas the subclassing of built-in widgets is) and it's not a fun qtile-related stat (e. g. qtile users have a config size of 100 lines on average). Qtile should work with all kinds of software, so it isn't necessary to spy on what the users use. Other programs don't make a *users of our software also like* chart either. It is interesting, I know, but I don't think that should be included or at least it should definitely be disabled by default...

**Comment by zordsdavini** [comment]
ok @ep12 you persuaded me :)

**Comment by ep12** [comment]
@zordsdavini just implemented [this](https://github.com/qtile/qtile/issues/1576#issuecomment-614446138).
For me that's 92 % of all the telemetry stuff (`python config_stats.py | wc -l`). It's a very simple and stupid implementation that doesn't respect privacy at all. But try it out yourself!

**Comment by zordsdavini** [comment]
@ep12 thanks :) it's just easier to send all config content :D You are right - we don't need so more.

**Comment by tych0** [comment]
I think interesting things would be which widgets and layouts are in use, and which configurations of those people are using. This would help us get rid of some unused code, if nothing else :)

**Comment by ramnes** [comment]
Reopened because I though it would still be a nice addition even if there wasn't much activity recently.

Closing because it's not a consensus at all between maintainers. :)
