### ISSUE TITLE
Sponsoring

### ISSUE THREAD

**Issue by pawamoy** [qtile/qtile#1740]
Would you consider allowing people to sponsor the Qtile organization?

https://github.com/sponsors/accounts

Or are there already ways to sponsor Qtile?

**Comment by tych0** [comment]
I would prefer not to deal with it for a variety of reasons.

I have no problem with people getting paid to work on qtile, I just do not want qtile.org to be the one dolling out the funds.

Indeed, if folks got paid to work on qtile, maybe more of the bugs would get fixed :)

**Comment by ramnes** [comment]
Yeah, we just shortly discussed about this with Tycho today before you opened this issue, quite a coincidence! (or maybe not)

Accepting money at the project level might be cumbersome in a few ways, e.g. deciding what we should do with it, or who decides, or other kind of "serious" stuff like this. That being said I still think we could benefit from this overall but I definitely understand the cons.

As an alternative I was thinking of registering to the sponsorship program myself, just for Qtile. Then if some people wanted to send me a few coins, I would be happy to either focus on some particular issues, or just act as a middle man and redistribute the cash where needed. If the amounts would get somehow serious, which I doubt but would love to see, I would be happy to even dedicate a given amount of time per week.

Now some people here have done a lot more than me on this project, and are also much more competent than I am (especially on the internals), so if they agreed to do this rather than myself I would be really glad to not step in and give them my own money instead!

**Comment by pawamoy** [comment]
As a sponsor, it would feel weird to send money to just one GitHub account instead of the GitHub organization. This could go wrong in many ways as well. What if the person stops contributing? How do we know they stopped? What if they receive money from other sponsors, for other projects? How do they tell which part is for Qtile, and which is not?

I totally understand that managing money related thing can quickly become cumbersome, but I believe this is a necessary evil if you want to be sponsored :slightly_smiling_face: 

> What should we do with it?

Let it stack up. It's fine. You'll fund a hackathon or sprint or simply pay back the maintainers. You can also put bounties on outstanding issues.

> Who decides?

An argument in favor of sponsoring the organization rather than an individual (well, the billing account is linked to an individual so it's kind of the same...). I'd prefer the decisions to be taken in committee, with agreement of all the maintainers, rather than giving all the decision power to one person.

Also, for potential new sponsors, it's way easier to find the "sponsor" button on the org than looking at who are the maintainers, and deciding which one they should pick.

Just my thoughts!

**Comment by ramnes** [comment]
> Also, for potential new sponsors, it's way easier to find the "sponsor" button on the org than looking at who are the maintainers, and deciding which one they should pick.

Just had a look at [sway](https://github.com/swaywm/sway) and found out that you can actually add sponsor buttons for users to a project with a `FUNDING.yml` file:

![image](https://user-images.githubusercontent.com/835072/88191267-8bdee980-cc3b-11ea-841d-be880a7ffc44.png)

> What if the person stops contributing? How do we know they stopped?

Well I guess you stop sponsoring as long as you realize that things are not moving as you think they should or as they used to? That would be a great sign for the sponsored person.

> What if they receive money from other sponsors, for other projects? How do they tell which part is for Qtile, and which is not?

I don't think this is a problem. If I sponsor people some day, it's to show appreciation to their work, and I don't mind if it's mixed with the money from other persons for other projects. And again, if their work don't satisfy me anymore because they've refocused on other projects, I'd stop sponsoring, it's that simple. And I would expect the same from my sponsors if I register to the sponsorship program.

**Comment by pawamoy** [comment]
These are fair comments, which I agree with 🙂 

I'd be happy to see the maintainers in such a list for qtile!

There's one last thing that bothers me with sponsoring individual developers rather than projects, it's that their lowest tier could be too high. I'd love to sponsor *many* developers at $1-5 per month, but if they all put their lowest tier at $10, it's not possible, and I won't choose which one I want to sponsor (meaning I'll choose none of them) 😕

**Comment by pawamoy** [comment]
Hey @ramnes @tych0 @zordsdavini @m-col, I'm starting to sponsor some developers at $2/month (it ain't much, but it's a start :sweat_smile:).

Would you consider creating your sponsoring pages and adding a $2/month tier? Thanks!

**Comment by ramnes** [comment]
Thanks @pawamoy! I've just been approved for GitHub sponsor, feel free to take a look at my profile! I'll soon add a `FUNDING.yml` file to the repository and close this.

**Comment by tych0** [comment]
Sorry, just saw this. I'm not interested, but feel free anyone who reads this to disperse my $$ to other developers that are doing work you like here!

**Comment by ramnes** [comment]
I've added the `FUNDING.yml` file, we now have these shiny sponsoring buttons on the repository page. :)
