### ISSUE TITLE
Wlan widget shows disconnected, needs root privileges to show status with certain drivers

### ISSUE THREAD

**Issue by Gavlan-Wheel** [qtile/qtile#1855]
# Issue description

Certain wifi drivers let the user only see partial information, such as essid but not the signal strength, so the Wlan widget returns disconnected even though wifi is active. This happens with the Broadcom BCM4331 using broadcom-wl driver, not with the b43 one. The problem is iwconfig which returns only partial information when executed by a normal user.

# Qtile version

7d0635b8b0b4759cff244f341f8bffc14485782f

# Stack traces

2020-08-03 01:55:01,815 ERROR libqtile wlan.py:poll():L86 Wlan: Probably your wlan device is switched off or  otherwise not present in your system.

# Configuration

https://gitlab.com/gavlan-wheel/dotfiles/-/blob/master/.config/qtile/config.py

# Attempted solutions

- Modifying /sbin/iwconfig permissions
- Changing device mode and status
- Invoking the shell from the widget ( very slow and may crash/freeze qtile )

**Comment by tych0** [comment]
Can you use a setuid wrapper script or something maybe? Or maybe we should just port it to using sysfs directly?

**Comment by Gavlan-Wheel** [comment]
I can't get the wrapper to work

**Comment by arjan-s** [comment]
This issue is still present in the latest master branch. While the widget visually appears to work just fine, my log is being flooded with 5-6 messages per second like yours:
```
2022-01-14 10:34:18,005 ERROR libqtile wlan.py:poll():L78 Wlan: Probably your wlan device is switched off or  otherwise not present in your system.
2022-01-14 10:34:18,158 ERROR libqtile wlan.py:poll():L78 Wlan: Probably your wlan device is switched off or  otherwise not present in your system.
2022-01-14 10:34:18,159 ERROR libqtile wlan.py:poll():L78 Wlan: Probably your wlan device is switched off or  otherwise not present in your system.
2022-01-14 10:34:18,159 ERROR libqtile wlan.py:poll():L78 Wlan: Probably your wlan device is switched off or  otherwise not present in your system.
2022-01-14 10:34:18,231 ERROR libqtile wlan.py:poll():L78 Wlan: Probably your wlan device is switched off or  otherwise not present in your system.
2022-01-14 10:34:18,820 ERROR libqtile wlan.py:poll():L78 Wlan: Probably your wlan device is switched off or  otherwise not present in your system.
```
Have you ever found a solution to your problem? If not, I think it would be good to reopen this one.

**Comment by m-col** [comment]
@arjan-s What `update_interval` are you using? The bug seems to be in `iwlib`. Perhaps @tych0's suggestion above might work for you as a workaround?

**Comment by arjan-s** [comment]
@m-col Thank you for your answer!
My update interval is not set, so it's 1 second (the default). But when I set it to 60, it doesn't change the amount of logging errors.
I don't see how to use a setuid wrapper script, since the config just has a network interface name, not a script or executable.

**Comment by m-col** [comment]
>  My update interval is not set, so it's 1 second (the default). But when I set it to 60, it doesn't change the amount of logging errors.

Huh, I guess it's retrying on the error, perhaps.

> I don't see how to use a setuid wrapper script

I think the idea here is to write a custom shell script to get the information for you, rather than using this widget. Then you can use something like `GenPollText` to run the script and get the information. If the problem with getting the data is to do with permissions, then setting the setuid bit on the script will let it run with elevate privileges.

Alternatively we could find a different library to replace iwlib.

**Comment by elParaguayo** [comment]
Could we do some parsing of `iwconfig`?

I'm not sure I understand why `iwlib` needs elevated permissions for this.

**Comment by m-col** [comment]
> Could we do some parsing of iwconfig?

Yeah, could do. Or get the data ourselves from /sys. Whichever is easiest.

> I'm not sure I understand why iwlib needs elevated permissions for this.

I think it can sometimes be a problem when trying access such data i.e. on some machines.

**Comment by arjan-s** [comment]
Weirdly, after I started up my machine today, this error didn't appear in the log at all. I'll keep monitoring it the next few days and report back here.
If the error reappears, I'm happy to test something. But I can also write a simple script to parse the `iwconfig` output, and display with `GenPollText`, so I'd say this issue is very low priority.
Btw, `iwlib` doesn't need elevated permissions on my system. Would be really strange if it did if you ask me.
