### ISSUE TITLE
Wallpaper issue

### ISSUE THREAD

**Issue by synack0** [qtile/qtile#1859]
# Issue description.

I'm having problems with the wallpaper settings. I'm able to set or change wallpapers natively inside the _Screen_ section, but the value of _wallpaper_mode_ doesn't seem to being working properly. It doesn't matter whether _fill_ or _stretch_ values are use, the wallpaper isn't being properly set.

wallpaper_mode variable seems to be ignored by file config.

**Image:** https://pasteboard.co/JlufLvA.jpg

# Qtile version.

0.16.1.dev21+g4e6a91b0

# Config files, settings and log file.

**Qtile configuration:** https://bit.ly/3krdLpX

**/.local/share/qtile/qtile.log:** https://bit.ly/30Fk419

**Resolution:**

```
screen #0:
  dimensions:    2560x1600 pixels (338x211 millimeters)
  resolution:    192x193 dots per inch
```

**Comment by m-col** [comment]
OK I don't see anything suspicious in the config or log.

Couple questions:

- If you try using non-JPG images is there a pattern? E.g. do you find that PNGs always work fine but other types don't, or maybe the issue is exclusive to JPGs? Is it just some images?
- Could you try it again after installing gdk-pixbuf and see if that makes any difference? (gdk-pixbuf2 package in Arch, gdk-pixbuf in debian by the looks of it)

[This](https://cairocffi.readthedocs.io/en/stable/pixbuf.html) says that GDK-PixBuf is needed to decode some images, and we haven't accounted for this. Despite that, on my machine I can use both JPGs and PNGs and they both work fine with `wallpaper_mode` too, and I don't have gdf-pixbuf installed (AFAICT). Could you maybe upload an image that doesn't work with you so I could try it on my machine?

Thanks!

**Comment by synack0** [comment]
OK let's see.

- Using .PNG images causes the same.
- Reinstalling gdk2-pixbuf did not fix it.
- Also I took a fresh qtile config and set a wallpaper and the same ocurred.

**Packages installed:**

https://bit.ly/2F7iEV0

I don't understand what is going on. I had previously another installation (Arch, qtile, same packages installation, same configs) and there wasn't any problem with this. I'll see if I can make an image for you to try.

Thanks,

**Comment by synack0** [comment]
OK, I found the problem. I'd set some global environment values for scaling both GTK and QT in lightdm and qtile. The variable that cause this behavior is _GDK_SCALE_.

```
export GDK_SCALE=2
```

This is causing the wallpaper to be drawn like that.

**Comment by m-col** [comment]
So without that variable it's all good?

**Comment by synack0** [comment]
Yes, I tested with and without each variable I have set and without that in particularit works fine.

I'm closing this now. Thank you!
