### ISSUE TITLE
Is there still no way to make the bar background transparent?

### ISSUE THREAD

**Issue by vaishnavmk** [qtile/qtile#1934]
# Issue description

Is there a supported option to make the bar background transparent, without affecting the opacity of bar icons? I've searched around the documentation and didn't find anything. I don't want switch from the qtile bar.

# Qtile version

0.16.1

**Comment by wetw3rx** [comment]
I would love to know this as well. Played around with the "opacity" setting with less than optimal effect, usually with change to the bar icons as well.

**Comment by ramnes** [comment]
I've spend a few hours on this the other day and yeah, we're not quite there yet. The opacity argument controls the opacity for the window of the bar, so it's normal that everything becomes transparent. The proper way to make the background transparent would be to use a transparent color for the background ([see the formats we support here](https://github.com/qtile/qtile/blob/a987366cd58191eb6495e07469d0c698597c0ed1/libqtile/utils.py#L62-L68)), but it doesn't work because of #900 and #1059. Closing in favor of these issues.
