### ISSUE TITLE
Windows still in qtile.current_group.windows after client_new/killed hooks

### ISSUE THREAD

**Issue by elParaguayo** [qtile/qtile#1978]
# Issue description

Not sure if this is a bug or expected behaviour...

I'm trying to show the count of windows in a particular group and display that in a text box. I'm using hooks to update the count when windows are added or removed but it's not working as expected.

If I just use the `client_new` and `client_killed` hooks then, when these hooks are fired, the changes are not reflected in `qtile.current_group.windows` so the count is off by one.

I've also used the `setgroup` hook and when I change groups and go back to the old one the count is correct so this feels like a race condition where the hook is fired before the windows property is updated. 

Using `client_managed` helps on the adding on new_windows but doesn't solve the problem when windows are closed.

# Qtile version

0.16.1

# Stack traces

None

# Configuration

``` python
@hook.subscribe.startup_complete
def create_wincount_hooks():
    hook.subscribe.client_killed(wincount)
    hook.subscribe.client_new(wincount)
    hook.subscribe.current_screen_change(wincount)
    hook.subscribe.setgroup(wincount)
    wincount()

def wincount(*args):
    try:
        win_count = len(qtile.current_group.windows)
    except AttributeError:
        win_count = 0
    logger.warning(qtile.current_group.windows)
    qtile.widgets_map["window_count"].update(win_count)
```

I then have a TextBox named "window_count" in my widgets.

The logger line is just to provide output showing the windows in the current group.

Is counting `qtile.current_group.windows` the right place to look, or should I be looking for a different property?

**Comment by m-col** [comment]
Instead of client_new, you want the client_managed hook. That is fired after the
client as added to the current group. However, there is not an equivalent hook
for when a client is unmanaged -- client_killed is fired before the client is
removed from the group. This happens after client_killed is fired (`c` is the
client):

```
if getattr(c, "group", None):
     c.group.remove(c)
```

So for the client_killed part you could similarly check that the client has a
group, and if so, manually subtract 1 from the relevant count. That should give
you the behaviour that you're after.

Hope that helps.

**Comment by elParaguayo** [comment]
Thanks. That would explain the behaviour I'm seeing.

I'll try that later that.

**Comment by elParaguayo** [comment]
Works. Thank you.
