### ISSUE TITLE
add parameters to qtile-cmd command

### ISSUE THREAD

**Issue by gibranlp** [qtile/qtile#1987]
Hi

I have been trying to add a parameter to toscreen funciotn in this command

qtile-cmd -o group 4 -f toscreen

What i want to do is to set the toggle=False

Is it possible or am i just doing it wrong?

**Comment by ramnes** [comment]
Hey @gibranlp,

Only positional arguments can be given at the moment, and only as strings:  https://github.com/qtile/qtile/blob/807c84dd/libqtile/scripts/cmd_obj.py#L207-L208

The signature of the function being `cmd_toscreen(self, screen=None, toggle=True)`, you can't use the `toggle` argument without specifying `screen` first, which makes what you try to achieve impossible.

Feel free to open a PR so that we support named arguments and all Python types, not just strings. :)
