### ISSUE TITLE
[Request] Add option to draw a border around the qtile bar

### ISSUE THREAD

**Issue by Barbarossa93** [qtile/qtile#2115]
# Issue description

As per our reddit [discussion](https://www.reddit.com/r/unixporn/comments/kzd6zt/qtile_genome/gjpj43c?utm_source=share&utm_medium=web2x&context=3) @ramnes , I wanted to make a request to add a new option for the qtile bar to have a border drawn around it. I imagine this would work similar to polybar in that you can specify the border width, color, and sides to draw a border. To take it a little further, being able to draw multiple borders would be _fantastic_, but not necessary. From the screenshots in the linked post, I'm able to create a border effect by using three seperate [eww](https://github.com/elkowar/eww) windows; One for the top and bottom of the bar to create the bubble effect on the widgets, as well as a gray bottom border to outline the bar itself. While this works, it's not an ideal solution. If I need to restart qtile, then the eww windows that are creating padding end up underneath the bar and then I need to refresh them to get them back on top of the qtile bar. For those trying to get a similar effect, see my [autostart](https://github.com/Barbarossa93/Genome/blob/main/.config/qtile/autostart.sh) and eww [config](https://github.com/Barbarossa93/Genome/blob/4a08d3cfd0900807aefaa9f9241a6dbf926c549b/.config/eww/eww.xml#L149) for how I did it. You also don't need eww for this, you could also achieve the same effect with empty polybars.

I'd be happy to take a stab at this myself, but I'm no pythonista and fully expect to not be able to figure it out. If someone can tell me the relevant files to look into, I'll give it a shot anyway.

Alternatively (or in addition), creating padding/margins around the widgets such that the background color of the bar can "peek" out from underneath the widget (such that the widget total height is smaller than the full height of the bar) would also get the same effect and would be a fantastic addition to the bar config options.

# Qtile version
0.16.2.dev189+g18ff9899

**Comment by m-col** [comment]
Hooking up the bar to it's window's `paint_borders` method and giving it a
corresponding option is likely a trivial change. Multiple borders would then
also be possible if/when the multiple borders PR is merged. I'd also like to see
this.

If you wanted edge-specific control over borders then looking into the bar's
`Drawer` may be a nicer interface to paint to the window, but it may get messy,
particularly if you wanted edge-specific, multiple borders or arbitrary patterns
or something. TBH this isn't something I'd necessarily push for merging into
libqtile because I think it would get messy and used by very few people (you and
me lol). However I'd certainly be happy to work with you to work out something
that works for us that we can use in our configs and get the same result (may be
hacky). Of course feel free to try the `drawer` related changes to see if it's
not messy... maybe it'd be fine.

**Comment by elParaguayo** [comment]
I saw a few posts about this in the qtile-dev forum. Agreed that boxing the entire bar should be straightforward enough. 

For the single edge approach, I'd also assume that you need to draw this but I'm not sure how well that works with widgets that draw themselves on top of the bar. I also have some widgets that draw a line at the bottom as a status indicator (e.g. when my TVHeadend server is recording, the widget shows a red bar at the bottom). I wouldn't want conflicts between that and the bar border.

It's probably doable but it feels like it could be complicated!

As a matter of curiosity, I'll take a look and see what happens when we use the Drawer to draw a single line.

**Comment by elParaguayo** [comment]
Had a quick play with this. So, you _can_ draw a single border:
![single_border_1](https://user-images.githubusercontent.com/946265/105078190-83019000-5a85-11eb-9c1c-dc88f4ecdc48.png)

However, when a widget redraws itself but doesn't trigger a whole redraw of the bar then you lose the border (unfortunately, my screenshot program triggers a redraw of the bar so I can't capture this!)

You'll also see that, in the first image, the border cuts off the highlighting.

You could fix this by increasing the bar's height for the border but limit the widgets to drawing in the part that excludes the border but that's a slightly bigger rewrite to the code.

**Comment by Barbarossa93** [comment]
@m-col I'm thinking of taking a shot at it this weekend. Do you know where exactly in Drawer.py would be a good start? It's all a bit overwhelming at this point. Also, I think you'd be surprised, I'm willing to bet there'd be at least dozens of us who would use this feature! Dozens!

@elParaguayo Hmm, I'd imagine that the border would add onto whatever the specified height of the bar (similar to polybar). I guess there'd have to be a function that would add the border pixel size to the bar size to create a new full height. All in all, promising stuff! Could you share what you have somewhere? I'll probably try and work from that

**Comment by elParaguayo** [comment]
@Barbarossa93 yes - that's the same idea as I was trying to explain in my last paragraph.

As for my code, it's very basic as I was just testing an idea. I put this at the end of `def _actual_drawer` in `bar.py`:
```
        self.drawer.set_source_rgb("800000")

        # The drawer is the size of the whole bar so, to draw the border at the
        # bottom of the bar, I've drawn the border at the top of the drawer and
        # then placed it at the bottom of the bar. Ugly.
        self.drawer.fillrect(0,
                             0,
                             self.width,
                             2,
                             2)

        self.drawer.draw(offsetx=0, offsety=self.height-2, height=2, width=self.width)
```

**Comment by m-col** [comment]
> I'm willing to bet there'd be at least dozens of us who would use this feature! Dozens!

Fair enough :)

> Do you know where exactly in Drawer.py would be a good start?

I think @elParaguayo has already covered the important parts to be honest! In the snippet above, `self.drawer` is an instance of the `Drawer` class, which is defined within drawer.py. The methods in that snippet are likely all of the ones you'd need to use from the bar.

The tricky part might be in reserving bar area around the widgets by adjusting the widgets to create their own `drawer`s using different geometry.

What would the configuration look like?

**Comment by cr1ogen** [comment]
Many things can be done in qtile surely, but the configuration of the config file is very technical for "common" users like me, luckily I know how to copy and paste xD. Excellent work your configuration @Barbarossa93

**Comment by desprit** [comment]
Yeah, having a top+bottom padding in a Bar OR top+bottom border around a Bar would be great. @Barbarossa93  I like Bubble effect that you made in Genome.

**Comment by Masacaai** [comment]
The ability to draw internal borders would open the doors for some really cool designs!
This was what I had in i3 before switching to Qtile:

![20210218_160818](https://user-images.githubusercontent.com/59050442/108355155-de997780-7203-11eb-823b-85129c1030ac.jpg)

Looking forward to being able to do something similar in Qtile as well!

**Comment by Barbarossa93** [comment]
@m-col Sorry for the long delay, but I've finally had some time to think about this. I think in terms of the configuration, What makes sense to me in defining the size is to provide a list (I think that's the right python term?) for internal bar thickness, border thickness left side, right side, etc. so something like `size = [ 56, 8, 0, 8, 0 ]` just like how `margin` is done. The default color of the borders should take up the background color that is likely already defined in `widget_defaults`. In terms of border color, that gets tricky. The best I can think of is something like `bar_border_color = [ color1, color 2, color 3, color4 ]` where this could be defined in `widget_defaults`. What do you think?

**Comment by m-col** [comment]
I think that sounds clean enough, though instead of extending the existing `size` parameter maybe just add a `borders` parameter that mirrors the margin parameter. Keeps things consistent and familiar :) The same logic for `border_colors` would work, one colour (a string) or a list (of 4 strings) would be managable and clear for specifying those.

However I'm not sure what you mean when you're talking about `widget_defaults`. I thought this was for the bar itself, rather than the widgets?

**Comment by Barbarossa93** [comment]
Nice, that does make more sense to have a separate borders parameter! I'll take a look and see how the existing parameters are parsed in libqtile.bar.Bar and see if I can add the new ones there

For some bizarre reason, I thought bar parameters had to be passed to widgets. Totally off my rocker there, disregard that!

**Comment by m-col** [comment]
Sounds good :) Feel free to ask if you want any more pointers on how to go about
implementing it

**Comment by elParaguayo** [comment]
Makes sense for me to pick this one up as it's similar to my decorations PR (#2489)

**Comment by elParaguayo** [comment]
Had to rethink my approach on this but have made some progress. Have got it working so you can draw border on the bar and you can customise size and colour of each edge individually.
![20210801_185556](https://user-images.githubusercontent.com/946265/127780847-21be272b-8a98-40d1-91df-047279c7036f.png)
![20210801_185756](https://user-images.githubusercontent.com/946265/127780850-f99c9829-c58c-4baa-9adf-2c2681167535.png)

Needs a bit of work with interaction between `margin` and `border` but coming along...
