### ISSUE TITLE
Running shell command from the config makes qtile not load correctly.

### ISSUE THREAD

**Issue by Valleriite** [qtile/qtile#2165]
# Issue description

Running a command using os.system at the end of the default config(os is imported after the other imports in the default config)
and then launching qtile using lightdm shows a black screen with a working mouse pointer,nothing else.

# Qtile version
0.16.1-2

# Stack traces
non
# Configuration

Default config the changes are explained above.

**Comment by Valleriite** [comment]
The command executed was ulauncher after I swapped it to ls qtile launches,
that's weird.

**Comment by m-col** [comment]
Can you post your full config? You mean just sticking `os.system("something")` within the top level of your config?

If so, that isn't a bug, it is expected, and not a good way to launch something. The process you are launching is blocking execution of Qtile. That's why `ls` is fine, because it exits very quickly, and presumably `ulauncher` does not. What are you trying to do?

**Comment by Valleriite** [comment]
no I am using that command at the very bottom of the config file,on top I did import os after the other imports

**Comment by Valleriite** [comment]
> What are you trying to do?

trying to auto start some apps

**Comment by m-col** [comment]
Sorry, I meant 'top level' to mean unindented i.e. not within a function or anything. You can use the `startup_once` hook and hook a function to it. Inside that function you should add your commands. For example:
```python
from subprocess import Popen

@hook.subscribe.startup_once
def auto_start():
    Popen(["something"])
    Popen(["something", "else", "with", "arguments"])
```
`subprocess.Popen` will run the command in the background so that Qtile's execution can continue, whereas `os.system` will block.
