### ISSUE TITLE
Too many decimal places printed in memory widget

### ISSUE THREAD

**Issue by montdor** [qtile/qtile#2230]
# Issue description
Recently, the memory widget was given the ability to use different units (hooray!). But now, it is printed to 15-ish decimal places. I'm sure all that is required is a floor function somewhere, I just thought I would mention the bug

# Qtile version

0.17.1.dev6+g82cc88fd

# Configuration
Relevent portion of my configuration:

>            
        widget.Memory(
                        font="UbuntuMono Nerd Font",
                        format = '{MemUsed}G/{MemTotal}G ',
                        measure_mem = "G",
                        update_interval = 1,
                        fontsize = 14,
                        foreground = colors[5],
                        background = colors[1]
                        ),

**Comment by elParaguayo** [comment]
You should be able to change that in the format string e.g.
```
format = '{MemUsed:.2f}G/{MemTota:.2f}G '
```

**Comment by ramnes** [comment]
I think a `round(x, 1)` would be a good default, yeah. I'm not even sure we want to make this configurable, since the unit is; if users want more precision, they can just switch to a lower unit.

**Comment by Masacaai** [comment]
Maybe we can configure the widget to give no decimal places when a value isn't specified? It would be a small change, but it would be more convenient than having to specify the decimal value as .0f

**Comment by elParaguayo** [comment]
Just to play devil's advocate here, you may want 1 decimal place when showing `G` but for `M` and `K` you're probably happy with 0. Do you want to hard code like that?

Also, shouldn't [this line](https://github.com/qtile/qtile/blob/master/libqtile/widget/memory.py#L60) be `K` rather than `B`?

Happy to update as necessary once we're agreed on an approach.

**Comment by Masacaai** [comment]
> Just to play devil's advocate here, you may want 1 decimal place when showing `G` but for `M` and `K` you're probably happy with 0. Do you want to hard code like that?
> 
> Also, shouldn't [this line](https://github.com/qtile/qtile/blob/master/libqtile/widget/memory.py#L60) be `K` rather than `B`?
> 
> Happy to update as necessary once we're agreed on an approach.

Yeah, you're right. I think it's best we leave it up to the user to choose the decimal places they want.

On the topic of KB, I did notice that B had been used in DF.py instead of K. I might have changed it to K in memory.py , but I just chalked it up to my ignorance and kept it as it was in DF.py

If K is supposed to be the right unit there, we gotta make changes in DF.py as well.

**Comment by m-col** [comment]
The default value for `format` appears to be `"{MemUsed: .0f}{mm}/{MemTotal: .0f}{mm}"`. Isn't that what we want?

**Comment by Masacaai** [comment]
Is this issue resolved? 
Should the actual units be K instead of B?

**Comment by elParaguayo** [comment]
Decimal places is configurable and unit issue was fixed in #2437. Closing.
