### ISSUE TITLE
Gaps on bar toggle

### ISSUE THREAD

**Issue by entropyhotpot** [qtile/qtile#2282]
When you use a keybind to toggle a bar qtile does not correctly put the gaps in when the bar returns to the screen. 

I noticed that it seems to have issue with existing windows on the screen so the gaps worked fine around the top and side but on the bottom underneath where I had the bar return, my gap settings were ignored.

I guess that maybe the existing windows on the screen need to be redrawn to take in the bar again and have the correct gaps

Prior to toggle
![21-03-09_08-12_366x94](https://user-images.githubusercontent.com/80286865/110382903-a9b86c00-80af-11eb-8255-edfe31f6061d.png)

After toggling the bar
![21-03-09_08-12_358x113](https://user-images.githubusercontent.com/80286865/110382889-a58c4e80-80af-11eb-9887-112a0c688734.png)

The only way to get it back to normal is to restart qtile

**Comment by Fabien-Bernard** [comment]
Bug reproduced.

### Quick workaround
Reload config  file.

### Analysis

The "show" method of the "Bar" class is suspicious.

When we hide the bar, the size of the bar is set to 0, losing the calculation of the size if a margin was specified (see _configure).
When we unhide the bar, the size is put to the initial size of the bar, whatsoever margin was specified.

### Possible Fix

When hidding, before setting the size to 0, save its value with an additionnal attribut.
When unhidding, set the size with this new attribut instead of the initial size.
