### ISSUE TITLE
CheckUpdate widget add line strip to custom_command? [feature request]

### ISSUE THREAD

**Issue by yobleck** [qtile/qtile#2311]
# Issue description
The custom_command doesn't have the line strip option that the built in cmd_dict has.

self.sutr at:https://github.com/qtile/qtile/blob/master/libqtile/widget/check_updates.py#L62 reads from the dict,
but on:https://github.com/qtile/qtile/blob/master/libqtile/widget/check_updates.py#L79 it just says zero.

It would be nice if the custom_command allowed for a tuple format. 
For example on Manjaro `custom_command=("pamac checkupdates", 3),` would make sense.

example code change starting at:https://github.com/qtile/qtile/blob/master/libqtile/widget/check_updates.py#L77
```
else:
    updates = self.call_process(self.custom_command[0], shell=True);
    self.subtr = self.custom_command[1];
```

some error checking to ensure compatibility with previous versions might be necessary. I'm not comfortable making the pull request my self since I'm new to git, but hopefully I'm not out of line to post here.

# Qtile version
0.17.0

**Comment by ep12** [comment]
Thanks for opening that issue! It is definitely an option that should be configurable since `custom_command` already exists. If you really don't want to create a pr on your own, I could do that. But feel free to use this small issue as a chance to learn git! I am relatively new, too, but the most important bits are learned quickly. I personally played through https://learngitbranching.js.org which still sometimes comes in handy to check the commands in a sandbox before doing anything wrong. Tell us/me how you like to proceed and we'll help you with that.

**Comment by yobleck** [comment]
I guess I'll take a crack at making a pr.

My first question his how should I handle backwards compatibility?
If I make custom_command take a two tuple as an argument I could add a check to convert strings into the first item in the tuple with the second value defaulting to 0.
Or I could make a new command like custom_command_line_strip which takes integer values (and defaults to 0).
The latter option would be easier to implement and have better backwards compat but would be messier for the user.
The former option would look cleaner but would require another update at some point to remove backwards compat.

**Comment by yobleck** [comment]
whoops didn't mean to do that

**Comment by ramnes** [comment]
> If I make custom_command take a two tuple as an argument I could add a check to convert strings into the first item in the tuple with the second value defaulting to 0.

LGTM

**Comment by ep12** [comment]
> The former option would look cleaner but would require another update at some point to remove backwards compat.

Maybe not even that, because the default value of `0` might be fine for many users. I agree with you and ramnes that the first option is probably preferable.  
Side remark: It is your pr, so you are free to choose which option sounds best to you. Doesn't mean that you can't ask or that the choice should be random, but small design changes are not set in stone. Just give it a go, you can always change things later on. It's not a shame to force-push because the ci tests can be hard to satisfy sometimes.

**Comment by yobleck** [comment]
I have a preliminary version that works with arch's pacman.
but obnoxiously it doesn't work with manjaro's pamac because pamac returns a non 0 exit code when there are updates available
which causes call_process to return `subprocess.CalledProcessError`.
I'm checking with them to see why that is. In the mean time is there any documentation or other files I should update in my fork before I start doing more testing?
new changes here: https://github.com/yobleck/qtile/commit/40872f9334b5884ac097f1e3352ba6a2ba4dab9c
sorry its kind of messy. I'll clean it up when I'm done testing

**Comment by ep12** [comment]
> I have a preliminary version that works with arch's pacman.
> but obnoxiously it doesn't work with manjaro's pamac because pamac returns a non 0 exit code when there are updates available
> which causes call_process to return `subprocess.CalledProcessError`.
> I'm checking with them to see why that is. In the mean time is there any documentation or other files I should update in my fork before I start doing more testing?

Some subprocess functions automatically check the return value and raise a `CalledProcessError` if it is not 0. Maybe try out another method. I haven't had a look at the diff yet, but the subprocess call probably is already in there. So maybe we need to check for non-zero exit codes ourselves (backwards compat), but I can't suggest anything just yet.

Regarding other files: There should be a test for this widget (hopefully?), so it would make sense to add a test to assure that the instantiation with the new argument handling code works well. If you have `tox` installed (from your package manager or from pip) you can run it with `tox -e py39 -- test/{path_to_test}` assuming you have python 3.9 installed. Other environments are `py37`, `py38`, `pypy`, `mypy` and some others. Also run `tox -e pep8,format` at some point.

Furthermore, you can add an entry to the CHANGELOG if you like.

> new changes here: https://github.com/yobleck/qtile/commit/40872f9334b5884ac097f1e3352ba6a2ba4dab9c

Cool, I'll have a look at it!

**Comment by ep12** [comment]
I added a comment to your commit, I hope you can find it. Comments to pull requests are displayed in the conversation and are therefore easier to find, so you might want to open yours already.
The behaviour of `pamac` to return code 100 is so annoying. Maybe you should add yet another option `expected_return_code` and check if the command we ran returned the desired code. Counting lines when the code differs probably doesn't make sense at all, so checking for it is necessary I think.

**Comment by yobleck** [comment]
https://github.com/yobleck/qtile/commit/c3e0fab5e3778939ccf0047e74b541405d537b35
All checking and parsing moved to _init_. Now _check_updates only runs command and handles error

Turns out the solution to the pamac 100 exit code was under my nose the whole time. CalledProcessError has an .output property that can get the update info even with the error code. .output returns and empty string when there is no output so it should be consistent with past versions.

**Comment by ep12** [comment]
That `__init__` looks great, exactly what I was thinking of :+1: ! I am still not sure what is best to do when the return code is unexpected. Of course we could count the lines, but that might only an indicator how long an error description is and not how many updates there are. So this is a point for discussion when the pr is open. Feel free to start yours right now if you like!

---------------

If you know how to deal with branches in git it would be good to create a branch for the pr and reset your local master to `upstream/master` (`qtile/master`). That makes it easier to rebase your work when the upstream development branch changes or when you want to squash commits later on. Don't fear all that vocabulary, I really learned and understood it just a couple of weeks ago. **If you want to skip this, just open a pull request to merge your master branch.** (Made that bold because this is the most important sentence in this second part: it really is optional)

If you don't have
```sh
$ git remote show upstream
* remote upstream
  Fetch URL: https://github.com/qtile/qtile/
  ..............................^^^^^ this is the important bit.
  ...
```
then you can add the `upstream` remote with `git remote add upstream https://github.com/qtile/qtile/`.
_Example_: I would do `git remote add yobleck https://github.com/yobleck/qtile/` to checkout and test your work on my machine.  
After that remote is set up, you can run the following commands (in order!)
``` sh
$ git checkout -b checkupdate_widget_custom_command_subtr_feature
$ git status
On branch checkupdate_widget_custom_command_subtr_feature
...
$ git branch -f master upstream/master
```
and hooray, you have added a branch for your feature and master and upstream/master are in sync again. 
After that you just need to push your branch:
```sh
$ git push --set-upstream origin checkupdate_widget_custom_command_subtr_feature
~~or~~
$ git push --set-upstream yobleck checkupdate_widget_custom_command_subtr_feature
```
depending on how the remotes are configured.

If you want to use separate branches in the future, is is easier to `git checkout -b some_feature` them from master. Then you don't have to worry about all that stuff above.

Phew, that text got _a bit_ long... :smile_cat:
