### ISSUE TITLE
[RFC] Embracing an additional community with archived discussions

### ISSUE THREAD

**Issue by Mithrandir2k18** [qtile/qtile#2368]
Hi, just a random fan and user here. I hope this is the right place to put this discussion.

I have switched to qtile on my main machine and I really love it. The documentation is also great and allows for easily extending functionality. However, what I really miss as a user is some kind of repository where I can browse "best practices" to implement some specific thing.

It's easy to find nicely riced configs here on github on some dotfile repos, but if I for example want my qtile config to work with my desktop, laptop and laptop docked into two extra monitors, it took me quite a while to find [this issue](https://github.com/qtile/qtile/issues/2300) where such a config was posted. Variable monitor counts isn't even covered in the [Screens part of the documentation](http://docs.qtile.org/en/latest/manual/config/screens.html). If I am unlucky, I'd either reimplement something somebody else already got working or browse other users configs for hours until I find something; neither is ideal.

I bet questions like these have been raised on the IRC many times now, but since IRC typically isn't archived anywhere, new users will have to browse the internet to find questions scrambled over [multiple](https://stackoverflow.com/search?q=qtile) [SE](https://unix.stackexchange.com/search?q=qtile) [sites](https://superuser.com/search?q=qtile), an underpopulated [subreddit](https://www.reddit.com/r/qtile/) and probably many more.

I hereby propose to explicitly embrace a single additional community, which archives discussions for future users that may have the same questions(a specific SE site/Subreddit/etc.), in the README and documentation, so that new users know where they can ask "How do I configure" questions and find past questions as well.

**Comment by elParaguayo** [comment]
We've got the docs and the [wiki](https://github.com/qtile/qtile/wiki). What would a new community add that can't be captured in those two?

Don't get me wrong, I'm all in favour of having good documentation but having it split over numerous sites doesn't seem ideal.

**Comment by ramnes** [comment]
Have a look at the Discussions tab here, it's exactly why we decided to enable it. :)

**Comment by m-col** [comment]
> We've got the docs and the [wiki](https://github.com/qtile/qtile/wiki). What would a new community add that can't be captured in those two?
> 
> Don't get me wrong, I'm all in favour of having good documentation but having it split over numerous sites doesn't seem ideal.

And the historical issues (and now discussions) that also represent a source of snippets that aren't elsewhere.

I think that actually highlights @Mithrandir2k18's point. Accumulated knowledge on Qtile is already split over numerous sites and it is not ideal. I actually forgot we even _had_ a wiki! 

There is a lot of great stuff buried within github (I don't consider those SE sites or reddit "official") and it would be great to have a central place for that. IMO discussions are better than wikis because they are more approachable and feel less permanent, but wikis have the advantage of being _just_ the snippets, with a nice contents list etc. Going back to OP:

> I hereby propose to explicitly embrace a single additional community, which archives discussions for future users that may have the same questions(a specific SE site/Subreddit/etc.), in the README and documentation, so that new users know where they can ask "How do I configure" questions and find past questions as well.

We can certainly make it more clear to users where information can be found, and can explicitly say "Try searching through old Github issues and discussions and check the wiki, as it's very likely what you're asking for has been asked before". We could also restrict feature requests / configuration questions to Discussions, limiting Issues to issues (we should update the issue template for that). If a user (@Mithrandir2k18) thinks it is unclear then it probably is :p

As a semi-related question... I've never used the google mailing list (because i was put off by it being google), but when I have looked at things on it it does seem similar in format to github's Discussions. If that is the case, should we perhaps stick to just one? My vote is obvious, but I'm all for democracy, though the advantage of Discussions is that we can convert Issues to them.

**Comment by kaistian** [comment]
> As a semi-related question... I've never used the google mailing list (because i was put off by it being google), but when I have looked at things on it it does seem similar in format to github's Discussions. If that is the case, should we perhaps stick to just one? My vote is obvious, but I'm all for democracy, though the advantage of Discussions is that we can convert Issues to them.

My vote would be a mailing list since mail is superior to web bases discussion IMO.
I try to contribute to the mailing list when I think I know the answer and would never participate in a web based discussion forum.

**Comment by m-col** [comment]
Clearly I have misunderstood how the google thing works and I should sign up!

**Comment by kaistian** [comment]
Google Groups is mailing lists but also have web frontend.
To use the web frontend I think you need a gmail address, but to sign up to the mailing list from your preferred address just send a mail to qtile-dev+subscribe@googlegroups.com

Since mailing list is public anyway I don't have a problem with Google hosting it.

**Comment by elParaguayo** [comment]
I like both.

The mailing list is great as I automatically receive notifications of new
questions.

The GitHub discussions page is also good as it's easier to display code,
reply to particular comments in a discussion etc.

If there are topics/questions that come up repeatedly then the suggests the
docs are lacking something so, ideally, we should be updating them.

**Comment by Mithrandir2k18** [comment]
Thanks @m-col for highlighting the key points more eloquently than I could ;) You got it exactly right. I didn't know about GitHub discussions being a thing and simply overlooked it it seems, and I must admit, I didn't check out the wiki, as so many other projects have the wiki page simply be a mirror of their documentation homepage. A "where can I ask questions?" entry in the FAQ would be nice :)

Mailing list and GitHub discussions both look great, expect questions and hopefully useful answers on there from me in the near future! ;)
