### ISSUE TITLE
Instruction for Fedora 34 are wrong.

### ISSUE THREAD

**Issue by emanuelep57** [qtile/qtile#2451]
I am a new Fedora user, I am used to tiling window manager, and in this period I decided I wanted to try qtile. So today I installed fedora and tried to install qtile. The first method I see reading the documentation is "sudo dnf -y install qtile", I don't know what's wrong with this method exactly, but doesn't work. After I tried to log in I would always receive "error in the configuration", I suppose some missing dependencies, because I copied the sample configuration, the same I am using right now.
So anyway, for a working qtile installation it's necessary to build from source, installing all the dependencies, cloning the repo and doing "pip install .", after that, Qtile won't be listed in the gdm sessions, to have it among the sessions in gdm all you need to do is : 
sudo nano /usr/share/xsessions and paste this :
[Desktop Entry]
Name=Qtile
Comment=Tiling window manager
TryExec=/usr/bin/qtile
Exec=qtile start
Type=XSession

This is the only solution I came up with which was perfectly working

**Comment by ura43** [comment]
I can reproduce the Problem.
Running `find / -name config.py 2> /dev/null | grep qtile` returns `/usr/lib/python3.9/site-packages/libqtile/config.py` as the only entry. 
This is not a configuration file and shouldn't be copied into your .config folder.
Qtile usually puts a config.py in .config/qitle and has a `libqtile.resources.default_config` as a fallback.
Since neither of those are available, propably due to a mishap in packaging, qtile returns the configuration error as there is no configuration to read.

**Comment by Alteus** [comment]
There is Qtile 14.2 in the Fedora repos. I installed it successfully with "sudo dnf install qtile".
[https://src.fedoraproject.org/rpms/qtile](url)

**Comment by Alteus** [comment]
The Qtile package in Fedora repo is 14.2 version, which is 2 years old. 

Changelog of 0.15:
"- qtile now copies the default config if the config file does not exist"
So Qtile usually puts a default config only since 0.15.

For 14.2 try to use its default config.py, it's in the release archive:
[https://github.com/qtile/qtile/releases/tag/v0.14.2](url)

This is it:
[config.zip](https://github.com/qtile/qtile/files/6566732/config.zip)

**Comment by srizzling** [comment]
Is there any potential for a later version of qtile to be packaged up into fedora without having to build from source?

**Comment by srizzling** [comment]
hmm oh I see - it seems like the RPM is maintained over at another git repo: https://github.com/qtile/qtile/pull/2201 interesting...

**Comment by clotodex** [comment]
Don't know if this is still a problem, but for your personal use you could use an installation script. With a virtualenv you can install qtile in any folder and symlink the binary to for example .local/bin/qtile
I wrote one already for wayland since packaging is broken there in general right now (#3756) but it can be adapted to X (feel free to drop an issue). https://github.com/clotodex/qtile-install-script

**Comment by jwijenbergh** [comment]
This no longer applies, docs have been changed regarding this it seems http://docs.qtile.org/en/stable/manual/install/fedora.html
