### ISSUE TITLE
cmd_reset function is not using my ratio value

### ISSUE THREAD

**Issue by RielPi** [qtile/qtile#2457]
The function `cmd_reset(self, redraw=True)` in [xmonad.py](https://github.com/qtile/qtile/blob/master/libqtile/layout/xmonad.py) supposed to reset all windows to a ratio of `0.5` or the ratio I set in the config file?

I don't use the default ratio of `0.5` which is used in `_med_ratio = 0.5`.
I added a variable under `_med_ratio`  called `reset_ratio` with the value I use for ratio and replaced in `cmd_reset()` function, `self.ratio = self._med_ratio` for `self.ratio = self.reset_ratio`.

I don't know how to grab the ratio I set in the config file and use the value for `reset_ratio`, my Python knowledge is a bit limited for this. :sweat_smile:

**Comment by elParaguayo** [comment]
Are you working with a modified version of `xmonad.py`? If so, can you paste it here?

If you've modified the code so that `cmd_reset` is just looking for the `self.reset_ratio` value then you don't need to define the attribute in `xmonad.py`, you can just define `reset_ratio=...` in your config e.g. in your layouts `layout.MonadTall(reset_ratio=...)`. However, please note, if `reset_ratio` is not defined in the `defaults` list in `xmonad.py` you'll get an error if you try to reset but haven't set the attribute via your config.

Alternatively, `med_ratio` is just a class attribute so you should be able to change it in your config by having a line `layout.MonadTall._med_ratio = ...`. You could add this before `layouts` is defined.

**Comment by RielPi** [comment]
I am using the default version of `xmonad.py`. I was able to workaround this, bare in mind I just omit other lines with `...` which they remain the same:

- I added `_reset_ratio` variable to a "default value"
- if statement in `__init__` to check if `ratio` value is different from the default one
- assign the value of `self._reset_ratio` to `self.ratio` in `cmd_reset`

```python
...
    _left = 0
    _right = 1
    _med_ratio = 0.5
    _reset_ratio = 0.5

...

    def __init__(self, **config):
        _SimpleLayoutBase.__init__(self, **config)
        self.add_defaults(MonadTall.defaults)
        if self.single_border_width is None:
            self.single_border_width = self.border_wi>
        if self.single_margin is None:
            self.single_margin = self.margin
        if self.ratio != 0.5:
            self._reset_ratio = self.ratio
        self.relative_sizes = []
        self.screen_rect = None

...

    def cmd_reset(self, redraw=True):
        "Reset Layout."
        self.ratio = self._reset_ratio
        if self.align == self._right:
            self.align = self._left
        self.cmd_normalize(redraw)
```

I could fix this behavior by just adding `if self.ratio != 0.5:  self._med_ratio = self.ratio` in `__init__` but I'm not sure what `_med_ratio` does in other functions.

I tested this by adding and removing `ratio` in the config file.

**Comment by elParaguayo** [comment]
`_med_ratio` is only used in 2 places: in `cmd_reset` and `_maximize_main`. Looking at that latter function, the purpose of the `_med_ratio` seems to just be a value that's in between `max_ratio` and `min_ratio` so the layout knows whether to increase or decrease the size.

Based on that, it looks like the requirements are just to define a `max_ratio` and `min_ratio` and have your default ratio be somewhere in between those limits.

**Comment by RielPi** [comment]
Got it, I left `_med_ratio` with `0.5` to avoid some issues with `max_ratio` and `min_ratio`. I've been testing with different ratio values and it's working well the `_reset_ratio` variable :tada:
