### ISSUE TITLE
Firefox - Right Click Menu Bug

### ISSUE THREAD

**Issue by christopherbui** [qtile/qtile#2460]
# Issue description
In Firefox browser: Right clicking to bring the pop up menu causes the cursor to instantly select the first option from the pop up menu. It appears that the cursor is somehow overlayed with the menu and instantly selects an option.

This bug is present both on desktop and laptop. I tested the right click on chrome, and there is no issue present.

# Qtile version
version 0.17.0

# Configuration
I am using the default [configuration](https://github.com/qtile/qtile/blob/master/libqtile/resources/default_config.py)

**Comment by m-col** [comment]
I can't reproduce. Do you use a custom cursor configuration?

**Comment by ChristopherBui3** [comment]
> I can't reproduce. Do you use a custom cursor configuration?

Nope. I am running off a fresh Arch install, all configurations are by default. I have not configured anything.

**Comment by desdemona2** [comment]
i don't think this is a qtile specific problem, I had same problem with dwm in both chrome and firefox, maybe it is caused by X

**Comment by ChristopherBui3** [comment]
> i don't think this is a qtile specific problem, I had same problem with dwm in both chrome and firefox, maybe it is caused by X

I see. How did you work around the problem when it was occurring on dwm? I'd appreciate any suggestions.

Also, I noticed that this bug occurs when the pop up menu appears below the cursor when right clicking. When the pop up menu appears above the cursor, it functions as normal.

**Comment by desdemona2** [comment]
> > i don't think this is a qtile specific problem, I had same problem with dwm in both chrome and firefox, maybe it is caused by X
> 
> I see. How did you work around the problem when it was occurring on dwm? I'd appreciate any suggestions.
> 
> Also, I noticed that this bug occurs when the pop up menu appears below the cursor when right clicking. When the pop up menu appears above the cursor, it functions as normal.

unfortunately i havn't resolved it and honestly i didn't tried to fix, as now my menu doesn't pops under my cursor. But in my previous build of arch (was just a test build to understand little about arch before shifting) my menu was appearing under cursor and it automatically runs the option below it. But that is now rendered in such a way that my popup menu doesn't appear under my cursor. I think that it is possible for you too, you just need to remove all xserver elements from your system (remove dependencies too) and reinstall it again.

And i think right click is configured in arch in such a way so that when it is pointing on a menu item, it will execute that and maybe that is the default behaviour (that is just a possibility as i obeserved on many arch ditros if you hold right click and move the cursor to a menu item and after releasing the button it will execute the item under the cursor), and to change the behaviour of mouse buttons or keyboard buttons you can edit files under /usr/lib/udev/hwdb.d , which specifies the default behaviour of keyboards, mouse and other devices. And for that you need expert opinion as i don't know which file to edit as it contains whole lot of files.

**Comment by ChristopherBui3** [comment]
Thank you for you input desdemona2. I know others should be able to replicate this bug easily as I have not done any modifications to my stock Arch and Qtile system. Using firefox on Gnome / Breeze did not have this bug.

**Comment by shaansubbaiah** [comment]
Have a similar issue, temporary fix was to open `about:config` in Firefox and set `ui.context_menus.after_mouseup` to `true`. 

Qtile 0.17.0
Firefox 88.0.1

**Comment by desdemona2** [comment]
> Have a similar issue, temporary fix was to open `about:config` in Firefox and set `ui.context_menus.after_mouseup` to `true`.
> 
> Qtile 0.17.0
> Firefox 88.0.1
> 
> edit:
> Similar issues have been reported on i3 and dwm aswell, so it might just be a Firefox issue.
> 
> ```
> https://unix.stackexchange.com/questions/418163/firefox-context-menu-placement-under-dwm
> 
> https://lumeh.org/wiki/linux/i3-firefox-context-menu-alignment-issue/
> ```

Yes this can be used as a workaround just don't let your menu appear under your cursor.
Try this in any application other than firefox like chrome, your file manager: Hold right button, when menu appears, while holding your mouse button move your mouse so that your cursor is now below one of the actions defined in the menu. If it executes the option than mouse is configured by default to do that as far as i can think of. And firefox is the one who is putting menu-item under the cursor.

**Comment by desdemona2** [comment]
This isn't occuring if i am in max, bsp or any other layout which doesn't shift pixels too much from border. But if you are in modes like matrix, monadtall, ratiotile or in other layout where there are pixel shifts, firefox doesn't seems to handle this well. That is why this problem was on my dwm too on any tiling window manager. This stack answer says it all.

**Comment by ChristopherBui3** [comment]
> Have a similar issue, temporary fix was to open `about:config` in Firefox and set `ui.context_menus.after_mouseup` to `true`.
> 
> Qtile 0.17.0
> Firefox 88.0.1
> 
> edit:
> Similar issues have been reported on i3 and dwm aswell, so it might just be a Firefox issue.
> 
> ```
> https://unix.stackexchange.com/questions/418163/firefox-context-menu-placement-under-dwm
> 
> https://lumeh.org/wiki/linux/i3-firefox-context-menu-alignment-issue/
> ```

This method works! Does changing this config setting affect firefox usability in any other way? If not, then I would think that this issue could be closed.

**Comment by m-col** [comment]
Looks like Firefox just had a big update. Does this problem still happen even without the `about:config` setting changed?

**Comment by shaansubbaiah** [comment]
> Looks like Firefox just had a big update. Does this problem still happen even without the `about:config` setting changed?



The issue is still present when the `about:config` parameter is not changed. 

Tested on Firefox 89.0 with the new Photon UI.
