### ISSUE TITLE
[Feature Request] Set properties on Bar

### ISSUE THREAD

**Issue by MithicSpirit** [qtile/qtile#2526]
# Issue description

The bar(s) should have properties like `WM_CLASS` set. This would be useful for setting up rules in `picom` or similar.

# Qtile version

`0.17.0` (installed from Arch repos)

**Comment by ramnes** [comment]
Did you try using `"QTILE_INTERNAL:32c = 1"`?

https://github.com/qtile/qtile/issues/1515#issuecomment-805888721

**Comment by elParaguayo** [comment]
@ramnes one thought on that approach, if we do that, there's no way to differentiate between the bar and other internal windows (e.g. popups). Is there any benefit to treating them differently?

**Comment by MithicSpirit** [comment]
> Did you try using `"QTILE_INTERNAL:32c = 1"`?

That worked. Thank you.

> Is there any benefit to treating them differently?

Some people might want popups to have rounded corners but not the bar, so I think that would be helpful.

**Comment by m-col** [comment]
It's a bit awkward to implement  this internally because the backend (which creates the windows) doesn't know what the window is being used for, and the `Bar` and `Popup` classes don't know which backend is being used to create their window (and this is X11-specific). So -1 from me for doing anything about this in libqtile.

Reason 2 is "some people might want ", and reason 3 is how easy it is to implement in one's own config:

```py
mybar = Bar(...)

@hook.subscribe.startup
def _():
    mybar.window.window.set_property("QTILE_BAR", 1)
```

With the picom rule being "QTILEBAR:32c = 1"

**Comment by ramnes** [comment]
Sounds fair enough to me. :)

**Comment by Verushan** [comment]
With specific mention to picom, I managed to match the Qtile bar using "QTILE_INTERNAL = 1" (without needing the WM_CLASS setting on my window). Just in case anyone visits this issue later, this fixed it for me.
