### ISSUE TITLE
dpi not working on Hdpi laptop

### ISSUE THREAD

**Issue by hackedWifi** [qtile/qtile#2568]
# Issue description
When launching qtile. The bar is small and its text small as well

I have to set my font to 28 in order to be able to read everything. I have set Xft.dpi=200 in my ~/.Xresources. This settings has worked for other window managers without issues.
# Qtile version
0.17.0

# Stack traces

2021-06-21 15:39:02,410 WARNING libqtile lifecycle.py:_atexit():L38 Qtile will now terminate                                                                                                 
2021-06-21 15:39:07,869 WARNING libqtile loop.py:__aenter__():L30 importing dbus/gobject failed, 
# Configuration
deault_config.py

**Comment by tych0** [comment]
Yes, we do not have variable DPI support right now. There are several PRs that aren't quite done that address this, if you would like to take them up.

**Comment by Magnitudexx** [comment]
I understand that there hasn't been any or much progress done to this, but playing around a little in wayland i found a problem relating to this. In Wayland, the compositor must handle the resolution/dpi/scaling itself rather than in X11 that have randr and xrandr doing that functionality. I am not much of a developer myself so i can not look in to this.

**Comment by kovasap** [comment]
This might be helpful: https://github.com/qtile/qtile/issues/1494#issuecomment-1009497797

**Comment by ramnes** [comment]
Closing in favor of #1494
