### ISSUE TITLE
Documentation for layout-specific keybindings

### ISSUE THREAD

**Issue by kovasap** [qtile/qtile#2571]
I noticed at https://qtile-dev.narkive.com/KB0yShYE/keyboard-action-based-on-the-current-layout-possible that there is a relatively-easy way to set up keybindings on a per-layout basis.  Is there any official documentation about this that can be linked to from the layouts page?  I feel like this would be a pretty common sticking point for users of multiple layouts like MonadTall/Wide + Stacks (like it is for me).  

Also, is that link the best way to do this?

**Comment by elParaguayo** [comment]
I've typically seen multiple commands bound to keys as being the more "typical" approach but, if that causes issues, the idea of having a bound function which runs a set command based on the layout should also work.

**Comment by m-col** [comment]
Since that thread was made, there has been a nice addition to the lazy interface that can be used to only allow their execution under certain conditions. Currently there are two conditions that can be used (and can be used together:
```py
# For a specific layout
Key([mod], "a", lazy.function(myfunc).when(layout: str = 'max'))
# When a floating window is focussed (default True)
Key([mod], "a", lazy.function(myfunc).when(when_floating: bool = False))
```
I don't believe this is in the docs, but for sure should be.

And as @elParaguayo says, you can pass multiple lazy objects bound to a keybinding, which allows for things like this:
```py
Key([mod], "a", lazy.function(max_func).when(layout: str = 'max'), lazy.function(columns_func).when(layout: str = 'columns'))
```
In this case the same key combo will trigger these two commands. Without the `when` bits, they'd both be executed every time. But with the `when`s, you'd essentially be binding layout-specific function calls to the same key.

**Comment by elParaguayo** [comment]
I wasn't aware of the `when` bit. That's very cool.

I've put the docs on my To Do list but happy to cross it off if someone else gets there first!

**Comment by m-col** [comment]
Right? I only found it recently. Would be a great way to get
application-specific bindings by letting it support a `Match` object.

**Comment by elParaguayo** [comment]
Ha. I was just checking the source and thinking exactly the same thing.

**Comment by kovasap** [comment]
Just to verify I understand how to apply when:

If I have this in my config:

```python
    Key([mod, "shift"], "h", lazy.layout.swap_left()),
    Key([mod, "shift"], "l", lazy.layout.swap_right()),
    Key([mod, "shift"], "j", lazy.layout.shuffle_down()),
    Key([mod, "shift"], "k", lazy.layout.shuffle_up()),
```

I could have these keybinds apply only during a certain layout by doing:

```python
    Key([mod, "shift"], "h", lazy.function(lazy.layout.swap_left).when(layout: str = 'max')),
    ...
```

Or would it be:

```python
    Key([mod, "shift"], "h", lazy.layout.swap_left.when(layout: str = 'max')),
    ...
```

?

**Comment by m-col** [comment]
Kind of a mix of the two :)

The `lazy.function(something)` was an example using `lazy.function` (and an
argument to it) but this could be anything, such as `lazy.layout.swap_left()`
(with no arguments, but _is_ called). So like your second one but calling
`swap_left`:

```python
     Key([mod, "shift"], "h", lazy.layout.swap_left().when(layout: str = 'max')),
     ...
```

**Comment by kovasap** [comment]
Hmm that doesn't seem to work for me:

```python
keys = [
    # For Columns Layouts
    Key([mod], "k", lazy.layout.left().when(layout = '2cols')),
    Key([mod], "j", lazy.layout.right().when(layout = '2cols')),
    Key([mod], "k", lazy.layout.left().when(layout = '3cols')),
    Key([mod], "j", lazy.layout.right().when(layout = '3cols')),
]
layouts = [
    layout.Columns(name='2cols', num_columns=2, **layout_theme),
    layout.Columns(name='3cols', num_columns=3, **layout_theme),
]
```

These keys have no effect.

**Comment by m-col** [comment]
I don't think you can bind to a set of keys multiple times. From looking at the
key grabbing code I think repeat bindings will replace previous bindings, so
that only your two 3cols bindings would work. Is that the case? To bind multiple
things to the same keyset, pass them as further arguments to `Key`:

```py
Key([mod], "k",
     lazy.layout.left().when(layout = '2cols'),
     lazy.layout.left().when(layout = '3cols'),
)
```

**Comment by kovasap** [comment]
Your snippet works perfectly, thanks!

**Comment by elParaguayo** [comment]
@mcol could we add a generic boolean condition test to `when`. I was just wondering if we could do something like
```
lazy.reload_config().when(qtile.core.name=="x11")
```

There are other ways of doing this but just an idea.

**Comment by kovasap** [comment]
Maybe when would accept a function that returns a boolean?

**Comment by m-col** [comment]
> lazy.reload_config().when(qtile.core.name=="x11")

I don't like this because it's a second way to do this:
```py
if qtile.core.name=="x11":
    keys.append(Key(mods, key, lazy.reload_config()))
```
but with less clarity and internal added code.

> Maybe when would accept a function that returns a boolean?

This sounds like it could be good, like:
```py
def condition():
    return some_bool
keys.append(Key(mods, key, lazy.reload_config().when(func=condition)))
```

However it's pretty similar to just doing:
```py
def action():
    if some_bool:
        do_some_stuff_here()
keys.append(Key(mods, key, lazy.function(action))
```

I think both are a bit redundant and imply a second canonical approach for doing the same thing, when there should be one obvious way to get this behaviour.

**Comment by elParaguayo** [comment]
Fair enough. Just a thought and certainly not needed. Thanks for the considered answer.

**Comment by elParaguayo** [comment]
Just adding to this... I'm not sure the `keys.append` approach is always going to be a viable option where that key is already bound to another action. I would assume that if you have two `Key` objects bound to the same key then the last one will replace any earlier ones.

If that is the case (and I've not checked the code to see what happens in that scenario) then you'd either need the ability to `append` an action to an existing key or the ability to have to test a condition for the key via `when`. So, maybe there is something to this here.

Looking forward to m-col telling me I'm wrong again!

**Comment by m-col** [comment]
>Looking forward to m-col telling me I'm wrong again!

You're pretty right this time ;)

Check out `Qtile.grab_key` - this is what registers the keybinding for a given
`Key` object with the backend. The `Key` is added to the dictionary
`Qtile.keys_map`:

```py
self.keys_map[(keysym, mask_key)] = key
```

The dictionary keys are keysym and modifiers for key combo, but the values are
of type `Union[Key, KeyChord]` rather than `List[Union[Key, KeyChord]]`. I don't
see why it couldn't be. Indeed `Qtile.mouse_map` actually does this: it has type
`Dict[int, List[Union[Click, Drag]]]` so multiple `Mouse` objects can be bind to
the same mouse button. I think that approach is more intuitive, especially
considering that if you have a bunch of bindings for the same key combo (which
might be common when a user makes use of the `when(layout=X)` functionality)
that are somewhat unrelated - why define them in the same `Key`? And the issue
that you mention: subsequent bindings with the same key combination silently
delete previously bound `Key`s.

**Comment by elParaguayo** [comment]
Yes - that sounds like a good approach.
