### ISSUE TITLE
KP keys for numeric keyboard not working

### ISSUE THREAD

**Issue by matheusfillipe** [qtile/qtile#2572]
I am on the last commit. If I create a keybinding with KP_1 or KP_2 it doesn't work but if I change to normal 1, 2, 3 it does work. Those are supposed to be the numerical keyboard keys and I can confirm my numeric keyboard is working and xev does see it as KP_1, KP_2 ....

**Comment by m-col** [comment]
Did this only stop working when you updated the commit? I ask because I recently started getting loads of warnings from xkbcomp that look like "> Warning: Could not resolve keysym XF86Macro10" but this is unrelated to Qtile. I'm guessing it's some update that triggered it, though I haven't found any functionality changes (though the warnings are very annoying).

Like you mentioned on IRC, libqtile/xkeysyms.py isn't there anymore. https://github.com/qtile/qtile/commit/59653ab8642c14fce5aa0a65d06c95f5b3cc8ea2 moved it into the x11 backend module. The commit was a simple file move and update imports, so not sure how it could have caused this. However if you do find that the commits before that work fine then that would be helpful in tracking this down.

Do you see any log entries about this?

**Comment by matheusfillipe** [comment]
> Do you see any log entries about this?

Nothing at all. Neither when I press or start.

> Did this only stop working when you updated the commit?

No. It wasn't working on 2e181cb708c134f6490fe2f62982bbd669131f9f so it was before the xkeysyms.py file change. I couldn't test much earlier commits.

**Comment by m-col** [comment]
Would you be happy to check commits further back to see if it worked at a past commit? If the issue persists then something other than Qtile changed.

**Comment by matheusfillipe** [comment]
No it never worked to me. Maybe it doesn't work on X11 at all?
I went way back to 0a61002aef5035300ec9279922cb57ac4847bef5 which was version 1.6.1 or something testing with xephyr and it never works (xev from inside xephyr sees my numpad keys as KP) so I guess it should work there too, but it never does.

**Comment by matheusfillipe** [comment]
Turns out I had to use the keys that xev uses when num lock is turned off, not when it is turned on. So I turned off numlock and opened xev and turns out the keys I thought were KP_1, KP_2, KP_3, KP_4 and KP_5 are actually: `KP_End, KP_Down, KP_Next, KP_Left, KP_Begin` on that order

**Comment by matheusfillipe** [comment]
This helped: https://github.com/qtile/qtile/issues/2283#event-4432515613
