### ISSUE TITLE
Pomodoro widget duplicates the prefix and suffix texts of the fmt key

### ISSUE THREAD

**Issue by U1s2e3r4n5a6m7e** [qtile/qtile#3070]
```
widget.Pomodoro(
    fmt='prefix{}suffix',
),

widget.TextBox(
    fmt='prefix{}suffix',
    text='TEXTBOX'
),
```

### 1. Pomodoro widget

_expected to display:_

> **prefix**POMODORO**suffix**

_actual:_

> **prefixprefix**POMODORO**suffixsuffix**

### 2. TextBox widget (for example)

_expected to dispay = actual:_

>**prefix**TEXTBOX**suffix**

## Description:

- If there is prefix or suffix in **fmt** key at Pomodoro widget, It doubles the text of prefix or suffix

`qtile -v: 0.18.1`
`logs: nothing relevant`
- [x]  I have searched past issues to see if this bug has already been reported. *

**Comment by elParaguayo** [comment]
I'm a bit confused by this. Are you saying it actually prints the word "prefix" twice?

Pomodoro has a number of different prefixes which are set via configuration options rather than the `fmt` variable so I can see why you could end up with `prefix{pomodoro prefix}pomodoro{suffix}`.

Can you post a screenshot?

**Comment by elParaguayo** [comment]
Thanks. I can recreate this. It's very odd.

Will look to get it fixed!

**Comment by elParaguayo** [comment]
This is actually the same issue as #1998.

#3073 should fix this for you.

**Comment by U1s2e3r4n5a6m7e** [comment]
Thanks for the fast response I will try this. And Thanks all you guys for Qtile and supporting Pango, It's life saver :+1:
