### ISSUE TITLE
Widget for updatable image

### ISSUE THREAD

**Issue by zordsdavini** [qtile/qtile#3094]
I don't want to reinvent the wheel, so will check before.
I use GenPollText for my keyboard layout indicator but instead I want to see the flag (image). As I change layout the image should be changed. Do Qtile has such widget or proper way to do that?

**Comment by m-col** [comment]
I don't think we have something like that, but it should be pretty straight forward to get what you want, especially if you update the widget as part of the same operation that changes the layout itself.

There are probably a few ways to do this. The most elaborate would be  making a `GenPollImage` widget. The simplest would be to add a method to the `Image` widget so that it can be updated with a new image, and then using that method as part of whatever operation you are using to change the layout. This latter approach would require you to use something like a Qtile keybind to change layout, so wouldn't work so well if you're changing layouts from scripts or something.

**Comment by zordsdavini** [comment]
@m-col I thought to create GenPollImage that updates from the command by getting new image path. Should it have something more?

**Comment by m-col** [comment]
If all you want to do is provide the widget with a new image from a command, then I think you best bet would be to add a command to the `Image` widget (e.g. `Image.cmd_update`). A `GenPollImage` implies that it is polling, so if you don't need the polling, then the update command is the way to go.

**Comment by zordsdavini** [comment]
@m-col tried to write something. The hardest part is to script in config.py, because there is no documentation or I don't know how to find :D So, the question is how to declare that `cmd_update` that I could call it as `update`? In config.py I can reach only like:
```
@lazy.function
def z_next_keyboard(qtile):
    call(['xkb-switch', '-n'])
    filenames = {
        'us': '~/.config/qtile/flags/en.png',
        'lt(sgs)': '~/.config/qtile/flags/sgs.png',
        'ru(phonetic)': '~/.config/qtile/flags/ru.png',
        }
    keyboard = check_output(
            ['xkb-switch', '-p'],
            shell=True).decode('utf-8').replace('\n', '')
    qtile.widgets_map.get('image').cmd_update(filenames[keyboard])
```

**Comment by m-col** [comment]
Yeah that looks about right! Most of that internal stuff isn't documented because big changes happen every now and then e.g. `cmd_X` commands will soon drop the `cmd_` prefix - something to bear in mind if you're using this kind of custom function. Of course, this would be automatically fixed with `qtile migrate` when that change is made.

To be honest, if the use case is just images for the keyboard layout then maybe such a feature could just be added to the `KeyboardLayout` widget.

**Comment by zordsdavini** [comment]
@m-col I used KeyboardLayout before but it has some issue with options, tried to fix but time after time it process as I don't expect. So, switched to simple GenTextPoll. In my case it works well now (speaking the true, I had to add cron to recheck do I have all layouts and recreate on failure). But Image.update functionality can be used in more places, so it is useful
