### ISSUE TITLE
XWayland: second xwayland window doesn't receive input

### ISSUE THREAD

**Issue by arjan-s** [qtile/qtile#3280]
When opening multiple X applications through the new XWayland support, they don't ever receive input. Only the first opened window gets the input, and all input actions done in more recently opened X applications get performed in the first one. When the first window is closed, the second window becomes the first (FIFO like) and gets all input from all XWayland applications.

This only happens with XWayland windows, all Wayland windows correctly receive input when focused.

**Comment by m-col** [comment]
If I open two xterm windows I can type and click into both of them just fine. Is there a specific kind of window (e.g. electron-based) that the problem is limited to? Also, is this one or more monitors, and if multiple, does it persist with just one? There are some input issues with multiple monitors and xwayland currently.

**Comment by arjan-s** [comment]
I'm afraid you have some good points there... I tested it with several combinations of vscode, gimp and element, but 2 of them are electron apps. And I also have a dual monitor setup. I'll test this later again to narrow it down.

**Comment by cr1ogen** [comment]
Same here. Y try with Steam, Spotify, and firefox xWayland. firefox wayland works fine

**Comment by cr1ogen** [comment]
https://github.com/qtile/qtile/issues/3259#issuecomment-1022806339

**Comment by cr1ogen** [comment]
Don't forget about this bug, it should be a priority in wayland xD

**Comment by m-col** [comment]
Lol, I actually did forget about it. I'll bump it up :wink:

**Comment by m-col** [comment]
If you drag the windows around does anything change? Like if you have two windows, and one isn't getting input, if you drag one to the far left and one to the far right, do you start to see input in the two windows? I'm beginning to think that the XWayland server's view of window positions is wrong, and its not relaying input how we expect.

**Comment by m-col** [comment]
If the 2 windows take up the same position, but on 2 different groups (so one is unmapped, but if it was mapped, they would overlap), the input in the overlapped area goes to the one that is "above" the other, even though it is unmapped.

Is this consistent with everyone else's experience?

**Comment by m-col** [comment]
OK, I got it! What a weird one. Basically, the X11 clients are also managed at the wlroots level (below Qtile), and a few months ago wlroots made a change to not restack X11 windows: https://github.com/swaywm/wlroots/pull/2915 While I dont think this affected us (because I don't think we had xwayland support at that time), it gives you an idea of how the x11 client management is abstracted away so that we don't have to do it. I only discovered this now because my local git copy of sway (which I was learning from) wasn't updated yet to account for this wlroots change!

So, what do we have to do? As mentioned in the wlroots PR, we need to manually restack x11 clients when we activate them so that they are above the rest in the Z axis. I guess x11 clients never get 'unmapped' from the point of view of the X server..? Not entirely sure how xwayland works tbh. We need this PR for pywlroots: https://github.com/flacjacket/pywlroots/pull/83, probably in a new pywlroots soon, and then this PR: https://github.com/qtile/qtile/pull/3507

**Comment by cr1ogen** [comment]
> If the 2 windows take up the same position, but on 2 different groups (so one is unmapped, but if it was mapped, they would overlap), the input in the overlapped area goes to the one that is "above" the other, even though it is unmapped.
> 
> Is this consistent with everyone else's experience?

Yes, i have the same experience.

**Comment by arjan-s** [comment]
Same here. Input works fine when two xwayland windows are both visible (tiled next to each other or on different monitors), but when they 'overlap', input is sent to just one of them (not necessarily the visible one).
@m-col thank you for working on this! And awesome that you found the issue!

**Comment by m-col** [comment]
Please could you update to the latest release of pywlroots (from a few hours ago) and test out the PR?: https://github.com/qtile/qtile/pull/3507

**Comment by arjan-s** [comment]
> Please could you update to the latest release of pywlroots (from a few hours ago) and test out the PR?: #3507

Works like a charm! Thank you!
