### ISSUE TITLE
Wayland: support for output power management protocol

### ISSUE THREAD

**Issue by anriha** [qtile/qtile#3283]
Hello, are there plans to support output power management protocol or anything similar? For me this is currently the main problem with using Qtile as my Wayland WM.

**Comment by m-col** [comment]
I agree that it would be great (well, _essential_) to support it. I have no hard plans to implement it, and I have one or two things I'd like to do first, but then yeah I'm happy to bump it up the to-do list. I've added it there (https://github.com/qtile/qtile/discussions/2409). I'll close this to keep any discussion there. If anybody is interested in working on this then fantastic, otherwise I'll get to it in perhaps a week or two. Handlers will need to be added pywlroots first.
