### ISSUE TITLE
Margin around fullscreened window

### ISSUE THREAD

**Issue by lominoss-git** [qtile/qtile#3328]
When I toggle fullscreen mode using a hotkey, the focused window gets fullscreened as expected but there is tiny margin around it:
![VirtualBox_Framework_11_02_2022_22_20_11](https://user-images.githubusercontent.com/79030093/153678818-4d1076e9-f2b8-479e-a493-f63afd7701de.png)
As you can see, the bar and the wallpaper are visible.

**Comment by m-col** [comment]
What client is that? Does it happen with every window, or perhaps to different extents with different windows? When placing a fullscreen window we respect hints that the window provides that specify what width and height increments it wants. The main example of this is that some terminals want to only have a width and height that is a multiple of the width and height of its text cells, so that there isn't excess space inside the window at the edge. Looking at your image I suspect that's what is happening. You'll also see the same thing if you drag resize the window - if it provides increment hints then resizing will respect those too, and it will grow/shrink in increments rather than smoothly.

**Comment by lominoss-git** [comment]
Yes you're right, when I tried fullscreening Firefox or Thunar this problem didn't occur.

**Comment by jwijenbergh** [comment]
Which terminal is that btw? Maybe we can find a setting for you that makes sure this doesn't happen for that application

**Comment by m-col** [comment]
While this is true, bear in mind that if the window is placed at the full screen dimensions that the margins _inside_ the client are going to be asymmetric. Usually terminals pad the bottom and right margins if there is excess they can't use, so you can imagine the white bar at the bottom of the text editor is not slightly further from the right hand window edge. So it's also not ideal. That said, the best thing a terminal could do is to divide the excess across all four edges -- some of them probably do that.

**Comment by lominoss-git** [comment]
Unfortunately I use Termite not ST, but I completely understand, thank you guys for your time and efforts.
