### ISSUE TITLE
MonadThreeCol has hard coded new_client_position

### ISSUE THREAD

**Issue by elParaguayo** [qtile/qtile#3333]
https://github.com/qtile/qtile/blob/5f6ab4bcafbcb31e45dbd178a77f49eb647505a6/libqtile/layout/xmonad.py#L1073

Posting here to remind me to fix it unless @mbenford gets there first...

**Comment by mbenford** [comment]
Sorry for not replying sooner. GitHub strangely didn't send me a notification. :(

Setting `new_client_position` as `top` was actually intentional because that's how XMonad's ThreeColumns layout works. But I totally agree that in Qtile it can be an option so it's up to users to decide what they want.

I'll work on it.

**Comment by mbenford** [comment]
#3423 was merged and this issue can be closed.
