### ISSUE TITLE
Error caused by screen change hook persists after deletion

### ISSUE THREAD

**Issue by xtalax** [qtile/qtile#3440]
### The issue:

I am getting the following error with [this](https://gist.github.com/xtalax/bd2d1a4237fb2181f436e41467c9f358) config:
```
2022-03-21 19:06:13,176 ERROR libqtile hook.py:fire():L392 Error in hook screen_change
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/hook.py", line 390, in fire
    i(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 359, in cmd_reconfigure_screens
    self._process_screens()
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 340, in _process_screens
    scr._configure(self, i, x, y, w, h, grp, reconfigure_gaps=reconfigure_gaps)
  File "/usr/lib/python3.10/site-packages/libqtile/config.py", line 302, in _configure
    self.set_group(group)
  File "/usr/lib/python3.10/site-packages/libqtile/config.py", line 364, in set_group
    g1 = self.group
AttributeError: 'Screen' object has no attribute 'group'
```

I did have a `screen_change` hook defined previously:
```
@hook.subscribe.screen_change
def set_screens(event):
    subprocess.run(["autorandr", "--change"])
    # lazy.spawn("mydock")
    qtile.restart()

```
The error persists after deleting the `screen_change` hook and reloading the config

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Can I check: are you saying you get the error if you remove that hooked function and start qtile?

**Comment by elParaguayo** [comment]
OK. Next question: are you on v0.20 or the latest git version? We've made a few changes to reconfiguring screens since v0.20 so this issue may be fixed (and no one else seems to have reported this recently either).

Are you able to install the git version?

**Comment by xtalax** [comment]
I've been having trouble with the AUR package for the git version, 
`error: failed retrieving file 'python-pytest-7.0.1-1-any.pkg.tar.zst' from mirrors.celianvdb.fr : The requested URL returned error: 404` etc.

Do you have a link to manual install instructions?

**Comment by elParaguayo** [comment]
That suggests your mirrors are out of date. When did you last do a full update? 

However, pytest is only needed to run the test suite. I'm not sure how you're installing from the AUR but `makepkg` has a `--nocheck` flag which would hopefully prevent those dependencies being installed.

**Comment by xtalax** [comment]
I'm now on v0.21 and the error persists

**Comment by elParaguayo** [comment]
OK. Can you confirm that the issue persists with no hooked function? and what about when running the default config?

**Comment by xtalax** [comment]
The hooked function is not in `~/.config/qtile/config.py`. Default config works.

**Comment by elParaguayo** [comment]
OK. So if the default config works then we need to track down which part of your config is breaking it. 

Can you try disabling your autostart script first (that's the usual candidate).

**Comment by elParaguayo** [comment]
OK - what's in the autostart script?

**Comment by elParaguayo** [comment]
What happens if you disable that hook function?

I don't think you should have to call `cmd_restart` and I could see why that could be problematic.

The default config includes `reconfigure_screens = True` which should be sufficient to set up your screens correctly when there's a change. We should, hopefully, have got rid of the bugs that meant you needed to restart qtile.

**Comment by elParaguayo** [comment]
Thanks for checking.

That's pretty weird behaviour. I'll see if I can test at some point over the weekend.

**Comment by dpiegdon** [comment]
side note:
I reconfigure my screens with a program that first disabled all outputs, then one-by-one adds outputs until all are configured.
that might introduce a race condition as well, as qtile would receive RANDR events multiple times in a very short span, with different configurations. here is one of these:
<pre>
xrandr --output DisplayPort-0 --off --output DisplayPort-1 --off --output DisplayPort-2 --off --output HDMI-A-0 --off
xrandr --output DisplayPort-1 --scale 1x1 --rotate left --pos 0x0 --mode 2560x1440 --primary
xrandr --output HDMI-A-0 --scale 1x1 --rotate normal --pos 1440x0 --mode 2560x1440
xrandr --output DisplayPort-2 --scale 1x1 --rotate left --pos 4000x0 --mode 1920x1080
</pre>

also, i have the same behaviour as mentioned when re-configuring from three-screen setup to the same setup. so after that, there would be only a single qtile-screen spanning all three displays.

this probably is because of the quick, successive calls to xrandr...

**Comment by elParaguayo** [comment]
Ah. Interesting. What happens if you don't use that script, connect an additional monitor and then just add that monitor with `xrandr`? Does it work correctly then?

**Comment by dpiegdon** [comment]
the xrandr configuration is generated by a program and then executed.
when manually merging it into a single `xrandr`-call, it works without error.

**Comment by dpiegdon** [comment]
yes, that also works fine without issues.
however, i will try to rewrite my xrandr-tool to do only a single xrandr-call. seems favourable.
thanks for your help!

if you still want to track down that race-condition, let me know. otherwise this is fine for me now. :)
