### ISSUE TITLE
libqtile.extension.window_list does not switch to the correct window sometimes

### ISSUE THREAD

**Issue by jagguli** [qtile/qtile#3502]
### The issue:

Version 0.19.0

libqtile.extension.window_list does not switch to the correct window sometimes

Scenario: not working
  Given I have multiple windows in a group 
  And I am on the same group as the window
  When I invoke the windowlist extension and select a window 
  Then selected window is not brought to the foreground

Scenario: working
  Given I select the window while I am on a different group
  Then it foregrounds the correct window

  Given I select the window while I am on a different screen 
  Then it foregrounds the correct window

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Thanks for the report.

A few questions/comments:
- What do you mean by `foregrounds`? Are these floating windows and you're selecting one that's underneath another?
- I note you're on v0.19. We're actually on v0.21 now but I can't say if this particular issue is fixed in the latest version.

**Comment by jagguli** [comment]
brings the window to the top.
I'm using max layout, not floating.

Still happening with the latest build from git.

but it seems to happen after a while of using qtile..

**Comment by jagguli** [comment]
I think it might be something to do with when a window changes its title in the background.

I can't seem to pin it 

Does anyone one else use the window list extension?

I'm using a lot of surf windows (20+) but I think it's mostly with browser windows the issue.


Any tips on how to debug this would be helpful too.

**Comment by jagguli** [comment]
It starts working when I switch to a different group and seleect a window in another group

seems like some kind of statefull bug ... the best kind in python ...lol

**Comment by jagguli** [comment]
Yes thats the problem there is no reliable way to replicate it .

I some how endup in a state where the window switcher stops working.

I have around 20 open windows on one group, all works fine then it suddenly stops.

I'll keep postin updates with my observations

**Comment by jagguli** [comment]
I think I have found a solution , just need to check group before focusing windown

https://github.com/jagguli/TAQtile/commit/fc9ddc3940a41a01d869d1a16bff07e38ce91def#diff-7fd554b1f6a365d5c788ba0cbd5fd5afd90cb357e489a433452d706303076a43R79

**Comment by jagguli** [comment]
That did not work still an issue

**Comment by jagguli** [comment]
Captured some logs and inspecting it shows that the selected window is focused then the previous window was refocused

```
2022-04-25 00:42:06,989 INFO libqtile surf.py:run():L100 surf called *  qtile hooks - Google Search

2022-04-25 00:42:06,989 INFO libqtile surf.py:run():L132 surf focusing window Window(name='@cgDISMfxT:T | qt
ile hooks - Google Search', wid=58720259)
2022-04-25 00:42:06,990 DEBUG libqtile hook.py:fire():L381 Internal event: client_focus((Window(name='@cgDIS
MfxT:T | qtile hooks - Google Search', wid=58720259),), {})
2022-04-25 00:42:06,991 DEBUG libqtile hook.py:fire():L381 Internal event: client_focus((Window(name='@cgDIS
MfxT:T | qtile hooks - Google Search', wid=58720259),), {})
2022-04-25 00:42:06,993 DEBUG libqtile hook.py:fire():L381 Internal event: client_focus((Window(name='@cgDIS
MfxT:T | qtile hooks - Google Search', wid=58720259),), {})
2022-04-25 00:42:06,994 DEBUG libqtile hook.py:fire():L381 Internal event: client_focus((Window(name='@cgDIS
MfxT:T | qtile hooks - Google Search', wid=58720259),), {})
2022-04-25 00:42:06,994 DEBUG libqtile hook.py:fire():L381 Internal event: focus_change((), {})
2022-04-25 00:42:06,995 DEBUG libqtile hook.py:fire():L381 Internal event: client_focus((Window(name='@cgDIS
MfxT:T | qtile hooks - Google Search', wid=58720259),), {})
2022-04-25 00:42:06,996 DEBUG libqtile core.py:_xpoll():L301 X11 event: FocusOut (targets: 1)
2022-04-25 00:42:06,996 DEBUG libqtile core.py:_xpoll():L301 X11 event: FocusOut (targets: 1)
2022-04-25 00:42:06,996 DEBUG libqtile core.py:_xpoll():L301 X11 event: PropertyNotify (targets: 2)
2022-04-25 00:42:06,996 DEBUG libqtile hook.py:fire():L381 Internal event: client_name_updated((Window(name=
'@cgDISMfxT:T | Built-in Hooks — Qtile 0.21.1.dev13+gea53111.d20220416 documentation', wid=67108867),), {})
```


Given that I start with window name '@cgDISMfxT:T | Built-in Hooks — Qtile 0.21.1.dev13+gea53111.d20220416 documentation'
When I select window with window name "*  qtile hooks - Google Search"
Then I see client_focus trigger on that window 
But the window is not focused


Still cannot replicate consistently but it happes on multi monitor
and if use the window list on a different screen the it starts working again.

**Comment by jagguli** [comment]
Hi @m-col I need some help with this please, thx.

**Comment by Windore** [comment]
I think I have the same issue but I'm pretty sure how to replicate it. Running version 0.21.0. 

If I try to use WindowList extension to switch to a non-active window on the same currently active group, WindowList fails to focus that window. Therefore my currently active window doesn’t change. Switching to a window on a different screen/group works.

This probably has something to do with the mouse moving focus back to the old window I’m trying to deactivate because if I set `follow_mouse_focus = False` the switching between windows in the same group works as expected. Can you @jagguli confirm if setting `follow_mouse_focus = False` fixes your problem?

**Comment by jagguli** [comment]
@Windore YES ... seems like `follow_mouse_foucs = False` is a workaround for the issue.

I guess this is a lead ? It should work even if `follow_mouse_focus = True`

**Comment by m-col** [comment]
Sorry, this flew under my radar.

> This probably has something to do with the mouse moving focus back to the old window I’m trying to deactivate because if I set follow_mouse_focus = False the switching between windows in the same group works as expected. Can you @jagguli confirm if setting follow_mouse_focus = False fixes your problem?

Great finding. Does the issue only happen when the cursor is above the currently focussed window?

FWIW I cannot reproduce on git master, regardless of follow_mouse_focus setting. Perhaps something has changed since last summer. We had a release since then - is this issue still happening?

**Comment by Windore** [comment]
I didn't manage to reproduce the issue either. The active window changed as expected.

The only thing I noticed was that when switching between floating windows that are on top of each other, the newly active window remains behind the previously active window. I suppose that is the intended behavior since it's the same if changing focus by moving the mouse. It's not at least a part of this issue, and I doubt it's an issue at all.

 This issue can probably be considered as fixed.

**Comment by jagguli** [comment]
not happening anymore closing .. thanks :pray:
