### ISSUE TITLE
Qtile has the wrong index for the monitor.

### ISSUE THREAD

**Issue by misumisumi** [qtile/qtile#3708]
### The issue:

I wanted to get monitor index same as result of `xrandr --listmonitors`, but qtile missmatch with it.

First is log of using my func of cycleing monitor using screen index.
Second is result of `xrandr --listmonitors'
Qtile reported monitor0(DP-0, primary, WQHD)->monitor1(DVI-D-0, FHD)->monitor2(HDMI-0, WQHD) but xrandr reported DP-0->HDMI-0->DVI-D-0.
I use display config generated by nvidia-setting. (Third is)
![image](https://user-images.githubusercontent.com/24451978/179156240-df22da9f-808a-4d96-b18c-17077be71d79.png)
![image](https://user-images.githubusercontent.com/24451978/179142499-15c1dd8e-1115-41c5-aaf2-b183dd693bfe.png)
![image](https://user-images.githubusercontent.com/24451978/179146061-ed87f01c-3edf-4519-b74d-192e3c18e70a.png)

* Qtile version: 0.21.1
* distro: ArchLinux
* I make screen using my func but this is almost identical to the example.
  ![image](https://user-images.githubusercontent.com/24451978/179146346-4816c0e5-0e42-4011-ad0b-a3b935084282.png)

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by Sumi-Sumi** [comment]
I believe this problem is caused by xinerama reporting the queries from xinerama in a different order than xrandr --listmonitor in the initialization of the physical monitor.
A simple check was made on the code where the physical monitor is actually initialized.
The finalized codes and results can be found here. (libqtile/backend/x11/xcbq.py, Line[533:544])
First we obtained the information from xinerama and then from randr.
![image](https://user-images.githubusercontent.com/24451978/179193926-927b17a8-0ade-493f-b466-0eed23935822.png)
![image](https://user-images.githubusercontent.com/24451978/179193971-e410050d-c0bc-4455-9501-99049d8fd4c6.png)
I don't know why it is retrieved from xinerama since xorg is configured not to use xinerama.

**Comment by elParaguayo** [comment]
Looking at this method:
https://github.com/qtile/qtile/blob/6620786f801f56fc61716514139044108eaef743/libqtile/backend/x11/xcbq.py#L407-L418

We could check the `mode` property of the individual screens and only add it if it's active.

According to the [spec](https://www.x.org/releases/X11R7.5/doc/randrproto/randrproto.txt):
```
'mode' indicates which mode is active, or None indicating that the CRTC has been disabled
and is not displaying the screen contents.
```
I think, in `xcffib`, the mode is actually `0` rather than `None`. Are you able to test?

**Comment by Sumi-Sumi** [comment]
OK. I will test it.
I will be away from the environment with the problematic PC for a little while, so my reply will be delayed.

**Comment by husjon** [comment]
I'm also experiencing this issue.
I'm looking to try out qtile, coming from bspwm (used for the last 3-4 years).

In my example
xrandr lists my monitor:
```
Monitors: 3
 0: +*DP-4 2560/598x1440/336+0+0  DP-4
 1: +DP-2 2560/598x1440/336+2560+0  DP-2
 2: +HDMI-0 1920/256x1080/144+5120+0  HDMI-0
```
while qtile swaps DP-2 and HDMI-0.

I find it strange that qtile uses monitor index from randr / xrandr instead of using monitor name (which are unique).

**Comment by Sumi-Sumi** [comment]
Sorry for the time delay in replying since the last time.
I checked mode of `xcffib`.
You are right, the mode was 0.
The fourth one is the output for the VM.
![image](https://user-images.githubusercontent.com/24451978/192144994-8acce7af-1732-4fe1-8aa6-4f2cfce46b30.png)
