### ISSUE TITLE
Mirror widget does not get events: mouse_entered/mouse_leave

### ISSUE THREAD

**Issue by btwe** [qtile/qtile#3806]
### The issue:

```
% qtile --version
0.21.0
```
I noticed that the mirrored widget does not trigger the mouse_enter/mouse_leave callbacks. They only work on one screen.

I think this is a bug.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Interesting.

I agree that those events are not handled by a mirror at the moment. I would, however, question whether they _should_ be.

Mirroring is really to do just that, reflect the contents of a widget. Anything that relies on the mouse position could result in some  unexpected behaviour. I'm not sure what your particular issue is but, if you're using mouse_enter/leave events, I'd be inclined to have separate instances of the widget, rather than using mirrors.

I could be convinced otherwise but I'd need more details about your specific situation.

**Comment by btwe** [comment]
In contrast mouse button events are processed  (I have not checked for the key events though).

I use it [here](https://gitlab.com/btwe/pomodorotimer) (still developing though, I plan to send a MR into qtile later). The functionality I was thinking to achieve is:
- mouse enters the widget: popup pops up
- mouse leaves: popup closes (after a delay)
This works so far, but not on the mirrored widget. But anyways, I would not prefer to have two separate widgets, because they should show the same content on each screen.

Does this make sense?

**Comment by elParaguayo** [comment]
Sure. It's easy enough to pass through the events. I'll submit a PR later (unless you want to do it...)

**Comment by btwe** [comment]
I 'll add to my todo list, so you do not have to worry about it any further. You'll find a MR then

Thanks!

**Comment by elParaguayo** [comment]
Actually, don't worry. I've got an open PR with some improvements to Mirrors so I'll add this to that.

**Comment by btwe** [comment]
Wonderful! Thanks a lot :)
Do you close this?

**Comment by elParaguayo** [comment]
It will close automatically when that PR is merged.
