### ISSUE TITLE
widget.Net overestimates download and upload speed by a factor ~3

### ISSUE THREAD

**Issue by Crystal4276** [qtile/qtile#3997]
### The issue:

widget.Net overestimates download and upload speed by a factor ~3

I realize that when is saw download speed value around 28-30 MB/s while my uni connection is limited to 10-11MB/s.
Looking at Deluge vs  widget.Net speed values, i can see this factor ~3 difference consistently.

```python
            widget.Net(
                       padding = 15,
                       foreground = colors[16],
                       background=colors[1],
                       fontsize = 22,
                       prefix ='M',
                       use_bits=False,
                       format="{down} {up}",
                       update_interval=2,
                       **decor_clock,
                       ),
```

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Not sure there's much in the widget to help here. It checks the number of bytes received between updates and divides that by the interval. The division uses the interval as defined in your config rather than the actual elapsed interval but I can't see how that would lead the magnitude of difference that you're seeing.

You could try setting the `interface` parameter and limiting this to a single interface but, again, I'd be surprised if that made the difference.

**Comment by Crystal4276** [comment]
> You could try setting the `interface` parameter and limiting this to a single interface but, again, I'd be surprised if that made the difference.

Specifying the interface to my NIC solved the bug.

In my network, configuration i have :
- a NIC
- a bridge with a port that NIC
- a vpn connection.

It could be that widget.Net is summing those three connection when the interface is not explicit?

**Comment by elParaguayo** [comment]
Yes, that's what happens. When no interface is specified, all interfaces are summed.

Sounds like we can close this then?

**Comment by Crystal4276** [comment]
Well, the only real interface is the NIC.
The others two are connections, i won't call them interfaces.
There's the possibility of pointing to an interface, so that's good enough workaround for me :)
