### ISSUE TITLE
OpenWeather: text is slightly off center

### ISSUE THREAD

**Issue by mrtnvgr** [qtile/qtile#4062]
### The issue:

![](https://i.imgur.com/fPB4Yy5.png)

My setup:
```
widget.OpenWeather(cityid='XXXXXXX', format='Weather: {main_temp}°{units_temperature} {icon}', foreground=foreground),
```

qtile --version:
```
qtile-0.22.2.dev83+ga4adb667
```

### Required:

- [x] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Interesting. That widget doesn't do anything special in terms of layout so I'm guessing it's an issue with the content.

What happens if you remove the icon?

**Comment by mrtnvgr** [comment]
I'm using a [Caskaydia Cove Nerd Font](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/CascadiaCode).

**Comment by elParaguayo** [comment]
OK. So the issue here is that the icons in that font are a different size to the other characters.

The widget positions text vertically by centering the text layout in the bar.  Those icons must have some extra space beneath them which is increasing the height of the text layout.

Do you get the same issue with other fonts?

**Comment by mrtnvgr** [comment]
> Do you get the same issue with other fonts?

No.

**Comment by mrtnvgr** [comment]
The icon has changed and the issue disappeared.

![](https://i.imgur.com/O7sR33t.png)

**Comment by mrtnvgr** [comment]
> Do you get the same issue with other fonts?

Yes, I tried "Liberation Mono", "Bitstream Vera Sans Mono".

**Comment by elParaguayo** [comment]
Unfortunately, this is really a font issue (particularly if the issue disappears with different icons).

A hacky way to fix this would be to check if there's an icon and, if there is, calculate the height of the text layout based on the same text _excluding_ the icon and position the text based on that height.

**Comment by mrtnvgr** [comment]
> Unfortunately, this is really a font issue (particularly if the issue disappears with different icons).

If this is a font issue, I will open a new issue in [nerd fonts](https://github.com/ryanoasis/nerd-fonts) repo mentioning this later.

**Comment by mrtnvgr** [comment]
I guess I can set this issue as completed for now?

**Comment by elParaguayo** [comment]
Would be great if you can check with them. There's clearly something different about some of those icons so I'd be interested in what they say.

We can leave this open until you have a response from them.

**Comment by Finii** [comment]
> So the issue here is that the icons in that font are a different size to the other characters.

I guess if that is NOT desired one would need to use `Caskaydia Cove Nerd Font Mono` instead (where the symbols are scaled to fulfill the 'monospaced' promise).

Here is an article about the scaling, but it is more interested in horizontal scaling: https://github.com/ryanoasis/nerd-fonts/discussions/969

**Comment by Finii** [comment]
Ah, now I notice that only the weather section is shifted up:

![image](https://user-images.githubusercontent.com/16012374/207429890-1afae245-ebab-48a9-8307-5fb4e823b3e9.png)

What comes to my mind additionally, there was some weather service thing, that had an Issue over ad Nerd Font, with icons not matching. After investigation it turned out that the icon/symbol in question is not part of the Nerd Font patch-set and was automatically pulled in via font-fallback from some other font, and then of course not centered / scaled at all.
Afterwards they switched to other codepoints for some queries.

It would be crucial to determine the codepoint of the sun-and-cloud thing to check that.
Ah, found it: https://github.com/ryanoasis/nerd-fonts/issues/543

**Comment by elParaguayo** [comment]
Can we close this then? It doesn't seem to be a qtile issue.
