### ISSUE TITLE
Get Mpd2 widget fixed width

### ISSUE THREAD

**Issue by K1ngst0m** [qtile/qtile#4101]
### The issue:

- qtile version: 0.22.1

Mpd2 widget has only the width attribute to control the maximize widget width, it won't always get the same width when the different lengths of song/artist names are.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Sorry, I'm not entirely sure what behaviour you're after. Setting `width` should fix the width of the widget. Not setting it would mean the width is calculated based on the content. Is there a third option you want?

**Comment by K1ngst0m** [comment]
sorry to have failed to make myself clear. 
e.g this's my widget setup:
```python
                widget.Mpd2(
                    foreground='#ffffff',
                    background='#1f1f1f',
                    status_format='{play_status} {artist} - {title}',
                    idle_format='{play_status} {idle_message}',
                    idle_message='wait for playing....    ',
                    width=300,
                    padding=10,
                    scroll=True,
                    # font= 'JetBrains Mono Bold',
                ),

```

when the songs name is shorter than 300, the bar will shrink
![image](https://user-images.githubusercontent.com/34272057/210327393-ccf31b43-300f-4ab7-9062-65b7cef9bbc5.png)

for the song that has a long name, the bar will maximize to 300 widths.
![image](https://user-images.githubusercontent.com/34272057/210327653-9dc63de5-8599-4ae4-a0df-d7cc9445f907.png)

looks like the `width` attribute only controls the maximum width of a widget. but the additional minimum width control or a permanently fixed width is always for need.

**Comment by elParaguayo** [comment]
If you disable scrolling, do you get the fixed size?

**Comment by K1ngst0m** [comment]
Yes, but can we get the fixed size when enabling scrolling?

**Comment by elParaguayo** [comment]
When scrolling is enabled, the `width` value is interpreted as the maximum value. Where text is shorter than this, it reverts to calculating the width of the widget based on the size of the content.

We did originally think about having a separate `scroll_width` parameter which was to deal with this particular issue.

The simplest fix would be to always have a fixed with when using scrolling but that would change behaviour for existing users. If we don't do that then I think we need to add a new parameter (something like `scroll_fix_width=True`) to do this.

@m-col you and I discussed this before so curious if you have a preference here (or a simpler fix that I may have missed).

**Comment by m-col** [comment]
I think you got it all, both setups seem like they would be desirable so +1 for a simple bool like `scroll_fix_width` as you suggest

**Comment by elParaguayo** [comment]
OK. Will add this later.

**Comment by K1ngst0m** [comment]
much appreciated!
