### ISSUE TITLE
Document qtile migrate in script itself

### ISSUE THREAD

**Issue by jgarte** [qtile/qtile#4236]
### The issue:

The migrate script [code](https://github.com/qtile/qtile/blob/master/libqtile/scripts/migrate.py) does not mention anything about what that script is for.

Would a PR be accepted to add a module level docstring to it using the information that I found here?

https://docs.qtile.org/en/stable/manual/contributing.html?highlight=bowler#submit-a-pull-request

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Not sure what the other devs think but I don't love the `migrate` script.

I think the intention is good as it can make sure configs are updated for changes. However, I'm not convinced that the script catches all the things it's supposed do and there's a risk it could catch things it shouldn't.

It's also not updated for every breaking change/deprecation we make.

**Comment by ramnes** [comment]
As someone that just returned to my Qtile config after a long break, I love this script and think that we should enforce a migration for every PR labeled "breaking-change"

**Comment by elParaguayo** [comment]
Fair enough. There are a few points that would need to be sorted out then:
- Do we stick with `bowler` for this? My understanding is that it's not compatible with certain, newer parts of python syntax.
- Do we have some way to track which migrations are needed rather than having an ever-growing script. This significantly slows down tests but also, if a user is running this regularly, they're not going to want every migration run every time.

**Comment by tych0** [comment]
My view is: if we're not going to maintain/enforce it, we should delete it. Having it half-working is much worse than not working. Of course it is annoying for developers, but it is even more annoying for users to have to read release notes and file bugs when things change. I guess the question is simply: who should be annoyed :)

**Comment by elParaguayo** [comment]
My personal feeling is that the migrate script is not worth the effort.

However, we could (and should) provide clearer documentation on breaking changes/deprecations i.e. rather than just a not in the changelog, we can show examples of what needs to be changed. That would allow users to make the relevant changes to the configs themselves and understand the changes.

**Comment by ramnes** [comment]
Actually people filing bugs when we push breaking changes was so annoying for us developers that we ended up writing a script...

**Comment by elParaguayo** [comment]
This is what I was thinking we could do for breaking chages:
![20230611_114257](https://github.com/qtile/qtile/assets/946265/11bf5021-0fc7-4fbf-8192-685891119635)

**Comment by elParaguayo** [comment]
@ramnes does this idea work for you? I'm happy to draft the docs but only if we think it's worth it.

**Comment by elParaguayo** [comment]
The problem I'm trying to solve is that I don't like the `migrate` script. I have nothing against it conceptually but my concerns are as follows:
1) It's not easy to write migrations (although that would get easier over time)
2) I'm not convinced that it's 100% safe (we may miss conversions or convert things that shouldn't have been converted)
3) The user doesn't necessarily understand what's being changed and why. Even if the script were to output a diff, I'm not sure everyone would follow it.

The docs solution would tell people what's changed, what error messages to expect and how they can fix their own configs. It's more effort on their part but they'll have a better understanding of where they need to make changes and how to do it.

**Comment by ramnes** [comment]
I don't want to block you if you're willing to put work into this, and I'm not going to fight for `qtile migrate` anyway. I believe it's a far superior solution if 1. we're enforcing it on PR that are willing to introduce breaking changes 2. we document what `qtile migrate` does and when / how to use it, as mentioned by OP. But at the end of the day the most important is that someone takes the responsibility on how we handle breaking changes and I'm really not active enough on Qtile these days to assume anything to that regard, so I'll be happy to disagree but still commit if you want to go that route. :)

**Comment by elParaguayo** [comment]
An alternative approach...

If we stick with the migrate script, we need to make more user friendly. We could do this by decorating migrations with something like:
``` python
@migrate_info(
    id=1,
    version="0.24.0",
    summary="Drop 'cmd_' prefix for exposed commands.",
    help="""The 'cmd_' prefix has been deprecated. Calls to these commands
    should be renamed in your scripts.
    
    e.g. qtile.cmd_spawn("vlc") should be changed to qtile.spawn("vlc").
    """,
)
def drop_cmd_prefix(query):
    ...
```

Users can then list migrations with the version number and summary (e.q. `qtile migrate --list-migrations`), get more info on specific migrations (`qtile migrate --help 1`) and run migrations for a specific version (`qtile migrate --update 0.24.0`).

**Comment by elParaguayo** [comment]
Playing around with `LibCST` a bit. It seems very promising.

To make a quick rule to change `cmd_func` calls to `func`, we just need something like this:
``` python
class ReplaceCmdPrefix(m.MatcherDecoratableTransformer):
    @m.call_if_inside(m.Call())
    @m.leave(m.Name(m.MatchIfTrue(lambda f: f.startswith("cmd_"))))
    def change_func_call_name(self, original_node, updated_node) -> cst.Name:
        return updated_node.with_changes(value=original_node.value[4:])
```

It's also easy enough to update a config where a user has defined a custom class with a method using the `cmd_` prefix to remove the prefix, add the `@expose_command` decorator and add the `import` line if it's missing.

I'd feel far more confident that `LibCST` can address points 1 and 2 in my list and we can easily arrange for the migrate script to provide more info to address #3.

I'm happy to play with this a bit and see what I can come up with.

**Comment by m-col** [comment]
LibCST looks pretty good, and if you're happy with it over bowler than +1 from me. In general I agree with all of the above... I'd be cautious about dropping `qtile migrate` because we end up in the issue we had originally, so ideally we'd have a fully functioning, easy to use, documented migration tool, that we actively maintain. Obviously given the rate of issues/questions we're always pretty inundated but if LibCST is a promising alternative way to maintain migrations then that's awesome and maybe we can commit to trying that out for a while, maybe it'll be a learning process :)

That said, qtile has lots of bugs and (configuration) inconsistencies, and I think the end game after most of these are fixed would be using proper semantic versioning, then we can drop `qtile migrate` and limit API breakges to major version bumps... but maybe that's idealistic.

**Comment by elParaguayo** [comment]
I'm glad you're in favour as I've done a lot of work to rework this with libcst! Trying to set up a framework that makes it really easy to write migrations and tests (all handled in a single file).
