### ISSUE TITLE
switching focus does the key input in new window

### ISSUE THREAD

**Issue by tokisuno** [qtile/qtile#4303]
Qtile version: 0.22.1
Arch Linux Kernel 6.3.7
### The issue:

i tried to search up what i was looking for, but i can't work it properly so i'll try to do it here.

whenever i go from firefox to alacritty with a vim buffer open, alacritty listens to the input that i do when i focus into it (mod1 + L) and gives me the vim output for doing alt+L. is there any way to avoid this happening? 

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by jwijenbergh** [comment]
wayland or x11?

**Comment by tokisuno** [comment]
X11. The issue literally solved itself. I have no idea what it was, or how to replicate it now. All I remember was it was on alacritty on a fresh installation. Sorry chief.

**Comment by anymuster2** [comment]
I have this issue, it started approximately 8-12 months ago but I was unable to figure out reliable steps to reproduce, apologies for the following instructions:

- Set `follow_mouse_focus = False`, aside from that the config I am using is entirely default
- Install BurpSuite Community Edition, https://portswigger.net/burp/communitydownload
- Open BurpSuite (it is in path pointing to `/usr/local/bin/BurpSuiteCommunity` at the top of the display there is a tab called 'Repeater', within the main panel, click the 'X' to show the request/response input fields
- Open Firefox
- Open a third window (this is my current workaround)
- In firefox, I click the address bar, type 'aaaa'
- In BurpSuite, I click the 'request' area and type 'bbbb'
- In firefox, I cilck the address bar and type 'cccc' - the 'cccc' is inputted into burpsuite, despite firefox having focus
- If I reproduce the same steps, but after typing 'bbbb', I click the terminal, and then click the firefox address bar, it works fine. Focus seems to work fine with the terminal (e.g., if instead of Firefox I reproduce with the terminal). I am able to reproduce if I use a HTML text input in firefox (it is not specific to the the address bar).

BurpSuite is (from my understanding) a Java/SWING application. I have no idea if this is relevant but I have not seen the issue manifest elsewhere.

Tested Ubuntu 23.04 using Qtile git master (and previous versions) using X11. As I said above, this issue appears to have been introduced in the last 8-12 months (maybe a bit earlier, idk), I'm unsure if this is a Qtile bug or an underlying lib, but either way the issue does not seem to be widespread to other Window Managers.

**Comment by tokisuno** [comment]
oh interesting..

**Comment by jwijenbergh** [comment]
Let's close this one and track the other in #4372
