### ISSUE TITLE
`pip install qtile` in a fresh environment fails

### ISSUE THREAD

**Issue by 3301n** [qtile/qtile#4346]
### The issue:

I wanted to install qtile using the command pip install qtile, but it showed a lot of error messages, and I expected it do a clean install . I think this is a bug. I am not in root but as a user installation. 
I am using python version 3.11.4 and pip version 23.2 in a debian based operating system.
![Screenshot_2023-07-18_04_55_55](https://github.com/qtile/qtile/assets/69240615/df85225d-5081-490c-935b-b641daeaaa32)

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
What version of `cairocffi` and `xcffib` do you have installed?

**Comment by elParaguayo** [comment]
(separately, what window manager are you using in that screenshot?)

**Comment by ramnes** [comment]
This is what happens when you try to run `pip install qtile` in a fresh environment:

```
$ virtualenv .venv
created virtual environment CPython3.11.4.final.0-64 in 824ms
  creator CPython3Posix(dest=/home/ramnes/tmp2/.venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/ramnes/.local/share/virtualenv)
    added seed packages: pip==23.1.2, setuptools==68.0.0, wheel==0.40.0
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
$ source .venv/bin/activate
(.venv) $ pip install qtile
Collecting qtile
  Downloading qtile-0.22.1.tar.gz (488 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 489.0/489.0 kB 3.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [41 lines of output]
      Failed to find pywlroots. Wayland backend libinput configuration will be unavailable.
      Traceback (most recent call last):
        File "/home/ramnes/tmp2/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/ramnes/tmp2/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/ramnes/tmp2/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-wrey3wwj/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 380, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-wrey3wwj/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-wrey3wwj/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 102, in <module>
        File "/tmp/pip-build-env-wrey3wwj/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-wrey3wwj/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
                                       ^^^^^^^^^^^^
        File "/tmp/pip-build-env-wrey3wwj/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 486, in __init__
          _Distribution.__init__(
        File "/tmp/pip-build-env-wrey3wwj/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
          self.finalize_options()
        File "/tmp/pip-build-env-wrey3wwj/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 925, in finalize_options
          ep(self)
        File "/tmp/pip-build-env-wrey3wwj/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 945, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "/tmp/pip-build-env-wrey3wwj/normal/lib/python3.11/site-packages/cffi/setuptools_ext.py", line 219, in cffi_modules
          add_cffi_module(dist, cffi_module)
        File "/tmp/pip-build-env-wrey3wwj/normal/lib/python3.11/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
          execfile(build_file_name, mod_vars)
        File "/tmp/pip-build-env-wrey3wwj/normal/lib/python3.11/site-packages/cffi/setuptools_ext.py", line 25, in execfile
          exec(code, glob, glob)
        File "libqtile/pango_ffi_build.py", line 24, in <module>
          from cairocffi.ffi_build import ffi as cairocffi_ffi
      ModuleNotFoundError: No module named 'cairocffi.ffi_build'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

@elParaguayo It happens because we're installing an older Qtile version with the newer cairocffi and xcffib. 0.22.1 doesn't put a version limit for cairocffi and xcffib, and we did not release yet the CFFI-related changes. This is why I tried to release the other day but got hit by the release process being broken (resulting in #4307) 

@3301n In the meantime, you can either force older version of xcffib and cairocffi, or install the git version of Qtile (e.g. `pip install git+https://github.com/qtile/qtile.git` (recommended).

**Comment by ramnes** [comment]
Pinning this one in place of #4290

**Comment by elParaguayo** [comment]
Thanks @ramnes I assumed it was the version issue.

We really need to release 0.23.0 soon (we're getting closer...)

**Comment by stevenre3d** [comment]
Up until a few months ago, I was cloning from the git repo and using `pip install .` for my qtile install. Then I started running into these cairocffi version build issues. I found I was able to instead install from the aur (on manjaro, so `pamac install qtile-git`) and that worked. Recently I updated my aur packages, and now building `qtile-git` fails with  

```
Cloning into 'qtile'...
done.
==> Starting pkgver()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
* Getting build dependencies for wheel...
Built with support for XWayland helpers.

ERROR Missing dependencies:
	cairocffi[xcb]>=1.6.0
==> ERROR: A failure occurred in build().
    Aborting...
```

I was at a loss. I removed `qtile-git` and as many cairo and python-cairo packages I could (without removing large important packages that are dependent), and tried again. No luck.

So I tried installing directly from git again. Pulled latest, ran `pip install .` and now (for whatever reason) `pip` spews out a refusal to install anything because my packages are managed externally. That's probably a good thing, I guess that came with some other python updates to my distro. But it included a line about using a `venv` to install packages if I need to. I ran `python -m venv temp` in the qtile root. Then ran `./temp/bin/pip install .`. This successfully pulled the correct packages, built, and installed qtile to this venv directory without any errors.

Then, just to see if it would work, I created a `qtile.desktop` file in `/usr/share/xsessions`:

```
[Desktop Entry]
Name=Qtile
Comment=Qtile Session
Exec=/path/to/qtile/temp/bin/qtile start
Type=Application
Keywords=wm;tiling
```

Then I logged out. An entry existed for qtile in LightDM, so I logged in, and everything is currently working for me. I'm on `Qtile 0.22.2.dev215+g142dc80a` no problem.

This is obviously not a permanent fix, but I'm hoping it's a datapoint that might help someone figure out what might be going wrong, or at least how to also work around it until it is solved. It would seem there's something messed up with my system's python environment that botches a qtile install, but when I do it in a fresh `venv` everything works fine. I don't know enough about package managers to know what's going wrong.

**Comment by ervinpopescu** [comment]
If you run `./temp/bin/pip list |  | grep -E "cairocffi|xcffib"`, you can see the versions `qtile` currently supports. Also see the [CHANGELOG](https://github.com/qtile/qtile/blob/master/CHANGELOG#L3-L4). AFAIK, these packages are outdated in the AUR (gotta check because I haven't in a while).

**Comment by cr1ogen** [comment]
I have the same problem but with the last dev version from qtile.
The Installing with `pip install git+https://github.com/qtile/qtile@master` workarround from #4290 issue work for me

**Comment by clotodex** [comment]
Python screws up the symlinking on some systems, see https://github.com/qtile/qtile/issues/3756. Maybe that is related to your wayland not working.
I have built a standalone install script that builds and patches everything in a virtual env for reproducability.  https://github.com/clotodex/qtile-install-script. Have a look at what allpatch.sh does to see if your libs are linked correctly in your python site-dir.

**Comment by cr1ogen** [comment]
> Have a look at what allpatch.sh does to see if your libs are linked correctly in your python site-dir.

I have downloaded and run the script, but when i run `dbus-run-session /home/cr1ogen/.local/bin/qtile` give me `dbus-run-session: failed to exec '/home/cr1ogen/.local/bin/qtile': No such file or directory`


`ls /home/cr1ogen/.local/bin/qtile
lrwxrwxrwx 60 cr1ogen 13 ago 21:12  /home/cr1ogen/.local/bin/qtile -> /home/cr1ogen/Git/qtile-install-script/build/.venv/bin/qtile`

**Comment by clotodex** [comment]
Hm that is very weird. I assume you checked that the paths exist? You can also directly use the symlink target to try it out: `dbus-run-session /home/cr1ogen/Git/qtile-install-script/build/.venv/bin/qtile start -b wayland`, otherwise drop the dbus-run-session for now and just see if it runs. Finally I could imagine dbus-run-session treating paths internally different, so if ~/.local/bin is in your path you can let the system resolve it with `dbus-run-session qtile start -b wayland`
Please let me know how it goes and otherwise create an issue https://github.com/clotodex/qtile-install-script/issues/new/choose and i will investigate there to not spam this issue here.

**Comment by cr1ogen** [comment]
> Hm that is very weird. I assume you checked that the paths exist? You can also directly use the symlink target to try it out: `dbus-run-session /home/cr1ogen/Git/qtile-install-script/build/.venv/bin/qtile start -b wayland`, otherwise drop the dbus-run-session for now and just see if it runs. Finally I could imagine dbus-run-session treating paths internally different, so if ~/.local/bin is in your path you can let the system resolve it with `dbus-run-session qtile start -b wayland`
> Please let me know how it goes and otherwise create an issue https://github.com/clotodex/qtile-install-script/issues/new/choose and i will investigate there to not spam this issue here.

The path exist `ls /home/cr1ogen/.local/bin/qtile lrwxrwxrwx 60 cr1ogen 13 ago 21:12  /home/cr1ogen/.local/bin/qtile -> /home/cr1ogen/Git/qtile-install-script/build/.venv/bin/qtile` then I gone try to run it, I'm not in home

**Comment by cr1ogen** [comment]
> > Hm that is very weird. I assume you checked that the paths exist? You can also directly use the symlink target to try it out: `dbus-run-session /home/cr1ogen/Git/qtile-install-script/build/.venv/bin/qtile start -b wayland`, otherwise drop the dbus-run-session for now and just see if it runs. Finally I could imagine dbus-run-session treating paths internally different, so if ~/.local/bin is in your path you can let the system resolve it with `dbus-run-session qtile start -b wayland`
> > Please let me know how it goes and otherwise create an issue https://github.com/clotodex/qtile-install-script/issues/new/choose and i will investigate there to not spam this issue here.
> 
> The path exist `ls /home/cr1ogen/.local/bin/qtile lrwxrwxrwx 60 cr1ogen 13 ago 21:12  /home/cr1ogen/.local/bin/qtile -> /home/cr1ogen/Git/qtile-install-script/build/.venv/bin/qtile` then I go to try run it, I'm not in home

``dbus-run-session qtile start -b wayland`` It works but I must have a problem related to debian wlroots because I get this error  #4382. Thank you so much anyway

**Comment by evofromko** [comment]
This bug is still here .
Im running FreeBSD 13.2 and trying to run Qtile inside venv. 
After many searches , deleting, reinstalling xcffib, cairocffi - im still not able to run Qtile as No  "cairocffi" found.
Tried few versions oc cairocffi , xcffib - no luck.
I aquired qtile trough  " git clone " command  earlier today.

**Comment by marcinkosztolowicz** [comment]
@evofromko 
I have struggled with installation of qtile (version 0.22.1) on fresh Ubunut 22.04. I tried many things along the way, so I could miss something important but those versions of python packages worked for me:
`
cffi == 1.15.1
xcffib == 1.3.0
dbus-next == 0.2.3
cairocffi == 1.4.0
pywlroots==0.15.24
`

**Comment by elParaguayo** [comment]
Latest qtile has different requirements for cairocffi and xcffib compared to 0.22.1.

The issue now is that pip builds/installs packages slightly differently and we're having some battles getting it to work with qtile.

**Comment by anthonyma94** [comment]
So what's the verdict currently? Installing qtile isn't possible? I tried `pip install git+https://github.com/qtile/qtile@master`, but can't seem to find the binary anywhere. The output says `Successfully installed UNKNOWN-0.23.0b2.post9+git.fd93e74c`.

**Comment by m-col** [comment]
Could you try again with the new release 0.23.0 and see if it persists?

**Comment by cr1ogen** [comment]
> Could you try again with the new release 0.23.0 and see if it persists?

Qtile 0.23.0 is installed for me, but it still gives me the error in issue #4325
