### ISSUE TITLE
Logging defaults to hiding errors

### ISSUE THREAD

**Issue by smurfix** [qtile/qtile#4464]
### Issue description

My qtile setup crashed, without telling me why.

`bin/qtile start` writes to the default log, which is somewhere off in `~/.local/share` which frankly is no sane place for a log file.

IMHO logging should by default go to standard error.

### Version

dev

### Backend

X11 (default), Wayland (experimental)

### Config

```python
(default config)
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
`qtile start` has a `-p` option to allow you to set a different path. I haven't tried it but you could try `qtile start -p /proc/self/fd/2` to write to stderror.

**Comment by m-col** [comment]
or maybe `qtile start -p /dev/stderr`?

**Comment by ramnes** [comment]
Well it's documented in pretty much every internet documentation related to Qtile that the logs are in `.local/share/qtile/`. As to use stderr as the default for all the logs, we're definitely not going to do that since all logs aren't errors.

Eventually we could default to stdout or stderr based on the log type, and ask users to use `-p` or a shell redirection if they'd want that in a file. In fact that's probably how I'd do it if I were to rewrite Qtile from scratch. :)

But realistically `~/.local/share/qtile/qtile.log` has been there for a very long time and I don't think that's worth the effort to get everyone to migrate, especially since we already have `-p` that exists if you're unhappy with `~/.local/share`.

Feel free to submit a PR if you really want to tackle this by changing the default and assuming the likely massive flow of issues that are going to be opened due to this, but we (maintainers) have limited time and more important matters.

Feel free to comment OP or anyone if you think there's more to add.
