### ISSUE TITLE
Systray still has issues (Implement xembed properly?)

### ISSUE THREAD

**Issue by dequis** [qtile/qtile#465]
Since we don't seem to have a bug for this, and we keep talking about it like it's a known issue...

Most common issue i'm seeing recently is the systray icon getting relocated to the top-left corner of the bar, or completely random locations. Applications that have this issue:
- Hipchat (qt5) - always
- Synergy (qt5) - always
- Steam (???) - sometimes
- utorrent (wine) - sometimes - a "wine system tray" window can be seen during restart, interesting behavior.

Other issues:
- bitcoin-qt (qt4) - very rarely: doesn't go to the top-left corner, just disappears sometimes and gets replaced by the steam icon.
- uim-toolbar-gtk3-systray (gtk3) - okay, but unlike the gtk2 version, the background seems to get stuck
- amsn (tcl/tk) - disappears after the first qtile restart. Started with a black background, turned it transparent somehow.

Applications that seem to be okay:
- Parcellite (gtk2)
- scim (gtk2)
- VLC (qt4)
- uim-toolbar-gtk-systray (gtk2)

Note that all the applications listed above (except uim-toolbar-gtk-systray) may have a black background sometimes (race condition on startup?)

**Comment by LoganKaser** [comment]
I use this to fix the startup placement bug:
```
@hook.subscribe.startup_once
def autostart():

	path = os.path.dirname(os.path.abspath(__file__))
	subprocess.call(['bash', path + '/startup.sh'])
	subprocess.Popen(['xsetroot', '-cursor_name', 'left_ptr'])
	time.sleep(0.3) #wait for applets to start
	lazy.group['Ω'].toscreen() #switch groups to force redraw
	time.sleep(0.3)
	lazy.group['λ'].toscreen()
```
I have noticed this issue on nm-applet, deluge, vattery and a possibly unrelated bug where the Dropbox icon has a white border (It also starts at the upper left corner like the others). I know two other people who use Qtile and all have experienced this bug.
I'd take a look at it myself but I doubt I'd be able to fix it, judging by the age of the issue.
It really adds to the image that Qtile is buggy since it is so visible, hope someone figures it out soon.

**Comment by flacjacket** [comment]
With #697 merged, I've marked this closed since it implements xembed, if there proves to be any problems with the systray we can re-open this

**Comment by LoganKaser** [comment]
I'm still getting some of icons appearing in the top left corner of the bar,
And staying there until the bar updates or the icon is clicked (which I assume also updates the bar)

Background color seems to be fixed with the exception  of dropbox but that is 
clearly a dropbox issue some other taskbars have dropbox specific fixes but I
personally think that it should be left to them to fix.

I'm running the python 3 git version from the AUR.

**Comment by dequis** [comment]
@LoganKaser Other than dropbox, what other apps have issues?

**Comment by LoganKaser** [comment]
@dequis

vattery 0.7.5, networkmanager-applet 1.0.4, deluge, bomi player

Which is everything I have in my tray I have a script that hides and then shows tha bar which fixes the start up issue of being in the upperleft (mostly) but anything start without hiding an showing the bar will sometimes do that.
Also icons still sometimes have corrupted black or all black backgrounds this happens either randomly
when interected with or reliablity when qtile is restarted with a key

![screen](https://cloud.githubusercontent.com/assets/7916909/9183939/195c3c98-3f67-11e5-8100-8f261b0f5711.png)

**Comment by ramnes** [comment]
I used to have this bug very often (and I used to complain very often about it), but I don't have it anymore, so I'll go ahead and close this. Please ping me here if you're still affected by this bug while running Qtile 0.12+ and I'll reopen the issue.
