### ISSUE TITLE
Screen/tmux-like keybindings support (prefix followed by key instead of modifier + key)

### ISSUE THREAD

**Issue by dequis** [qtile/qtile#470]
Given a "prefix key" set to ctrl-a and a keybinding "n" for switch to next group (like screen's ctrl-a n), the following sequence should work:

```
key down ctrl-a
key up ctrl-a
(prefix mode set for the next keystroke)
key down n
key up n
(switch to next group, restore normal keybinding mode)
```

The ctrl-a could be considered two key down/up, but only the "a" with modifier matters.

Optionally, the "normal keybinding mode" could be restored after a timeout, not immediately, allowing to chain "ctrl-a n n n" if n is pressed quickly enough (tmux does this with the bind-key `-r` parameter, which stands for repeat, and timeout is configurable with `repeat-time`)

Originally suggested by qtile/qtile-examples#9

**Comment by traverseda** [comment]
One way you could handle this, a pretty flexible way, would be something like the django url dispatcher.

On keydown, start logging every keypress to a string. On keyup, send your list of key events through a bunch of regular expressions. First regular expression it hits triggers an action.

This would give you just a ridiculous amount of flexibility. You could do "(shift|mod4){2}" to represent pressing shift or mod4 in any order, or if you only want to trigger if they press mod4 and then shift "(mod4shift)". Want the reverse? Only trigger if they press shift then mod4? "(shift|mod4)", If course the actual regex would be using hex codes.

Plus you could match arbitrary key combinations. Do "(shift|mod4){2}.+" at the end of your list of keys to catch mod4+shift+whatever, where whatever is any key bindings that aren't already registered.

Of course since we're dealing with hex codes actually editing the raw regexes would be difficult. Mostly people would access it like they do now.

We'd also want a record of what the last (few?) key combos were so people could chain keybindings together.

**Comment by m-col** [comment]
#1777 provided this functionality with the key chords, right?

**Comment by ramnes** [comment]
Let's assume so. :)
