### ISSUE TITLE
Weird squarish border around system tray icons

### ISSUE THREAD

**Issue by RVSmooth** [qtile/qtile#5049]
### Issue description

![2024-10-20_06-13](https://github.com/user-attachments/assets/dff9ef2a-e3a9-4101-899b-17c74cc1f294)

my picom config: https://pastebin.com/5T5uem1M

* same issues with 0.29.0 as well 

### Version

0.28.2.dev0+gf1ed49bc.d20240813

### Backend

X11 (default)

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
This is expected behaviour. See the note in the Systray widget docs:
> Icons will not render correctly where the bar/widget is drawn with a semi-transparent background. Instead, icons will be drawn with a transparent background.
> 
> If using this widget it is therefore recommended to use a fully opaque background colour or a fully transparent one.

You can see if you have better luck with the `StatusNotifier` widget but not all apps are compatible with it.

This issue will be fixed if we ever implement pseudotransparency but it's not a high priority at the moment.

Closing this as it's a know, documented issue.
