### ISSUE TITLE
mashed title for UTF-8 in py3

### ISSUE THREAD

**Issue by zordsdavini** [qtile/qtile#548]
For example visiting http://xn--emaitj-m4ab33g.lt/ (žemaitėjė.lt) in title will show mashed characters. System locale is en-utf8 or lt-utf8

**Comment by zordsdavini** [comment]
@ixjlyons your patch works perfectly. I suggest to make a pull request for it

**Comment by flacjacket** [comment]
@ixjlyons Ultimately, I would argue xcffib should implement a `.to_utf8()` method doing that to deal with the [EWMH](http://standards.freedesktop.org/wm-spec/1.3/ar01s05.html) properties (in this case, `_NET_WM_NAME`). Then, a `._propertyUTF8()` method should be added which calls the xcffib method, keeping `._propertyString()` to deal with [ICCCM](http://tronche.com/gui/x/icccm/sec-4.html#s-4.1.2) properties.

**Comment by ixjlyons** [comment]
I submitted a pull request as suggested, but I've thought about it some more and I'm inclined to agree with @flacjacket. `xprop`, for example, outputs something like `_NET_WM_NAME(UTF8_STRING)`. This indicates to me that the library used for retrieving these properties should know it's Unicode (rather than byte-per-char as currently implemented) and decode it properly.

**Comment by tych0** [comment]
On Jan 9, 2015 1:12 PM, "ixjlyons" <notifications@github.com> wrote:
>
> I submitted a pull request as suggested, but I've thought about it some
more and I'm inclined to agree with @flacjacket. xprop, for example,
outputs something like _NET_WM_NAME(UTF8_STRING). This indicates to me that
the library used for retrieving these properties should know it's Unicode
(rather than byte-per-char as currently implemented) and decode it properly.

That's an interesting idea, actually. UTF8_STRING is in this case an atom
itself, so xcffib has no way of knowing directly how to decode it, which is
why we need a to_utf8 method.

However, we could add some sort of smarter decoder in qtile that would
figure all this out.

In any case, I think the right way is to implement to_utf8 and hardcore
it's use for now.

**Comment by flacjacket** [comment]
I think for most things, qtile can hard code in what to decode things as, I
think `_NET_WM_NAME` is always UTF8_STRING and `WM_NAME` is always STRING.
But, yes, I think that is the best way to go.

**Comment by tych0** [comment]
Ok, based on discussion I've posted

https://github.com/tych0/xcffib/tree/qtile-fixes
https://github.com/tych0/qtile/tree/wmname-is-utf8

which should be the fixes we've talked about here. If that works for everyone, I can merge to mainline and tag a new xfffib.

**Comment by flacjacket** [comment]
I think WM_NAME should stay as a string. You should also bump the xcffib
version requirement. Otherwise that looks good.
