### ISSUE TITLE
vivid (15.04) release in launchpad

### ISSUE THREAD

**Issue by delijati** [qtile/qtile#719]
can you create a vivid release in launchpad

**Comment by flacjacket** [comment]
@tych0 is the one in charge of the ppa, I don't know how much free time he has, but he's the one to ask

**Comment by tych0** [comment]
Hi,

I probably won't release one for the ppa any time soon (maintaining separate packaging branches is a pain :). However, all of the recent work with *cffi has made it so the packaging should be fairly simple to get it into debian proper, which will the percolate to ubuntu.

I've recently done an upload of xcffib, so once cairocffi uploads 0.7, I'll see about getting a qtile release tagged and sponsored for debian upload. Depending on how fast this happens, it could happen in time for inclusion in wily, but it seems more likely that it'll be in 16.04. A ping to the debian maintainers for cairocffi would help, although they seem fairly active since they're the ones who pinged me for an xcffib upload :)

Tycho

**Comment by dequis** [comment]
Vivid is dead, and sounds like newer stuff is covered by http://docs.qtile.org/en/latest/manual/install/ubuntu.html
