### ISSUE TITLE
MPD widget doesn't always connect

### ISSUE THREAD

**Issue by ff2000** [qtile/qtile#733]
It always shows the "not connected" message (Mpd off), regardless of the actual state of mpd.
Configuration should be fine, I run the defaults (localhost:6600).
I see this line in my qtile.log, which seems to be related, as I don't have it without mpd widget added:
```
2015-08-04 07:27:50,365 WARNING on_done:507 poll() returned None, not rescheduling
```
I'm on qtile:develop running python-3.4.1.

**Comment by ff2000** [comment]
Hm, sorry, party my fault. Didn't look at default_config but only the documented options in __init__(). Setting reconnect to True an the mpd widget starts working.
Still there needs to be something fixed as reconnect=False is the default and that case does not work even with mpd running.

**Comment by flacjacket** [comment]
Ah, yeah, that would probably be preferable. I don't use the mpd widget, so I'm not sure why the default is set to not reconnect

**Comment by ff2000** [comment]
Of course I could create a pull request to set reconnect=True, but as I said I think there is another issue, as the widget shows "Mpd off" even if mpd was running while qtile was started. Any idea why that happens? Do you need more information?

**Comment by mandaltapesh** [comment]
@ff2000   i want to work on this . Can you tell me which is the relevant code/file ?

**Comment by nicoe** [comment]
What happens is that the MPD widget initialize ThreadPoolText with the string used when there is no connection, then poll() is called but the widget is not connected and not set to reconnect so poll() returns None and is never called again.

My fix would be to use a different string ('MPD Widget') to initialize ThreadPoolText. Otherwise I don't think there is a bug.
