### ISSUE TITLE
Prompt widget stores duplicates in history

### ISSUE THREAD

**Issue by ff2000** [qtile/qtile#741]
Simply removing the launched command before appending it should be easy. But I wonder if there are better options. Should this be made optional? If not is there a better storage type in python that doesn't keep duplicates?

**Comment by soulchainer** [comment]
Prompt widget (tries to) duplicate behavior of the shell prompt. Every prompt shell I have used stores duplicates: if you repeat the same command two times, it's stored two times. If you do:

```sh
firefox
mousepad
zeal
qupzilla
mousepad
mousepad
```
It saves it that way, because these were the commands being executed, in that same order.
If not, I think that wouldn't be history (a record of last used commands), but a record of last unique used commands. That's at least, my opinion. So, what I'm saying is that prompt widget is not storing duplicates because there's a mistake or because there isn't a better storage that could allow it to not keep duplicates (I can't answer this question right know, because I'm a bit disconnected from using Python now, but I think it would be relatively easy to not store duplicates using the actual storage type), but because that is like a prompt with history is expected to behave.
History is optional (can be deactivated), but is setted by default to `True`.

Anyways, if you plan on one option to not store two lines with same command, I will be grateful if you keep that optional, because I wrote history option because I wanted (and use everyday) history ;).
BTW: I didn't fully understand your first sentence, could you elaborate it, please. Removing the launched command before appending it? Then you will have no history or record of any kind, because you won't be appending anything never, right?

**Comment by ff2000** [comment]
@soulchainer Inspect your webbrowsers history, it won't keep duplicates. Also every zsh config  I tried enables either HIST_IGNORE_ALL_DUPS or HIST_IGNORE_DUPS. Also most DEs/WMs I tried implemented non-duplicating history in some way (kde, awesome, lxqt and most likely some more).

Concerning the sentence you didn't understand: I tried to explain how zsh's HIST_IGNORE_ALL_DUPS is implemented:
"firefox, urxvt, gvim" is the history. Now you launch "urxvt". First remove urxvt: "firefox, gvim", then push it to the front: "urxvt, firefox, gvim" - you still have your whole history. Hope that was clear enough :)

**Comment by soulchainer** [comment]
Aha. Thanks for talking about the `HIST_IGNORE_ALL_DUPS`, `HIST_IGNORE_DUPS`. So, you agree that this should be an *option*, because is not the plain history behavior. Like I said previosly, if you keep that optional, I see no issue. You can write a `HIST_IGNORE_DUPS` *option* :D.

Thanks for clarify that sentence :).
> **First remove** urxvt: "firefox, gvim", then push it to the front: "urxvt, firefox, gvim" - you still have your **whole history**.

I'm sorry, but that doesn't look like *«whole»* at all, @ff2000.
So, like said: I think this will be a good *option*.
