### ISSUE TITLE
Z axis

### ISSUE THREAD

**Issue by ramnes** [qtile/qtile#753]
It would be nice to have some sort of Z axis information, which is completely missing today as far as I know.

That would fix at least #415 and #676, I guess.

**Comment by ramnes** [comment]
Would also fix #1260.

**Comment by ramnes** [comment]
One implementation could be to keep a z-ordered list of clients and then make `layout_all` iterate through that list to apply `bring_to_front` on each one. @flacjacket what do you think?

**Comment by ramnes** [comment]
Yeah, looks like it's how it's meant to be done: https://stackoverflow.com/questions/40257320/how-to-define-window-stacking-order/40259106

**Comment by tcld** [comment]
To get more into the code, I'll try my hands at #415 or #1260 and do what you suggested, @ramnes: Add in the facilities for keeping track of z-layers within a group and then draw them accordingly. It sounds suspiciously simple, so it is probably going to cause a million issues.

I am a little unsure how the z-layering would interact with the `focus_history` right now. If the lists were coupled (i.e. focusing a window brings it to the front, which might be expected behaviour), the entire idea of keeping track of the z-layers might be rendered moot, since the `focus_list` already does it.
A less automatic approach would require a few ways for the user to interact with the z-layering, and the result might be very much unintuitive to use.
It might even be best to just extend the `focus_history` list so it contains windows that were never focused. Then that list could be used for the z-layering and nobody would be confused.

Does anybody happen to have any input on this?

**Comment by tcld** [comment]
After some experimentation, I have a little code to show by now - any feedback would be welcome (the general approach might be completely off):
https://github.com/tcld/qtile/tree/feature_zlayering

There is still a lot to learn (utilizing tests, create an environment to test for #415, minimize flickering due to redrawing in `layout_all`, and possibly more).
I have a few ideas for how to improve the flickering, but my understanding of Qtile and especially the X11-backend are too limited right now.

Overall I wanted to add screen-layering (not window-layering) for fake-screens, so I have tried to set up the new class in a way that might allow to reuse it for that purpose later. The placement of the class as well as the formatting of the code are not final in the linked branch.

**Comment by ramnes** [comment]
Thanks for the work, glad to see it's moving forward!

Am I right in thinking that you assumed that giving focus to a window should always bring it to the front? I'm not sure we want this, and thus I'm not sure that we should merge history and Z layering. I don't have a strong opinion thought, but I'm a little afraid that one day someone will come to us with a use case that needs these two to be separate things, so I'd rather keep them separate for now if that doesn't make too much of a difference.

Also, what would you think of adding the Z-index directly inside windows objects, so that we don't have to keep another data structure for these, or to change the existing ones?

**Comment by m-col** [comment]
>Am I right in thinking that you assumed that giving focus to a window should always bring it to the front? I'm not sure we want this, and thus I'm not sure that we should merge history and Z layering. I don't have a strong opinion thought, but I'm a little afraid that one day someone will come to us with a use case that needs these two to be separate things, so I'd rather keep them separate for now if that doesn't make too much of a difference.

I agree that it would be a bad idea to always raise a window upon focus. One use
case would be when using a "sticky" window that is always at the top of the Z
axis but is rarely focussed. Perhaps we could add a snippet to the default
config of hooking into client_focus and raising it to the top. It would provide
that functionality and also serve to demonstrate hooks in the config, which
might be useful.

**Comment by tcld** [comment]
> Am I right in thinking that you assumed that giving focus to a window should always bring it to the front? I'm not sure we want this, and thus I'm not sure that we should merge history and Z layering. I don't have a strong opinion thought, but I'm a little afraid that one day someone will come to us with a use case that needs these two to be separate things, so I'd rather keep them separate for now if that doesn't make too much of a difference.

That is correct. Focusing a window would move it to the "front" (there are three layers with different priorities, each of which has its own "front"), but that would only be the case for stacked layouts or for floating windows (or if there are multiple fullscreen windows).
At the very least, I can see how that behaviour wouldn't be wanted for floating windows - I guess it would be better for the user to at least click on a window to raise it to the front. (If at all?)

Initially `focus_history` and `z_layering` were doing the same thing, so I replaced the former with the latter. It was only when using the new property for drawing in `layout_all` that the concerns started to conflict. Maybe the `_ZTracking`-class should actually be a `_History`-class and we could hold two of those (one for focus, one for z-levels). The `windows`-property is another one with a lot of overlap...

> Also, what would you think of adding the Z-index directly inside windows objects, so that we don't have to keep another data structure for these, or to change the existing ones?

The additional property would have to be managed from the group anyway, so I think the group should hold the data. Plus, the new datastructure could be used for managing fake screens, too (which is the feature I was initially after).
If anything, the z-levels could maybe be put into the `windows`-property by just reordering the windows. It would be a little less convenient, but it might produce the same results.

> Perhaps we could add a snippet to the default config of hooking into client_focus and raising it to the top. It would provide that functionality and also serve to demonstrate hooks in the config, which might be useful.

It would enable that functionality by default (which we all agree is not ideal). There are probably examples of hooks almost anybody would want, maybe we could find one of those and include that instead.

I will have another look at the code this evening and see if I can address the points you brought up. Thank you very much for the feedback!

**Comment by tcld** [comment]
I have done a few changes here and there, mostly as hinted at above (no commit yet, though). And I am now facing the problem of interacting with the z-layers:
So far it *has* been the case that a change of focus changed the z-layer of a window (at least in the cases that come to my mind, like switching windows in a max layout). Therefore there really seems to be no generalized way (yet) to interact with the z-layers. "Clicking" a window, as I suggested above, would be the only existing way of interaction I can think of - and for a tiling WM that is just not enough.

So what kinds of interaction with the z-layering would you suggest? Maybe give each group a setting to select between "automatic/grouped" (which is how my first commit should handle it), "automatic/nongrouped" (which would be as close as possible to how things are handled now) and, maybe, "somewhat manual but not so much that the experience suffers"?

I'll think about this in between meals and work hours, but it might take a bit of time.

**Comment by ramnes** [comment]
Let's just keep the current behavior? i.e. floating windows on top, with the reordering happening when a floating window is moved. I think it's pretty sane. The only thing I would change is that currently, if we spawn a new tiled window, it will be above the floating windows, and I'd rather want it behind. And I guess it would be a nice and quick addition to write commands to move the current window behind or above for even more control.

About the Z-axis being handled directly inside windows, there are two ideas behind this that I should have explained before, I'm sorry:
* x and y are already handled that way, and as a user I'd prefer the API to be consistent
* z being an integer, and not an index in a list, we could do things like `window.z = 9999` for screen lockers and such

**Comment by tcld** [comment]
I finally found some time to continue working on this. An actual z-property for the windows is not yet added, since I think that might require a number of changes in other places, too (e.g. any method to place windows).
This is what a z-property would do:
Have a default value of 0 which is *not* changed by layouts (there might be some edge-cases I am overlooking). Unless a user explicitely changes the z-property of a window, this would result in everything behaving as usual. The priorisation of the layering would happen as follows:

1. Group windows by "normal", "floating" and "fullscreen". They will be layed out in that order, with fullscreen on top. This would address #1260 . If screensavers have their fullscreen-flag set, issue #676 would also be addressed.
2. Order each of those groups by the z-properties of their windows. The highest z will be on top within its group. For equal z's, the order of windows will be retained.

I readded the `focus_history`, although right now it does almost the same as the `z_layering`-property. I also made it so that "normal" windows are only layed out in `layout_all` if they belong to a max- or stack-layout. In all other layouts there should only be one layer of normal windows - this gets rid of the flickering I mentioned above (although there is more that can be done here) while still addressing #415 .

Does that sound sane so far?

The next steps right now would be to add a z-property to windows, make it usable somehow, and eventually add more checks to `layout_all` to minimize flickering due to redrawn windows in all situations.

**Comment by m-col** [comment]
I just want to add that it might be a good idea to incorporate the [recommended stacking order](https://specifications.freedesktop.org/wm-spec/1.3/ar01s07.html#STACKINGORDER) of windows with specific hints (I don't think this has been discussed already). I.e. we should respect `_NET_WM_STATE_ABOVE` as this is used by some windows that want to stay on top of others. This could then be added by Qtile to windows that a user wants to always on be on top so deal with #1260. I think we should also put `_NET_WM_TYPE_DOCK` and `_NET_WM_TYPE_DESKTOP` windows in the recommended position, and perhaps an option to put `_NET_WM_WINDOW_TYPE_NOTIFICATION` windows either above all or behind fullscreen windows.

**Comment by tcld** [comment]
@m-col: That's a very good point, thanks for bringing it up. I really don't have any experience tinkering with window managers myself (yet).

As far as I see it this means that, after adding at least a rudimentary z-property to windows, I would have to ... "intercept" these hints and assign the z-values (Can these hints change over time?). I would go with -9999, -99, 0, 99 and 9999. This would mean that the user is still allowed to screw things up, if he really wants to.

**Comment by m-col** [comment]
> Can these hints change over time?
As I understand it, WM_TYPE hints are fixed but WM_STATE hints can change. You can get the type hint for a given window at `Window.window.get_wm_type()`. The possible values that can be returned by that can be seen [in this dict](https://github.com/qtile/qtile/blob/master/libqtile/backend/x11/xcbq.py#L115). Perhaps we should cache the result of `get_wm_type` if it is indeed fixed.

Also when putting together the stacking order you'll only have to test the state of normal windows that aren't docks, desktops, notifications or fullscreen, because the type would in those cases determine stacking order. I can't think of a scenario where a normal tiled window will suddenly set `_NET_WM_STATE_ABOVE`. Most windows that set that hint are relatively small windows that I imagine most people will auto-float. In any case, if somebody is tiling small popup windows then they probably won't care about that state. So maybe: don't consider state or type for tiled windows in a group, for floating and fullscreen windows use the state, and everything else look at the type.

**Comment by ramnes** [comment]
At this point can you maybe open a PR and make it WIP so that we can discuss the implementation here? :)

**Comment by tcld** [comment]
Done. I didn't want to open a PR initially because there is likely a lot that still needs to be done - but you are right, it will make the discussion easier.

**Comment by m-col** [comment]
#1145 is yet another issue that this would fix
