### ISSUE TITLE
Focus should cycle through floating windows on `cmd_next`

### ISSUE THREAD

**Issue by 0ion9** [qtile/qtile#794]
Frankly, this behaviour -- where there is a window I can see on screen but I cannot cycle focus to it with the keyboard -- is quite frustrating. I understand the technical reasons why doing the 'simplest possible thing' results in this outcome (floating windows are kept in a separate layout instance), but personally I cannot imagine that this is a desirable default behaviour.

What about, when cycling the last window in base layout is focused and the user tries to cycle 'forward' (or 'up' as lazy.layout calls it), it goes to the first item in floating layout, and vice versa?

Currently, you can cycle from a floating client to one in base, but not the reverse.

**Comment by flacjacket** [comment]
Just tested this, I see what you mean, this should be fixed, but glancing through, it may have to be implemented on a layout-by-layout basis.

**Comment by flacjacket** [comment]
So thinking about this, `lazy.group.next_window` is probably what you want, as that will cycle through the floating layout once it has run through the not-floating windows. We should maybe make this distinction more clear, but I think leaving `layout.cmd_next` as-is is better, since the floating layout is associated to the group, rather than the layout. With that said, I'm closing this for now, feel free to re-open if there is still something that you see can be improved upon.

**Comment by dranzer9944** [comment]
## Cycle through floating
@lazy.window.function
def float_to_front(window):
    if window.floating:
        window.cmd_bring_to_front()
    else:
        window.cmd_bring_to_front()
        window.cmd_disable_floating()


 Key(["mod1"], "j",
                lazy.group.next_window(),
                float_to_front(),
                desc="move focus to next window"
                ),
that's works for me you can try that.
And sorry for formatting problem in text i am new to linux community
