### ISSUE TITLE
Please allow tests to run with xvfb

### ISSUE THREAD

**Issue by irl** [qtile/qtile#906]
In packaging qtile for Debian I have had issues in running the nose test suite as our builds run
on headless machines that do not have an X server available.

Instead of Xephyr, can you provide the option of running the tests using xvfb as an alternative?

http://www.x.org/releases/X11R7.6/doc/man/man1/Xvfb.1.xhtml

**Comment by flacjacket** [comment]
We do run our test suite on Travis, by running the Xephyr instances on Xvfb. When we were setting that up I recall there was some issue with running straight on Xvfb, but I can't think of what that was off the top of my head. If running Xephyr on Xvfb is ok, I can try to make that setup easier to run, rather than having to configure it manually as we currently do for Travis.

**Comment by irl** [comment]
This sounds like a reasonable way to do it.

I've uploaded qtile to Debian with tests disabled currently, as I have run the tests locally and they have passed.

https://lists.debian.org/msgid-search/E1avmKN-00085k-0W@franck.debian.org/firsthit

(Link may not yet be active)

**Comment by flacjacket** [comment]
@irl I was able to get the tests setup to run on a Xephyr instance on Xvfb by default, so new versions should be easier for you to run tests on. If you have a timeline that you want a new version, just let us know!

**Comment by irl** [comment]
Awesome thanks. (:

I'm happy to update the package in Debian whenever, my first upload was rejected by our license control people as I'd not specified some of the licenses correctly (3 files are GPL-3+ not MIT apparently).

I'll fix that issue and reupload the current release, and I'll build a version based on master to test out the builds in our build system and let you know if I have any issues.
