### ISSUE TITLE
How to call cmd_next_keyboard from config.py ?

### ISSUE THREAD

**Issue by andering** [qtile/qtile#929]
Hello,
i don't understand how to call function from widget in `config.py`,
specifically switching keyboard layout,
 from widget [keyboardlayout](https://github.com/qtile/qtile/blob/develop/libqtile/widget/keyboardlayout.py) function `cmd_next_keyboard()`

I thought `lazy.keyboard.next_keyboard()`, but not

**Comment by flacjacket** [comment]
You probably need something like `lazy.widget["keyboardlayout"].next_keyboard()`

**Comment by flacjacket** [comment]
You can check by running `qshell`, doing `cd widget`, then `ls` to see the widget names available

**Comment by andering** [comment]
Thank you very much.

**Comment by andering** [comment]
I additional question,
do you know if/how is possible to define Key() just for "Mod4 + Shift",
i tried:

```
Key(["mod4"], "Shift", ...)
Key(["mod4"], "shift", ...)
Key(["mod4", "shift"], "", ...)
Key(["mod4", "shift"], None, ...)
```

but nothing really works.
Thank you.

**Comment by andering** [comment]
Figured out, sorry.
Key(["mod4"], "Shift_L", ...)

**Comment by flacjacket** [comment]
No problem, glad you figured it out!

**Comment by dexic79** [comment]
Hi Andrej,
as a experienced user, but no-python-at-all-guy-until-now, can you please show the whole code line for the keyboard layout switch? Why is there no comment with an example, how the key binding could look like, so that "average users" can make the most of it fast. I mean: I shall work on the config once and then let it work until the computer dies! ;-)
