### ISSUE TITLE
Remap key

### ISSUE THREAD

**Issue by andering** [qtile/qtile#955]
Hello, does anybody knows how to swap (remap) two keys.

I got some wireless keyboard with swapped window button and alt button.
so i need to swap key(code) 133 and 64.

I was trying to make it through xmodmap and setxkbmap , but with no success.

Thank you.

**Comment by soulchainer** [comment]
Ummm...  This doesn't have much to do with qtile, but OK, I will respond, and, with luck, at least the issue will be closed.
Because I do this everyday: I recover an old mechanical keyboard from 1990 and I'm using it everyday. It's old enough for not having the `Super` keys, so I have to remap these and also repurpose Scroll_Lock.

Basically, I type everyday `xmodmap .Xmodmap` (I should check to automatize it, but well... xD).

`.Xmodmap` is a file where I pass the desired config to `xmodmap`. Just to you grasp the idea, I will reproduce my `.Xmodmap`:

```
!Scroll_Lock is now Control_R
keycode 78 = Control_R
!Control_R is now Super_L
keycode 105 = Super_L
keycode 37 = Control_L
!Change modifiers
clear Control
!clear Mod1
!clear Mod2
!clear Mod3
!clear Mod4
!clear Mod5
add Control = Control_L Control_R
```
Explanation:

- Made single one-side asignation of keys, just indicating the `keycode target_keynumber = name_of_new_desired_key`, data that you can get with `xev`.
- `!comment` is a comment.
- Changing `modifier` keys is a bit different. You first need to `clear` the modifiers you want to change (rest you left commented), that could have more than one key associated, and then you `add` them, and associate the desired keys.

You can read about all this [here](https://wiki.archlinux.org/index.php/Xmodmap).

So, in your case, I think it would be something like this:

```
keycode 133 = name_of_key_64
keycode 64 = name_of_key_133
```

This only if none of them is a modifier key. If they're, you need to use the explained modifiers stuff.
You would apply this, as I said, with `xmodmap .Xmodmap`. I guess you can then add a line in your `config.py` to execute it with the qtile startup. I didn't try still. I should do it :þ. Doing it in `.xinitrc` doesn't work.

**Comment by ramnes** [comment]
`setxkmap us altwin:swap_lalt_lwin` should do just fine. :wink: 

See `/usr/share/X11/xkb/rules/evdev.lst` for a list of all `setxkbmap` options.
